Statistics
Mstrutov/Desbordante pull request #109
Opened 2022-05-12 04:33 UTC by nikita-talalai

Измениял условия сравнения в компораторе, чтобы правильно работал алгоритм std::nth_element.
Добавил геттеры расположения null'ов и empties, так как они нужны в методах, чтобы не было seg fault.

Пока что непонятно, как тестить квантили, что брать за эталон. Есть несколько способов их вычисления, например, значения, высчитанные в электронных таблицах, в большинстве случаев, не будут совпадать с результатом методов.

ShowSample на null'ах и emties выдает: "Meaningless operation. Use EmptyType or NullType methods directly". Как это обойти,я не понял.

2022-05-14 14:26 UTC, polyntsov requested changes
Довольно много чего нужно поправить и обсудить (:
А еще мне кажется, что коммит-месседжи стоит сделать более понятными. `Add some statistics` и `Add all statistics` -- совсем размыто и непонятно

2022-05-14 14:26 UTC, polyntsov commented on src/statistics/CsvStats.cpp
> +std::optional<std::pair<std::byte const*, mo::Type const*>> CsvStats::CountCentrlMomntOfDist(
Этот метод почти целиком повторяет `GetSTD` (потому что deviation это корень из второго central moment)

2022-05-14 14:26 UTC, polyntsov commented on src/statistics/CsvStats.h
> +    std::optional<std::pair<std::byte const*, mo::Type const*>> GetQuantile(double part, int index);
Мне в целом не нравится весь этот дизайн с `std::optional`, который всегда пустой, если колонка не `Numeric`. Не очень понятно зачем, по-моему горадо лучше было бы иметь доступ к `TypedColumnData` и из него получать доступ к типам, а не возвращать тип из метода, который должен считать статистику. А в этих функциях, например, выкидывать исключение (хотя возможно тоже не лучший вариант), если статистику над колонкой не посчитать. Вообще надо обсудить, как это будет отдаваться на веб, возможно стоит считать все статистики сразу в одном `execute()`, а в таких методах просто отдавать их. Ну и очевидный минус -- здесь статистики при каждом вызове метода пересчитываются заранее при том, что табличка не меняется и результат всегда один и тот же (кроме статистик с параметрами: `Quantile` и `CentrlMomntOfDist`). А еще не нужно сокращать названия удаляя гласные буквы выглядит ужасно. И `StndrtCentrlMomntOfDist` на самом деле standardized moment, кажется, а не standard moment (t там определенно в конце нет)

2022-05-14 14:26 UTC, polyntsov commented on src/statistics/CsvStats.h
> +    std::optional<std::pair<std::byte const*, mo::Type const*>> GetQuantile(double part, int index);
А еще тут для индексации везде используется `int`, я бы предпочел `unsigned`, индекс все-таки.

2022-05-14 14:26 UTC, polyntsov commented on src/statistics/CsvStats.h
> +    std::optional<std::pair<std::byte const*, mo::Type const*>> GetQuantile(double part, int index);
И для методов статистик не хватает описания

2022-05-14 14:26 UTC, polyntsov commented on src/statistics/CsvStats.h
> +class CsvStats {
Не очень понятно, насколько оправдано то, что этот класс не наследуется от `Primitive` и получает в конструкторе имя датасета (так кажется точно быть не должно). Это в целом надо обсудить
Отсутствие наследования, например, добавляет еще одно место с захардкоженным путем для датасетов "inputData" (в функции `CreateColumnData`), что мы, вообще-то, хотим #105 исправить

2022-05-14 14:26 UTC, polyntsov commented on src/statistics/CsvStats.cpp
> +        model::ColumnLayoutTypedRelationData::CreateFrom(input_generator, true, -1, -1);
Тут не нужно передавать просто `true` в качестве параметра `is_null_equals_null`. Это конечно не важно, когда мы просто игнорируем нуллы, но когда-нибудь может стать важно. Вообще, я думаю, что этот параметр должен передаваться со всеми остальными через структуру конфиг, как это делается для всех примитивов

2022-05-14 16:09 UTC, nikita-talalai commented on src/statistics/CsvStats.cpp
> +    int counter = 0;
counter здесь нужен был для того чтобы единственный раз проинициализировать min, когда мы наткнемся на корректный элемент, не null и не empty(изначально проинициализировать min каким-то элементом колонки не получится, так как он может оказаться  некорректным), дальше он не используется. i == 0 не подходит, т.к. первый элемент колонки также может быть некорректным. Кажется, nullptr подойдет.

Если табличка пустая, тогда выполнение не должно дойти до этого места, так как в начале производится проверка.

2022-05-14 16:26 UTC, nikita-talalai commented on src/statistics/CsvStats.cpp
> +        for (int j = start_col - 1; j <= end_col - 1; ++j) {
Это я делал для смещения точки отсчета в (0;0). А пользователю вводит номера строк и столбцов, считая от 1.

2022-05-14 16:29 UTC, nikita-talalai commented on src/statistics/CsvStats.cpp
> +void CsvStats::ShowSample(int start_row, int end_row, int start_col, int end_col, int str_len,
Да, просто печатаест часть таблицы, это предполагалось для интерактивного взаимодействия с таблицей через консоль.

2022-05-15 10:25 UTC, polyntsov commented on src/statistics/CsvStats.cpp
> +#include <math.h>
Не думаю, что стоит использовать сишные хедеры в новом с++ коде. Здесь точно можно обойтись без этого хедера, тем более снизу уже подключается его с++ версия `cmath`.

2022-05-15 10:26 UTC, polyntsov commented on src/statistics/CsvStats.cpp
> +    return this->Distinct(index) <= quantity ? true : false;
`this->Distinct(index) <= quantity` имеет тип bool, тернарный оператор тут лишний. Просто
`return this->Distinct(index) <= quantity;`

2022-10-09 07:42 UTC, Mstrutov commented
development was continued in #120

2022-10-09 07:42 UTC, closed without merging