Multidimensional Metric FD
Mstrutov/Desbordante pull request #115
Opened 2022-07-11 14:04 UTC by Aviu00

Implements calipers MFD verification algorithm for 2d euclidean metric.
Implements brute force and 2-approximation algorithms for multidimensional euclidean metric.
Fixes typo.

2022-07-20 09:54 UTC, polyntsov commented
Можешь, пожалуйста, разбить один этот коммит на несколько по логически законченным частям (например, где-то ты исправлял опечатки или у `MetricVerifier::parameter_` заменил тип на long double, это явно может быть отдельным коммитом). Так будет проще ревьюить и потом разбираться в истории. И заодно поправь коммит месседж(и), чтобы они выглядели как описано в вики, и напиши где-нибудь комменатрий о том, что такое MFD (:

2022-08-02 12:39 UTC, polyntsov requested changes
Изменения в `main.cpp` придется подправить, после того, как примут #117, но там немного

2022-08-02 12:39 UTC, polyntsov commented on tests/TestMetricVerifier.cpp
> +                          std::vector<unsigned int> const& rhs_indices,
можно принимать по значению и делать `move` в params, избавимся от копирования (то же самое с `lhs_indices`), но тут это конечно абсолютно некритично

2022-08-02 12:39 UTC, polyntsov commented on src/util/ConvexHull.cpp
> + */
Этот комментарий нужно переместить в хедер и заодно пометить в нем, что эта функция меняет (сортирует) свой аргумент, чтобы вызывающий код был готов к этому

2022-08-02 12:39 UTC, polyntsov commented on src/main.cpp
> +#include <set>
а зачем?

2022-08-02 12:39 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +}
Эту функцию я бы сделал статической у `Point`: `Point::EuclideanDistance()`, выглядит как полезная общая функциональность для точек

2022-08-02 12:39 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +            break;
Это тоже хочется вынести в отдельную функцию `GetComparatorForMetric()`

2022-08-02 12:39 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +                : model::Type::GetValue<long double>(col.GetData()[i]);
Кажется, что нужно сделать метод у `TypedColumnData`, который будет делать это.
`col.GetValue<long double>(index)` внутри просто вызывающий
` model::Type::GetValue<long double>(col.GetData()index])`

2022-08-02 12:39 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +std::optional<std::vector<T>> MetricVerifier::GetVectorOfPoints(
А тут обязательно `optional`? Почему нельзя просто пустой вектор?
вообще кажется, что можно заранее (вне этой функции) проверять, что в колонках есть пустые значения (количество нуллов и пустых значений хранится в `TypedColumnData`) и `dist_to_null_infinity_ == true`

2022-08-02 12:39 UTC, polyntsov commented on src/algorithms/MetricVerifier.h
> +    std::function<long double(std::byte const*, std::byte const*)> GetCosineDistFunction(
Я бы сделал приватный элиас для `std::function<long double(std::byte const*, std::byte const*)>`, менее громоздко, более читабельно
А еще ты используешь `std::function`, хедер для которого не подключается в этом файле, а подключается транизитивно в каком-то из инклудов, [так делать не надо](https://google.github.io/styleguide/cppguide.html#Include_What_You_Use), подключи явно `#include <functional>`

2022-08-02 12:47 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +long double GetDistanceBetweenPoints(std::vector<long double> const& p1,
Для функций, которые не предполагается использовать вне данного файла, используй `static`

2022-08-03 09:41 UTC, Aviu00 commented on src/algorithms/MetricVerifier.cpp
> +    for (int i = 0; i < (int)cluster.size() - 1; ++i) {
У меня как-то слишком часто ошибки возникают из-за unsigned значений в цикле

2022-08-03 10:06 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +    for (int i = 0; i < (int)cluster.size() - 1; ++i) {
Это довольно странно при условии, что цикл обычный (от 0 до n). Среди этих изменений я видел кажется только один, где `int` применимо (там было условие `i >= 0`)

2022-08-04 18:22 UTC, polyntsov requested changes
Минорные замечания по стилю. Ждем пока примется #117 и можно мерджить

2022-08-04 18:22 UTC, polyntsov commented on tests/TestMetricVerifier.cpp
> +#include <vector>
тут кстати неправильный порядок хедеров (:
Сначала стандартные, потом библиотченый `gtest`

2022-08-04 18:22 UTC, polyntsov commented on src/main.cpp
> +        vm.at("lhs_indices").value() = lhs_indices;
Мне в целом не кажется правильным, что код, который проверяет правильность задания параметров алгоритма находится тут (хотя выше также проверяется `error`). Потому что когда появится питоновская библиотека, она по идее не должна проверять параметры на правильность, а просто передавать их в с++ код и в случае чего получать ошибку. Сложно. Наверное, пока можно оставить так, все равно эту часть менять скоро будем

2022-08-04 18:22 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +                    return points;
Просто `return {};`, тут лишняя работа делается

2022-08-04 18:22 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +    for (int i = 0; i < (int)points.size() - 1; ++i) {
Все еще не понимаю, зачем тут `int`. Когда вижу этот код с явными приведениями, начинаю думать о том, что они здесь зачем-то нужны и i видимо бывает отрицательным, хотя это не так. Я бы все же предпочел `size_t`
@Mstrutov

2022-08-04 18:22 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +            max_dist = std::max(max_dist, GetDistanceBetweenPoints((points)[i], (points)[j]));
а зачем скобки вокруг `points`?

2022-08-05 01:05 UTC, Aviu00 commented on src/algorithms/MetricVerifier.cpp
> +    for (int i = 0; i < (int)points.size() - 1; ++i) {
Там могло оказаться, что массив точек пустой, но раз там это сверху проверяется, то приводить теперь уже не нужно

2022-08-05 18:36 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +    for (int i = 0; i < (int)points.size() - 1; ++i) {
Это кажется не единственное место, где ты делаешь такие приведения к `int`, я тут про все такие сразу писал (где i не предполагается отрцательным) (:

2022-08-06 05:25 UTC, Mstrutov commented on src/algorithms/MetricVerifier.cpp
> +    for (int i = 0; i < (int)points.size() - 1; ++i) {
Согласен с Михалиом, стоит везде в циклах, где итерируемся по неотрицательным значениям, использовать `size_t`. Если из `size_t` приходится что-то вычитать, как здесь, можно ещё использовать `std::max(points.size(), 1) - 1`. Если понадобится в нескольких местах, можно вынести в статическую функцию типа `size_t decrementUnsinged(size_t x)`.

2022-08-06 12:14 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +    for (int i = 0; i < (int)points.size() - 1; ++i) {
Или просто перенести -1 влево: `i + 1 < points.size()`

2022-08-07 14:07 UTC, polyntsov approved these changes
LGTM!

2022-08-07 14:08 UTC, merged