Implement aidfd
Mstrutov/Desbordante pull request #116
Opened 2022-07-30 13:30 UTC by rakhmukova

Implement AIDFD and SearchTree data structure used in the algorithm

2022-07-31 16:03 UTC, polyntsov requested changes
Нужно поправить пару мест
И, пожалуйста, прогони свои изменения через clang-format (:

2022-07-31 16:03 UTC, polyntsov commented on src/algorithms/AIDFD/SearchTree.cpp
> +    auto node_set = current_node->set_;
Тут создается ненужная копия

2022-07-31 16:03 UTC, polyntsov commented on src/algorithms/AIDFD/Aid.cpp
> +    sort(attr_indices.begin(), attr_indices.end(),
`std::sort`, чтобы было явно видно

2022-10-09 07:38 UTC, Mstrutov approved these changes

2022-10-09 07:40 UTC, Mstrutov commented
@polyntsov all comments were addressed and necessary fixes were done, go approve

2022-10-09 13:04 UTC, polyntsov approved these changes

2022-10-09 13:04 UTC, merged