Better command line parsing
Mstrutov/Desbordante pull request #117
Opened 2022-07-30 17:22 UTC by BUYT-1

Changes:

- Split the command line arguments into different groups (easier to read for the user and programmer alike)
- Use constants for command line argument strings (easier maintenance)
- Use bool_switch for some arguments (more intuitive)

2022-07-30 17:25 UTC, BUYT-1 commented
Теперь разобрался получше и лично убедился, что надо много чего переделывать.
Мёрж по желанию, но вот это вот может помочь в таких переделках потом.
Не уверен, что всё, что между квадратными скобками заменённое корректно семантически, т.е. что это именно аргументы командной строки, а не просто строка "error" в другом контексте.

2022-07-31 11:41 UTC, polyntsov requested changes
Хорошие изменения, в правильную сторону (:
Возможно все, что касается описания опций командной строки придется потом выкинуть (с написанием клиента на питоне), но ничего
Нужно поправить только кодинг стайл и можно вмерджить

2022-07-31 11:41 UTC, polyntsov commented on src/util/ProgramOptionStrings.h
> +    const char * const QGramLength = "q";
Тут можно (и стоит) использовать `constexpr`. Строковые литералы имеют тип `const char[n]`, а не `const char*`, поэтому кмк лучше написать точный тип (на самом деле это вкусовщина и не должно вообще ни на что влиять). Либо вообще `auto`:
```cpp
constexpr auto Help = "help";
```

2022-07-31 11:41 UTC, polyntsov commented on src/util/ProgramOptionStrings.h
> +namespace ProgramOptionStrings {
Пространства имен [именуются](https://google.github.io/styleguide/cppguide.html#Namespace_Names) snake_caseом

2022-07-31 11:41 UTC, polyntsov commented on src/util/ProgramOptionStrings.h
> +}
после закрывающей фигурной скобки: `}  // namespace program_option_strings`

2022-07-31 11:41 UTC, polyntsov commented on src/util/ProgramOptionStrings.h
> +#define SEPARATOR "separator"
Google style guide очень [не любит](https://google.github.io/styleguide/cppguide.html#Preprocessor_Macros) макросы, особенно в хедер файлах. Тут на самом деле кажется, что он не нужен, он используется только для инициализации `SeparatorConfig` и `SeparatorLibArg`, у которых есть общая строка "separator". Но при этом кажется, что семантически они не обязаны иметь вообще что-либо общее (только если мы строго решаем называть опции в конфиге ровно так же, как названы соответствующие параметры командной строки)

2022-07-31 11:41 UTC, polyntsov commented on src/util/ProgramOptionStrings.h
> +namespace ProgramOptionStrings {
Я бы наверное переименовал в `program_option_names`. @Mstrutov ?

2022-07-31 11:41 UTC, polyntsov commented on src/algorithms/AlgoFactory.h
> +namespace posr = ProgramOptionStrings;
Псевдонимы для пространств имен тоже [должны](https://google.github.io/styleguide/cppguide.html#Namespaces) находиться в пространстве имен текущего файла. При этом в хедер файлах они разрешены только внутри неймспейсов, которые явно помечены как не часть интферфейса (в этом случае это неймспейс `details`). Туда и стоит перенести этот алиас

2022-07-31 11:41 UTC, polyntsov commented on src/algorithms/TypoMiner.h
> +namespace posr = ProgramOptionStrings;
То же самое про псевдонимы для неймпесов, что и в `AlgoFactory.h`. Только тут нет неймспейса ниже уровнем, который не часть интерфейс. Поэтому этот псевдоним надо либо убрать, либо можно перенести в функцию, где он используется

2022-07-31 11:41 UTC, polyntsov commented on src/main.cpp
> +#include "ProgramOptionStrings.h"
Сверху лишняя пустая строка

2022-07-31 11:41 UTC, polyntsov commented on src/main.cpp
> +         "possible.")
Лучше оставить предыдущее описание, оно гораздо более точно описывает, что произойдет, если не указать этот параметр (твое описание вообще-то неверное, если быть точным).

2022-07-31 11:41 UTC, polyntsov commented on src/main.cpp
> +         "specify whether two nulls should be considered equal")
Тут я бы все же явно обозначил, что такое null (это не пустое значение, а именно "NULL").

Хм, а учитываем ли мы регистр (и хотим ли, если нет)? @Mstrutov

2022-07-31 11:41 UTC, polyntsov commented on tests/TestAlgoInterfaces.cpp
> +namespace posr = ProgramOptionStrings;
этот файл надо бы обернуть в `namespace tests {}` (:

2022-07-31 11:41 UTC, polyntsov commented on tests/TestMetricVerifier.cpp
> +namespace posr = ProgramOptionStrings;
Должно быть внутри namespace'a

2022-07-31 11:41 UTC, polyntsov commented on tests/TestTypoMiner.cpp
> +namespace posr = ProgramOptionStrings;
Должно быть внутри

2022-07-31 11:41 UTC, polyntsov commented on tests/TestingUtils.h
> +namespace posr = ProgramOptionStrings;
Не должно быть в хедер файле в глобальном неймйспейсе, можно перенести в функцию ниже

2022-07-31 14:21 UTC, BUYT-1 commented on src/util/ProgramOptionStrings.h
> +#define SEPARATOR "separator"
Я тут просто исхожу из того, что написано: значения потом вытаскиваются из бустовского хранилища. В данном случае строкой "separator", которая совпадает с длинной формой аргумента командной строки, т.к. так работает `boost::program_options`, но бусту мы передаём не только её, но ещё и короткую форму. В итоге, покуда мы сидим на бусте, и получается `SEPARATOR` и `SEPARATOR ",S"`.

2022-07-31 14:42 UTC, BUYT-1 commented on src/main.cpp
> +         "possible.")
> твое описание вообще-то неверное, если быть точным

Хм, а разве оно не просто шире? Ну, типа железо не позволяет использовать больше чем N потоков, значит больше использовать невозможно, значит используется столько потоков, сколько возможно?

2022-07-31 16:27 UTC, polyntsov commented on src/main.cpp
> +         "possible.")
Железо может выполнять не больше, чем N потоков concurrently. При этом просто выполнять оно может, я думаю, сколько угодно потоков. Для производительности в случае алгоритмов майнинга ФЗ заводить больше потоков, чем N смысла не очень много имеет (скорее всего станет хуже), но это все же возможно сделать

2022-07-31 16:34 UTC, polyntsov commented on src/util/ProgramOptionStrings.h
> +#define SEPARATOR "separator"
а, ну да, из буста оно достается по длинной опции. Но мне все равно кажется, что можно просто сделать без него, так как стайл-гайд против макросов, кроме случаев, где иначе никак. Тут по идее совсем не такой случай. @Mstrutov

2022-08-03 08:51 UTC, BUYT-1 commented on src/util/ProgramOptionStrings.h
> +#define SEPARATOR "separator"
Ну, чёрт его знает, сделал без. Не думаю, что стало лучше.

2022-08-03 09:06 UTC, BUYT-1 commented on src/util/ProgramOptionStrings.h
> +#define SEPARATOR "separator"
> But before using a macro, consider carefully whether there's a non-macro way to achieve the same result.

Ну вот мне нужно две строки соединить. Без макро этого не получится без танцев с бубном.

Я как бы сделал без макро, но там тогда опять эта старая проблема с тем, что `"separator,s"` -- это обычная строка, которая формально не зависит ни от чего.
Тем более, что гайду в целом не нравится, когда макросы как функции используют. Вот такое использование там упоминается, но как такое, которое обычный C++ не позволяет: `some of their special features (like stringifying, ->concatenation<-, and so forth) are not available through the language proper`. 

Так что тут можно сделать исключение, я думаю, тем более, что даже в самом гайде как бы написано вот так: `If you understand what goals each rule is serving, it should be clearer to everyone when a rule may be waived (some can be)`.

2022-08-03 09:07 UTC, polyntsov commented
Когда исправляешь замечения из ревью, лучше меняй уже сделанные коммиты и пуш через `--force`, чтобы оставлять историю +- чистой, потому что коммиты в пулреквесте вида "добавил А", "убрал А" выглядят странно

2022-08-03 09:08 UTC, BUYT-1 commented on src/util/ProgramOptionStrings.h
> +namespace ProgramOptionStrings {
> Я бы наверное переименовал в `program_option_names`.

Имеет смысл, если там нет `"separator,s"`. А так нет, `"separator,s"` не название/имя.

2022-08-04 18:28 UTC, polyntsov requested changes
Перенос строки в конце файла, в остальном хорошо, ждем Максима и можно мержить

2022-08-04 18:28 UTC, polyntsov commented on tests/TestAlgoInterfaces.cpp
> +}  // namespace tests
Гитхаб хочет перенос строки в конце файла

2022-08-04 18:28 UTC, polyntsov commented on src/util/ProgramOptionStrings.h
> +#undef SEPARATOR
По идее такое решение и не распространяет макрос дальше и позволяет избежать ручного копирования строки "separator", так что наверное подходит
Но я все же хочу аппрув от @Mstrutov (:

2022-08-06 05:11 UTC, Mstrutov commented on src/util/ProgramOptionStrings.h
> +#undef SEPARATOR
Думаю, так оптимально, да.

2022-08-06 05:13 UTC, Mstrutov commented
@polyntsov сможешь заапрувить и помёржить?

2022-08-06 11:38 UTC, polyntsov approved these changes
LGTM

2022-08-06 14:19 UTC, merged