Implement metric FD data highlights
Mstrutov/Desbordante pull request #118
Opened 2022-08-09 07:44 UTC by Aviu00

Adds highlights of data that is processed during MFD verification. That allows the user to get detailed information about the distribution of distances between values if metric FD does not hold.

2022-10-09 15:49 UTC, polyntsov requested changes
- Прогони изменения через clang-format.
- Шаблоны читать сложно.
- Из-за того, что `highlights` считаются одновременно с проверкой MFD, код сильно усложняется -- передаются пары, которые выводятся через `auto`, вместе с шаблонами совсем тяжело. Думаю, эту функциональность надо разделить и подумать о том, как переиспользовать то, что уже написано в `TypoMiner`, там есть почти такая же функциональность

2022-10-09 15:49 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +                }
`algo_` не меняется во время проверки фз на разных кластерах, поэтому этот `if` нужно вынести наружу. При этом он только выбирает, какую функцию вызывать, аргументы у функций одинаковые, поэтому, думаю, стоит сделать как-то так:
```cpp
auto verify_cluster = (algo_ == +MetricAlgo::brute) ?
                                 &BruteVerifyCluster<std::byte const*> :
                                 &ApproxVerifyCluster<std::byte const*>;
/* Тут захватываем verify_cluster в лямбду и вызываем с нужными параметрами */
```
То же самое и в `case Metric::cosine`, поэтому вычисление `verify_cluster` можно вынести вообще до свитча.

2022-10-09 15:49 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +                }
Вообще код с шаблонами читать очень тяжело, довольно сложно разобраться из-за этого, что происходит. Шаблоны при этом тут в основном параметризуют аргументы метода, имплементации методов вообще не используют шаблонные параметры. Не знаю пока, как можно это сделать лучше, но как минимум, наверное, стоит сделать две отдельные функции с говорящими названиями, которые внутри уже будут подставлять явный тип в шаблон, станет точно читабельнее (шаблонный параметр бывает только двух типов и больше вряд ли появится, насколько я вижу)

2022-10-09 15:49 UTC, polyntsov commented on src/algorithms/MetricVerifier.h
> +    };
Использование этой структуры в `multise` выглядит так, будто с помощью нее эмулируется `map`. В целом не очень понимаю, зачем тут нужен именно multiset, по-моему в коде ты ничего по нему не ищешь. Или я что-то не заметил?

2022-10-09 15:49 UTC, polyntsov commented on src/util/ConvexHull.h
> +    int index;
Кажется, это нигде не используется и нужно убрать. Используется `IndexedPoint` и это правильно, эту структуру я бы не менял

2022-10-09 15:49 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +void MetricVerifier::VisualizeHighlights() const {
Не стоит результаты работы алгоритма печатать прямо из алгоритма. Сейчас делается cli, там это явно будет реализовано иначе. Эту функцию можно оставить для дебага, но тогда уровень логгирования заменить на соотвествующий

2022-10-09 15:49 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
>                  auto const& type = dynamic_cast<model::StringType const&>(col.GetType());
Вообще касты это плохо. Можно хотя бы сделать метод `TypedColumnData::GetTypeAs`, который внутри будет делать каст и проверять, что все норм. А тут ты на самом деле уже сверху проверил, что тип правильный, поэтому если делать каст, то `static_cast`

2022-10-09 15:49 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
> +}
а, потому что здесь мы проверяем все кластеры, чтобы найти нарушающие точки. Думаю, эту функциональность стоит явно разделить, кажется, иногда может быть достаточно только информации о том, удерживается зависимость или нет.

2022-10-09 16:26 UTC, Aviu00 commented on src/util/ConvexHull.h
> +    int index;
Это нужно, чтобы сохранить индекс после вызова ConvexHull() и GetAntipodalPairs(), которые работают с Point, а не с IndexedPoint

2022-10-09 16:30 UTC, Aviu00 commented on src/algorithms/MetricVerifier.cpp
> +}
Вроде как всегда решили делать подсветку, поэтому там все вместе

2022-10-09 16:32 UTC, Aviu00 commented on src/algorithms/MetricVerifier.cpp
>  }
Это не относится ни к чему из ConvexHull.h

2022-10-10 17:28 UTC, polyntsov commented on src/algorithms/MetricVerifier.cpp
>  }
В ConvexHull.h определяется структура точки. Тут расстояние между точками, которые представлены в виде вектора координат, вполне себе по смыслу относится

2022-10-24 18:02 UTC, Mstrutov commented on src/algorithms/MetricVerifier.cpp
> +    it->second = std::max(it->second, dist);
Ты хочешь так одну строчку заменить или весь блок с итератором?

В первом случае станет только сложнее, а во втором .at() должен бросить исключение, если индекса нет в мапе.

Я мб что-то не понял, но кажется сейчас нормально написано, го так оставим.

2022-10-24 18:04 UTC, Mstrutov commented on src/algorithms/MetricVerifier.cpp
> +    it->second = std::max(it->second, dist);
Аа, я понял, что происходит, сейчас подумаю

2022-10-24 18:21 UTC, Mstrutov commented on src/algorithms/MetricVerifier.cpp
> +    it->second = std::max(it->second, dist);
Давай оставим как есть, потому что это по KISS, хоть и версия Михаила даже более простая, если помнить, как работает `operator[]`.

Ну и версия Михаила отличается в логике, если dist отрицательная, хотя такое не может быть по определению расстояния — но если вдруг произойдёт, будет непросто отдебажить.

2022-10-24 18:29 UTC, Aviu00 commented on src/algorithms/MetricVerifier.cpp
> +    it->second = std::max(it->second, dist);
Там немного изменилась структура подсветки, поэтому я заменил это на `try_emplace`

2022-11-25 17:10 UTC, polyntsov requested changes
Для начала стоит поправить эти три комментария. Почему-то легче вообще не стало, стало очень сложно. Объявление класса на 350 строк -- это очень плохо. Любое его изменение затронет все файлы, которые этот хедер включают. Как минимум их придется перекомпилировать, а с++ и так собирается запредельно долго. Ну и просто будучи пользователем этого класса не хочется разбираться в 300ках строчках кода, чтобы понять, как им пользоваться, это надо как-то починить. Все еще очень много шаблонных функций, я пока не смотрел подробно (посмотрю, как исправятся эти три комментария, ибо `bind` там слишком много где встречается и этот код всё равно перепишется), но неужели без них действительно никак?

2022-11-25 17:10 UTC, polyntsov commented on src/algorithms/metric_verifier.cpp
> +                std::bind(&MetricVerifier::CalculateIndexedPoints, this, _1),
`std::bind` целиком и полностью заменяется лямбдами, всегда стоит использовать их

2022-11-25 17:10 UTC, polyntsov commented on src/algorithms/metric_verifier.h
> +    }
Все вот эти маленькие функции хелперы нужно перенести в cpp и сделать их локальными для cpp (или через static, или лучше через анонимный неймспейс)

2022-11-25 17:10 UTC, polyntsov commented on src/algorithms/metric_verifier.h
> +    }
Всё вот это должно быть в cpp

2022-12-02 20:30 UTC, polyntsov approved these changes

2022-12-02 20:50 UTC, merged