Statistics
Mstrutov/Desbordante pull request #120
Opened 2022-09-11 23:33 UTC by Firsov62121

Add CsvStats, Statistic, ColumnStats classes for using base statistics in Desbordante.

2022-09-26 17:38 UTC, Firsov62121 commented
Можно закрыть PR Никиты Талалая, т.к. это его продолжение.

2022-10-09 21:52 UTC, polyntsov requested changes
Нужно прогнать все изменения через clang-format. И кроме тех комментариев, что я оставил, нужно исправить все неисправленные из #109, а их много. После этого еще раз посмотрю `СsvStats.h`

2022-10-09 21:52 UTC, polyntsov commented on src/statistics/CsvStats.h
> +    unsigned long long Execute();
`Execute()` не должен быть приватным.

2022-10-09 21:52 UTC, polyntsov commented on src/statistics/Statistic.cpp
> +}
Это должно быть деструктором

2022-10-09 21:52 UTC, polyntsov commented on src/statistics/Statistic.cpp
> +}
Это уже есть в `src/model/types/CreateType.cpp`, нужно использовать функцию оттуда (этот код и так ужасно выглядит, дублировать его в двух местах совсем плохо)

2022-10-09 21:52 UTC, polyntsov commented on src/statistics/Statistic.cpp
> +}
не понимаю зачем этот метод нужен

2022-10-09 21:52 UTC, polyntsov commented on src/statistics/Statistic.h
> +    model::Type* type;
`type` стоит сделать `std::unique_ptr`.

2022-10-09 21:52 UTC, polyntsov commented on src/statistics/Statistic.cpp
> +}
Этого метода не должно быть, только деструктор у `Statistic`, который делает всё нужное

2022-10-09 21:52 UTC, polyntsov commented on tests/TestCsvStats.cpp
> +    mo::Type const& type = static_cast<mo::Type const&>(*pair.getType());
этот static_cast ничего не делает

2022-10-09 21:52 UTC, polyntsov commented on tests/TestCsvStats.cpp
> +    mo::INumericType const& type = static_cast<mo::INumericType const&>(*pair.getType());
а зачем тут этот каст? Никакие методы этого интерфейса не используются же

2022-10-09 21:52 UTC, polyntsov commented on tests/TestCsvStats.cpp
> +    mo::Type const& type = static_cast<mo::Type const&>(*pair.getType());
Зачем вообще во всех этих тестах достается тип, если от него везде вызывается ровно один *статический* метод, для вызова которого объект не нужен.

2022-10-09 21:52 UTC, polyntsov commented on tests/inputData/TestCsvStats.csv
> +NULL,,1.07,1,1
стоит добавить колонок со смешанными значениями, чтобы они тестировались в том числе

2022-10-09 21:56 UTC, polyntsov commented
И @DaniilGoncharov исправь, пожалуйста, последний коммит-месседж на что-то более конкретное ([вот тут](https://github.com/Mstrutov/Desbordante/wiki/Development) описано, как коммиты должны быть оформлены)

2022-10-18 21:32 UTC, Firsov62121 commented on src/model/types/StringType.h
> +        //Destruct(value);
В buf в `TypedColumnData.cpp` строка 127 выделен кусок памяти под них несколько данных, этот деструктор пытается очистить память в середине выделенного участка.

2022-10-20 20:59 UTC, polyntsov requested changes
В имплементациях функций не пиши строчки подряд одна за одной, а делай логическое разбиение кода на части пустыми строками, а-то читать тяжело

2022-10-20 20:59 UTC, polyntsov commented on src/algorithms/statistics/CsvStats.cpp
> +        }
Думаю, стоит этот кусок, который считает количество уникальных значений в отсортирвоанном векторе, вынести в отдельную функцию, использовать её и тут, и в distinct

2022-10-20 20:59 UTC, polyntsov commented on src/algorithms/statistics/CsvStats.cpp
> +        std::nth_element(data.begin(), data.begin() + quantile, data.end(), type.GetComparator());
Хочется скобочек вокруг

2022-10-20 20:59 UTC, polyntsov commented on src/algorithms/statistics/CsvStats.h
> +    std::vector<const std::byte*> DeleteNullAndEmpties(unsigned index);
@chernishev как предполагается использовать эту функцию? То есть, что отображать на фронте? Отдельно отображать каждую колонку без нуллов и пустых значений? Если вместе, то оно съедет же

2022-10-20 20:59 UTC, polyntsov commented on src/algorithms/statistics/CsvStats.cpp
> +Statistic CsvStats::GetSTD(unsigned index) {
Думаю, метод надо всё же переименовать и комментарий о том, что это corrected deviation должен быть в определении класса в хедере, а не тут

2022-10-20 20:59 UTC, polyntsov commented on src/algorithms/statistics/CsvStats.cpp
> +Statistic CsvStats::STDAndCentralMoment(unsigned index, int number, bool is_for_STD) {
По-моему довольно странно делать функцию "std and central moment", где параметр `is_for_STD` одновременно определяет и корректировку (-1 из количества), и извлекается ли квадратный корень или нет. В этой функции реализована логика подсчета центрального момента с номером number, среднеквадратическое отклонение -- это корень из второго центрального момента, думаю, это так и должно быть разделено. А булевый параметр должен отвечать только за корректировку и соответственно быть назван "bessel_correction"
То есть извлечение квадратного корня из результата этой функции стоит перенести в `GetCorrectedSTD`

2022-10-20 20:59 UTC, polyntsov commented on src/algorithms/statistics/CsvStats.cpp
> +        all_stats[index].isCategorical = isCategorical(index, all_stats[index].count - 1);
почему параметр количества именно такой?

2022-10-20 20:59 UTC, polyntsov commented on src/algorithms/statistics/CsvStats.h
> +    std::vector<ColumnStats>& GetAllStats();
А зачем нужна возможность получить доступ к посчитанным статистикам и изменить их извне? выглядит странно

2022-10-20 20:59 UTC, polyntsov commented on tests/TestCsvStats.cpp
> +                         ::testing::Values(CsvStatsParams("TestCsvStats.csv", ',', false)));
Все эти тесты должны быть обычными, а не параметризованными, потому что в них захардкожен ответ для конкретного датасета, смысла в передачи датасета как параметра в таком случае нет (ну либо надо передавать еще и ожидаемые значения)

2022-10-20 20:59 UTC, polyntsov commented on tests/TestCsvStats.cpp
> +    auto result1 = quantile_0_25.GetType()->GetValue<mo::Int>(quantile_0_25.GetData());
Почему не `Type::GetValue`? Это ведь короче..

2022-10-20 20:59 UTC, polyntsov commented on src/algorithms/statistics/Statistic.cpp
> +}
Вообще не нравится эта логика. Думаю, будет лучше, если конструктор сразу будет принимать `std::unique_ptr<Type>` и всегда новый объект `data` (внутри кода статистик, если нужно, будет вызываться `type->Clone()` вместо параметра `clone_data`.
И я все еще решительно не понимаю, зачем здесь нужен `const_cast`
`data` при этом не должна быть обычным `unique_ptr`, потому что удаление дефолтным deleter'ом `unique_ptr` может быть неверным, поэтому оно делается отдельно через функцию `Free` у `Type`

2022-10-20 20:59 UTC, polyntsov commented on src/model/types/CreateType.h
> +std::unique_ptr<Type> CreateTypeClone(const Type& type);
Эта функция не должна быть реализована здесь через switch-case, это нужно делать через виртуальную функцию `Type::CloneType`

2022-10-20 20:59 UTC, polyntsov commented on src/algorithms/statistics/Statistic.h
> +    Statistic(const Statistic&);
Зачем этому классу конструктор копирования и копирующий оператор присваивания? Это где-то используется, а я не увидел?

2022-10-21 16:25 UTC, Firsov62121 commented on src/algorithms/statistics/Statistic.h
> +    Statistic(const Statistic&);
Да, в `CsvStats::Execute`, в `CsvStats::STDAndCentralMoment` для avg.

2022-10-21 16:50 UTC, Firsov62121 commented on src/algorithms/statistics/Statistic.h
> +    bool isDistinctCorrect = false;
Для несравнимых типов distinct не определён.

2022-10-21 16:52 UTC, Firsov62121 commented on src/algorithms/statistics/Statistic.h
> +#include "../../model/types/Types.h"
vs code находил не тот заголовочник, из другой версии Desbordante в соседней папке.

2022-10-21 16:56 UTC, polyntsov commented on src/algorithms/statistics/Statistic.h
> +#include "../../model/types/Types.h"
Это, кажется, проблема настройки vscode, которая не должна решаться изменением путей в коде

2022-10-21 16:58 UTC, polyntsov commented on src/algorithms/statistics/Statistic.h
> +    Statistic(const Statistic&);
в каких строчках?

2022-10-21 17:01 UTC, Firsov62121 commented on src/algorithms/statistics/Statistic.h
> +    Statistic(const Statistic&);
299, 301, 306-308, 116

2022-10-21 17:08 UTC, polyntsov commented on src/algorithms/statistics/Statistic.h
> +    Statistic(const Statistic&);
Там везде справа от присваивания стоит rvalue, соответственно вызывается там перемещающий оператор присваивания, а не копирующий

2022-10-21 18:40 UTC, Firsov62121 commented on src/algorithms/statistics/CsvStats.cpp
> +    }
Компаратор должен быть std::less<const std::byte*>. Лямбда функцию туда не подставишь, нужен отдельный тип, у которого будет перегружен operator()(const std::byte*, const std::byte*). Городить целый тип для этого метода не захотелось.

2022-10-21 18:45 UTC, Firsov62121 commented on src/algorithms/statistics/CsvStats.cpp
> +    }
В теории можно написать свой компаратор со своим оператором `bool operator()(const std::byte*, const std::byte*)`. Но это слишком много для одного места.

2022-10-21 18:54 UTC, Firsov62121 commented on src/algorithms/statistics/Statistic.cpp
> +}
Часто перед вызовом данные нужно было копировать, т.к. результаты многих статистик хранятся в общем буфере. Одним параметром здесь я сокращаю кучу вызовов type.Clone снаружи.

2022-10-21 20:06 UTC, Firsov62121 commented on src/algorithms/statistics/CsvStats.cpp
> +        all_stats[index].isCategorical = isCategorical(index, all_stats[index].count - 1);
Категоричный - значит есть повторения каких-то значений, т.е. distinct <= число значений в колонке - 1

2022-10-21 23:34 UTC, Firsov62121 commented on src/model/types/StringType.h
> +        //Destruct(value);
Несколько часов смотрел логи, ничего не помогло - пишет, что мы пытаемся очистить кусок памяти внутри большего выделенного участка памяти. Без этого деструктора никаких утечек памяти нет.

2022-10-24 17:51 UTC, chernishev commented on src/algorithms/statistics/CsvStats.cpp
> +int CsvStats::Distinct(unsigned index) {
Игнорируем, у нас есть отдельная штука которая считает количество NULL.

2022-10-24 18:50 UTC, polyntsov requested changes

2022-10-24 18:50 UTC, polyntsov commented on src/algorithms/statistics/statistic.cpp
> +}
Экономия всё же не очень большая от отсутствия нескольких копирований этих значений, но наверное можно оставить. Только тогда `clone_data` не должно быть параметром по умолчанию, чтобы пользователь этой функции явно видел, что происходит с владением `data`

2022-10-24 18:50 UTC, polyntsov commented on src/algorithms/statistics/statistic.cpp
> +std::unordered_map<std::string, std::string> ColumnStats::ToKeyValueStringPairs() const {
`ToKeyValueMap` уже

2022-10-24 18:50 UTC, polyntsov commented on src/algorithms/statistics/statistic.cpp
> +        res << stat.first << " = " << stat.second << '\n';
structured bindings

2022-10-24 18:50 UTC, polyntsov commented on src/model/types/DoubleType.h
> +    }
Выглядит плохо, это должно быть сделано через виртуальные функции как-нибудь. Сделать виртуальный `ConvertTo` и использовать примерно так (`MakeFrom` по идее тогда может быть даже не виртуальным и реализован в Type):
```cpp
auto value = Allocate();
type.ConvertTo(*this, data, value);
```
`ConvertTo` будет проверять кастится ли один тип к другому (не свитч-кейсом, через опять же виртуальную функцию `IsConvertible`) и если кастится, то делать приведение

2022-10-24 18:50 UTC, polyntsov commented on src/model/types/DoubleType.h
> +    }
Думаю, это нужно делать отдельным пулреквестом, а-то тут уже много получается

2022-10-26 20:16 UTC, Firsov62121 commented on src/model/types/DoubleType.h
> +    }
Согласен.

2022-10-30 14:45 UTC, polyntsov requested changes
`TestCsvStats.csv` надо переименовать в `test_csv_stats.csv`

2022-10-30 14:45 UTC, polyntsov commented on src/algorithms/statistics/csv_stats.cpp
> +        }
а, окей, в прошлый раз я этого не заметил, но проблема в том, что с помощью типа колонки не получится нормально переводить null и пустые значения в строку. Решение простое: добавить в `TypedColumnData` метод `GetValueAsString(unsigned index)`, который внутри сделает проверку на null или empty и вызовет у нужного типа `ToString`. Если так не сделатЬ, так такой ужас придется писать во всем коде, которму нужна эта функциональность

2022-10-30 14:45 UTC, polyntsov commented on src/model/transactional_data.cpp
> +        size_t const tid = std::stoi(row[tid_col_index]);
`std::stoi` возвращает `int`, тогда уж `std::stoull`

2022-10-30 14:45 UTC, polyntsov commented on src/model/types/mixed_type.h
> +            return CompareResult::kGreater;
Зачем? Сравнивать значения по их типу очень странно: `5 < "five"`? `5 < 3.14`?

2022-10-30 14:45 UTC, polyntsov commented on src/model/types/mixed_type.h
> +        ValueFromStr(new_value, ValueToString(value), type.get());
Да, это опять будет работать неправильно для строковых типов, молодец, что нашел. Только оставь тут комментарий о том, что через строки это делать не совсем правильно. Потому что для произвольных значений  всех типов кроме строчных придется создавать по две строки и делать приведения. Но лучше способ с текущим кодом вряд ли существует (нужно сделать виртуальный `Clone()`, который не выделяет память, а пишет в переданную ему и можно будет сделать нормально).

2022-10-30 14:45 UTC, polyntsov commented on src/model/types/type.h
> +    }
`Mixed` тоже скорее не `ordered`

2022-10-30 14:45 UTC, polyntsov commented on tests/test_csv_stats.cpp
> +#endif
а почему всё же этот код закомменчен? Норм тест же, как минимум поверяет, что оно не падает в нескольких тредах. `std::cout` только на `LOG(INFO)` заменить

2022-10-30 17:32 UTC, Firsov62121 commented on src/model/types/mixed_type.h
> +            return CompareResult::kGreater;
Георгий предложил сравнивать их как строки.

2022-10-30 17:44 UTC, Firsov62121 commented on tests/test_csv_stats.cpp
> +#endif
Очень долгий в debug режиме.

2022-10-30 18:01 UTC, polyntsov commented on tests/test_csv_stats.cpp
> +#endif
хм, окей, если в релиз режиме лучше, то можно обернуть в `#ifdef DNDEBUG`. Если и в релиз моде не очень, то оставим так

2022-10-30 18:01 UTC, polyntsov commented on src/model/types/mixed_type.h
> +            return CompareResult::kGreater;
Так тут они не как строки сравниваются, ну и в целом не очень понимаю, что это значит. @chernishev

2022-10-30 18:21 UTC, Firsov62121 commented on src/model/types/mixed_type.h
> +            return CompareResult::kGreater;
Тут да, я в новой версии на сравнение строк переделаю.

2022-10-30 18:26 UTC, chernishev commented on src/model/types/mixed_type.h
> +            return CompareResult::kGreater;
Насколько я понял это по следам нашей сегодняшней дискуссии. Обсуждали как делать distinct для колонки смешанного типа. Изначально было так: внутри каждого типа считаем свой, потом суммируем. Я предложил привести к строке все и на ней сделать. Кажется что так смысла будет больше. Но это касалось конкретно вычисления distinct в таком случае, а не всегда.

2022-10-30 18:49 UTC, polyntsov commented on src/model/types/mixed_type.h
> +            return CompareResult::kGreater;
Думаю, просто считать отдельно внутри разных типов, а потом суммировать самый правильный способ. Но точно неправильно определять сравнение для значений разных типов через их `type_id`

2022-10-31 16:23 UTC, polyntsov requested changes
Имена коммитов все ещё не исправлены. Кроме того там кажется не хватает пустой строки между commit message и commit body, потому что локально оно выглядит вот так:
![image](https://user-images.githubusercontent.com/71596237/199058025-7c8041cd-d20d-4b4d-8639-b97b1dfa001b.png)

2022-10-31 16:23 UTC, polyntsov commented on src/algorithms/statistics/csv_stats.cpp
> +size_t CsvStats::MixedDistinct_(size_t index) const {
у названий функций в конце не должно быть нижних подчеркиваний

2022-10-31 16:23 UTC, polyntsov commented on src/algorithms/statistics/csv_stats.cpp
> +        mo::TypeId::_size(), std::vector<const std::byte*>(0));
конструктор от одного `size_type` аргумента и так использует конструкторы по умолчанию (`std::vector<const std::byte*>(0)` эквивалентно вызову конструктора по умолчанию). Поэтому просто:
`std::vector<std::vector<const std::byte*>> values_by_type_id(mo::TypeId::_size());`

2022-10-31 16:23 UTC, polyntsov commented on src/algorithms/statistics/csv_stats.cpp
> +        return all_stats_[index].distinct;
Теперь кажется мы считаем `distinct` от любого типа колонки, нет?  Мы ведь решили не учитывать NULL'ы и пустые значения, соответственно для колонок только из нуллов и пустых значений distinct = 0 --  ожидаемое значение. Тогда необходимость в `is_distinct_correct` отпадает.

2022-10-31 18:09 UTC, Firsov62121 commented on src/algorithms/statistics/csv_stats.cpp
> +        return all_stats_[index].distinct;
Есть ещё null и undefined колонки.

2022-10-31 18:34 UTC, polyntsov commented on src/algorithms/statistics/csv_stats.cpp
> +        return all_stats_[index].distinct;
так этот как раз колонка только из нуллов и пустых значений, 0 вполне подходит кажется

2022-10-31 18:54 UTC, Firsov62121 commented on src/algorithms/statistics/csv_stats.cpp
> +        return all_stats_[index].distinct;
Ок

2022-10-31 20:26 UTC, polyntsov requested changes

2022-10-31 20:26 UTC, polyntsov commented on src/model/transactional_data.cpp
> ->>>>>>> Refactor statistics and types:
Интересный коммит. Я на него нажал, потому что плохое ни о чем не говорящее название, а тут такое. Если этот коммит удаляет эти строки, значит где-то есть коммит, который добавляет эти изменения (:
Такого быть не должно, не нужно коммитить маркеры конфликта, а если они случайно закоммитились, то править это надо не новым коммитом их удаляющим, а исправлять неправильный коммит через `--amend`. В идеале проект должен собираться и проходить тесты на любом коммите, к этому стоит очень сильно стремиться.

2022-10-31 20:26 UTC, polyntsov commented on src/algorithms/statistics/csv_stats.cpp
> +    if (!mo::Type::IsOrdered(col.GetTypeId())) return {};
так этот `if` тогда не нужен

2022-11-01 09:43 UTC, polyntsov approved these changes

2022-11-01 09:43 UTC, merged