Dataset stream interface
Mstrutov/Desbordante pull request #127
Opened 2022-10-15 16:48 UTC by BUYT-1

Part of the way towards implementing Python bindings. Make primitives use an abstract interface to read data instead of storing a (specific) parser.

2022-10-17 17:34 UTC, polyntsov requested changes
Основное -- `shared_ptr` точно не везде должен передаваться по значению, а где-то должен быть `unique_ptr`

2022-10-17 17:34 UTC, polyntsov commented on src/model/IDatasetStream.h
> +    [[nodiscard]] virtual int GetNumberOfColumns() const = 0;
Думаю, можно тут заодно int на size_t заменить

2022-10-17 17:34 UTC, polyntsov commented on src/algorithms/Primitive.h
> +    std::shared_ptr<model::IDatasetStream> input_generator_;
`unique_ptr`?
А еще нужно явно проверить все места, где ты заменил ссылки на `shared_ptr`.  `shared_ptr` описывает владение объектом, функции типа "CreateFrom" явно не должны владеть переданным им data_stream, там стоит оставить ссылки

2022-10-21 15:59 UTC, BUYT-1 commented
Ок, жду мёрж

2022-10-26 18:06 UTC, polyntsov approved these changes

2022-10-29 09:50 UTC, BUYT-1 commented
Чуть не забыл про тексты ошибок, их же тоже надо поменять.

2022-10-30 14:43 UTC, polyntsov requested changes

2022-10-30 14:43 UTC, polyntsov commented on src/algorithms/primitive.h
>  #include "csv_parser.h"
этот хедер тогда не нужен

2022-10-30 14:57 UTC, polyntsov commented on src/algorithms/primitive.h
>  #include "csv_parser.h"
я не прав, нужен

2022-10-30 14:57 UTC, polyntsov approved these changes

2022-10-30 15:27 UTC, merged