Rename to snake_case
Mstrutov/Desbordante pull request #128
Opened 2022-10-18 03:08 UTC by Mstrutov

Previously there was no strict convention for directory naming and the file names were formatted in PascalCase.

The decision was to stick to google style guide and use snake_case for both source code files and directories.

2022-10-18 03:17 UTC, Mstrutov commented
I've used a slightly modified renaming [tool](https://github.com/Gadiguibou/stdrename) with a bit of scripting and linux utilities, followed by manual directory renaming and tool failures fixes. The script and modified tool can be found [here](https://github.com/Mstrutov/desbordante-rename) --- beware that it is faulty and must not be used blindly.

2022-10-20 21:17 UTC, polyntsov requested changes
Думаю, imetrizable и qgram должно быть слитно, насчет остальных не уверен

2022-10-20 21:17 UTC, polyntsov commented on src/algorithms/algorithms.h
> +#include "algorithms/fast_fds.h"
Ощущение, что fastfds и tanex должны слитно писаться, нет?

2022-10-20 21:17 UTC, polyntsov commented on src/model/types/type.h
> +#include "built_in.h"
слитно?

2022-10-20 21:17 UTC, polyntsov commented on src/model/types/numeric_type.h
> +#include "i_metrizable_type.h"
i и metrizable слитно?

2022-10-20 21:17 UTC, polyntsov commented on src/util/q_gram_vector.cpp
> +#include "q_gram_vector.h"
q и gram слитно?

2022-10-24 05:22 UTC, Mstrutov commented on src/algorithms/algorithms.h
> +#include "algorithms/fast_fds.h"
TaneX --- согласен
FastFDs --- думал, что можно смотреть на `fast` как на отдельное слово, но, пожалуй, можно всё слитно написать: всё-таки название алгоритма, ну и `depminer` уже слитно написан

2022-10-24 05:23 UTC, Mstrutov commented on src/algorithms/algorithms.h
> +#include "algorithms/fast_fds.h"
Вообще, заменил tane_x на tane

2022-10-24 15:08 UTC, polyntsov commented
Появился конфликт, по всей видимости с #130

2022-10-24 21:19 UTC, polyntsov approved these changes

2022-10-24 21:19 UTC, merged