Add frontend visualization report
Mstrutov/Desbordante pull request #137
Opened 2022-10-25 16:43 UTC by iliya-b

2022-10-30 15:51 UTC, chernishev requested changes
Непонятно почему такое имя, за какой семестр какого года эта работа сдается?

2022-10-31 13:59 UTC, iliya-b commented
> Непонятно почему такое имя, за какой семестр какого года эта работа сдается?

У меня практика была в 2020 году, 1 семестре. Потом я был в академе.

2022-10-31 14:36 UTC, chernishev commented
Я вот подумал и кажется что очевидного ответа на вопрос "какие даты ставить" нет. С одной стороны, вся инфа о том, когда работа сдавалась есть в дате коммита. При этом, за какой семестр это отчет -- на самом деле не очень важно для проекта. Единственный юзкейс дат в названиях -- это быстро искать когда оно делалось / было сдано. Потому прошу Вас переделать название.

2022-10-31 16:31 UTC, iliya-b commented
переименовал все два отчета

2022-10-31 18:02 UTC, chernishev commented
Пойдет.

2022-10-31 18:02 UTC, chernishev approved these changes

2022-11-01 09:43 UTC, merged