Feature/18 implement hyfd
Mstrutov/Desbordante pull request #139
Opened 2022-11-03 06:58 UTC by Mstrutov

HyFD is a hybrid functional dependency discovery algorithm, employing both row-efficient
sample-based agree set generation and column-efficient lattice traversal.

The algorithm has three major components: Sampler, Inductor and Validator --- the former two
representing row-efficient step. Sampler acquires a collection of agree sets using a special
deterministic sampling approach, then Inductor uses this data to enrich an FD prefix tree. This
concludes the first step and the execution moves to Validator, which performs breadth-first
bottom-up traverse of the FDTree, validating the FDs and specializing incorrect candidates.

It is difficult to come up with a criteria or an algorithm for choosing the optimal point to move
from the first step to the second, therefore HyFD uses a notion of efficiency to track how
efficient current step is performing and switches to the other step in case it falls beneath a
configured threshold. Each step's results are useful for the other step: Sampler-Inductor
specialize the prefix tree, which reduces the number or costly PLI checks Validator has to
perform, while Validator yields a collection of row pairs, which invalidated a candidate and can
be used by Sampler to obtain a new agree set.

Thorsten Papenbrock and Felix Naumann. 2016. A Hybrid Approach to Functional Dependency
Discovery. In Proceedings of the 2016 International Conference on Management of Data (SIGMOD
'16). Association for Computing Machinery, New York, NY, USA, 821–833.
https://doi.org/10.1145/2882903.2915203

2022-11-03 07:01 UTC, Mstrutov commented
Closes #18, leaving a todo list:
- parallelize validator using `ParallelFor`
- implement the Guardian component 
- investigate performance issues, optimize to beat Metanome 
- consider implementing a bitset custom iterator to simplify bitset loops, which are used very frequently

2022-11-07 13:54 UTC, polyntsov requested changes

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/elements/raw_fd.h
> +struct RawFD {
Выглядит вообще довольно полезно для тестирования, там часто хочется задавать ожидаемые намайненные ФЗ, а делать этот через существующий класс `FD` очень неудобно (ему нужны `Vertical`, которому нужен `RelationalSchema`). Я для этого делал костыльный `FDByIndices` (в `test_typo_miner.cpp`) и даже `Vertical::GetColumnIndicesAsVector`. Гораздо лучше будет использовать такой класс, особенно если сделать ему конструктор от индексов (в тестах по идее удобнее всего задавать список колонок через `initilizer_list<unsgined>`). Думаю, это `RawFD` стоит переместить куда-нибудь в `src/model` и у `FD` сделать метод `ToRawFD`.

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/elements/raw_fd.h
> +struct RawFD {
Ну и надо бы просмотреть существующий код, ощущение, возможно кто-то делал такой же класс у себя в алгоритме

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.h
> +    Validator(std::shared_ptr<fd_tree::FDTree> fds, PLIs plis, RowsPtr compressed_records) noexcept
С точки зрения интерфейса и семантики кажется, что нечто с названием `Validator` и одним публичным методом `Validate` не должно владеть тем, что валидирует, и стоит использовать raw pointers 
И `plis` тоже зря принимается по значению, думаю, можно принимать сырой указатель на него (в `hyfd.cpp` его забыли переместить и по итогу он просто так копируется)

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/inductor.h
> +    void UpdateFdTree(NonFDList non_fds);
Аргумент кажется не меняется, поэтому `NonFDList const&`

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/structures/fd_tree.h
> +    std::shared_ptr<FDTreeVertex> GetRoot() noexcept {
Сам метод должен быть `const` и возвращаемое значение `const &`

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/structures/fd_tree.h
> +    bool FindFdOrGeneral(boost::dynamic_bitset<> const& lhs, size_t rhs) {
Должен быть `const`

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/structures/fd_tree_vertex.h
> +    void GetLevelRecursive(unsigned target_level, unsigned cur_level, boost::dynamic_bitset<> lhs,
Должен быть `const`

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/structures/fd_tree.h
> +    std::vector<LhsPair> GetLevel(unsigned target_level);
Должен быть `const`

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +Validator::FDValidations Validator::ProcessHigherLevel(LhsPair const& lhsPair) {
`lhs_pair`

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +                  << std::to_string(num_valid_fds) + " FDs";
думаю, стоит вынести в отдельный метод

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +}
Примерно то же самое делается в `RelationalSchema::IndicesToBitset`, их бы объединить как-то

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +            sub_cluster.push_back(lhs_cluster_id);
Тяжело читать, думаю просто определение `lhs_cluster_id` стоит вынести до if'a, скоуп тут все равно очень маленький

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +BuildStructures(boost::dynamic_bitset<> const& lhs, boost::dynamic_bitset<> const& rhs,
Думаю, это стоит разбить на три отдельные функции (чтобы не возвращать `tuple` ни о чем не говорящих типов, имена функций будут давать хоть какую-то информацию). Одна для `valid_rhss`, одна для `rhs_columns_ids` и `rhs_ranks`, одна для `lhs_column_ids`

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +        for (int row : cluster) {
`PLI::Cluster::value_type`, `int` кажется не очень удачным типом для обозначения индекса строки, может когда-нибудь исправим, поэтому не стоит добавлять зависимости от него

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +        };
Не должны быть `static`

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +        std::unordered_map<std::vector<size_t>, std::pair<std::vector<size_t>, size_t>,
Думаю, для вектора и пары стоит сделать using'и локальнрые для этой функции (или нет, зависит от их значения). Как и для всего map'a, а то грустно, когда объявление переменной в 100 символов не помещается

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +    for (auto const& cluster : plis[firstAttr]->GetIndex()) {
Очень большой цикл, его бы разбить на функции или хотя бы просто тело вынести в отдельную

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +                        value != rhs_record.first[rhs_ranks[rhs_column]]) {
Думаю, объявления переменных тоже стоит вынести до if'a просто чтобы упростить код (тут и условие сложное)

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +            boost::dynamic_bitset<> childLhs = lhs;
`child_lhs`

2022-11-07 13:54 UTC, polyntsov commented on src/algorithms/hyfd/validator.cpp
> +
Стоит добавить хедеры стандартной библиотеки, имена из которых тут используются (`<unordered_set>`, например), а не рассчитывать на транзитивное включение, а-то у кого-нибудь на немейнстримном дистрибутиве обязательно не соберется

2022-11-07 17:12 UTC, Mstrutov commented on src/algorithms/hyfd/hyfd.h
> +        : PliBasedFDAlgorithm(std::move(relation), config, {"FD mining"}) {}
Если прогресс бар не реализован (одна фаза и нет прогресса от 0 до 100), то нужно оставить пустым --- это знак серверу, что он не реализован, а таком случае на сервере есть своя реализация

2022-11-08 06:41 UTC, Mstrutov commented on src/algorithms/hyfd/inductor.h
> +    void UpdateFdTree(NonFDList non_fds);
Задумка была в том, что в `hyfd.cpp` этот объект мувается в `Inductor`, как бы передаётся от `Sampler`'а к `Inductor`'у, нигде больше не используясь. Но, наверное, с `const&` понятнее и чуть эффективнее, хотя объект будет позже уничтожаться.

2022-11-09 04:23 UTC, Mstrutov commented on src/algorithms/hyfd/sampler.cpp
> +            cluster_comparator.IncrementActiveKey();
Разделил логику сравнения и изменения опорных объектов для сравнения, вынес в два класса, посмотри, стало ли лучше.

2022-11-09 04:36 UTC, Mstrutov commented on src/algorithms/hyfd/structures/fd_tree.h
> +    std::shared_ptr<FDTreeVertex> GetRoot() noexcept {
Такой `GetRoot` нужен в `Validator::Validate()`, тк он может изменять ноды дерева.

Переделал константный метод, переименовал неконстантный.

2022-11-09 04:39 UTC, Mstrutov commented on src/algorithms/hyfd/structures/fd_tree.h
> +    std::vector<LhsPair> GetLevel(unsigned target_level);
Наружу выдаются неконстантные указатели на вершины, по-моему, в таких случаях не прописывают `const`, так как объект может поменять состояние после вызова этого метода.

2022-11-09 04:40 UTC, Mstrutov commented on src/algorithms/hyfd/structures/fd_tree_vertex.h
> +    void GetLevelRecursive(unsigned target_level, unsigned cur_level, boost::dynamic_bitset<> lhs,
То же самое про неконстантные указатели на ноды.

2022-11-09 06:23 UTC, Mstrutov commented on src/algorithms/hyfd/sampler.cpp
> +Sampler::~Sampler() = default;
Деструктор пришлось перенести в `.cpp` из-за forward-declared `Efficiency` в хедере: без этого генерируемый деструктор падал при инстанциировании деструктора `std::priority_queue<Efficiency>`.

Удалил констуктор и оператор копирования, чтобы избежать описанных проблем.

2022-11-13 12:32 UTC, polyntsov commented on src/algorithms/hyfd/sampler.cpp
> +Sampler::~Sampler() = default;
Тогда стоит и явно объявить/удалить перемещающие операции

2022-11-13 12:34 UTC, polyntsov commented on src/algorithms/hyfd/sampler.cpp
> +            cluster_comparator.IncrementActiveKey();
думаю, да

2022-11-13 12:36 UTC, polyntsov commented on src/algorithms/hyfd/inductor.h
> +    void UpdateFdTree(NonFDList non_fds);
Тогда, наверное, тут должна быть rvalue ссылка, а-то принимая по значению задумка вообще не ясна из интефрейса

2022-11-13 12:38 UTC, polyntsov commented on src/algorithms/hyfd/structures/fd_tree.h
> +    std::vector<LhsPair> GetLevel(unsigned target_level);
Согласен, забыл, что LhsPair хранит внутри указатель

2022-11-13 12:48 UTC, polyntsov commented on src/algorithms/hyfd/structures/fd_tree.h
> +    std::shared_ptr<FDTreeVertex> GetRoot() noexcept {
Имел в виду, что возвращаемое значение стоит сделать `std::shared_ptr<> const&`. С точки зрения пользователя функции не изменится совсем ничего, но если он будет писать `GetRootPtr()->method()` не произойдет лишней копии поинтера. Но возмно это overoptimization + overthinking, усложняющий чтение интерфейса, не уверен

2022-11-14 03:46 UTC, Mstrutov commented on src/algorithms/hyfd/hyfd.cpp
> +    LOG(INFO) << "Executing";
Наверное, это всё-таки `TRACE`, переделал.

2022-11-14 03:49 UTC, Mstrutov commented on src/algorithms/hyfd/sampler.cpp
> +Sampler::~Sampler() = default;
Kk, думал, по [rule of three ](https://en.cppreference.com/w/cpp/language/rule_of_three) можно забить на мув методы, но видимо лучше явно со всеми разобраться: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-five

2022-11-14 03:59 UTC, Mstrutov commented on src/algorithms/hyfd/structures/fd_tree.h
> +    std::shared_ptr<FDTreeVertex> GetRoot() noexcept {
Ага, понял. Думаю, оставлю то, как переделал с изначальным пониманием: есть метод, который явно выдаёт указатель для владения нодой, есть метод, который даёт ссылку на константную ноду, если надо только подёргать её константные методы.

2022-11-14 04:53 UTC, Mstrutov commented on src/algorithms/hyfd/structures/fd_tree_vertex.h
> +    std::shared_ptr<const FDTreeVertex> GetChild(size_t pos) const {
Сделал в том же ключе, что и в `GetRoot()`

2022-11-14 05:17 UTC, Mstrutov commented on src/algorithms/hyfd/elements/raw_fd.h
> +struct RawFD {
В остальном коде не нашёл чего-то похожего, перенёс в `src/model`, добавил `ToRawFD`.

Делать конструктор под тесты и рефакторить сами тесты надо уже в отдельном PR.

2022-11-14 05:38 UTC, Mstrutov commented on src/algorithms/hyfd/validator.h
> +    Validator(std::shared_ptr<fd_tree::FDTree> fds, PLIs plis, RowsPtr compressed_records) noexcept
Тут валидатор валидитрует не в общепринятом смысле, когда считывается структура подаваемого объекта и проверяется, что она удовлетворяет всем правилам, а в смысле HyFD: переименовал его метод, чтобы отразить, что именно он делает.

`plis` теперь шерится так же, как и остальные структуры из препроцессинга.

2022-11-14 05:54 UTC, Mstrutov commented on src/algorithms/hyfd/validator.cpp
> +}
Вынес в `bitset_utils`

2022-11-14 12:54 UTC, polyntsov commented on src/algorithms/hyfd/efficiency.h
> +class Sampler::Efficiency {
Интересно, а как оно собирается? Перед включением этого хедера всегда (буквально выше) включается хедер, где объявлен `Sampler`? Не очень какая-то зависимость получается

2022-11-14 12:55 UTC, polyntsov commented on src/algorithms/hyfd/hyfd.cpp
> +    size_t id = 0;
false positive, надо будет совсем убрать это правило

2022-11-21 04:32 UTC, Mstrutov commented on src/algorithms/hyfd/efficiency.h
> +class Sampler::Efficiency {
Это я задумывал как приватный класс у `Sampler`, в `Sampler` лежит forward declaration of `Efficiency`. Таким образом единственный файл, где он должен использоваться, это `sampler.cpp`, а остальные места его не надо включать.

2022-11-21 04:32 UTC, Mstrutov commented on src/algorithms/hyfd/efficiency.h
> +class Sampler::Efficiency {
То же с `FDValidations`

2022-11-21 12:25 UTC, polyntsov commented on src/algorithms/hyfd/efficiency.h
> +class Sampler::Efficiency {
Возможно, тогда стоит этот код просто целиком перенести в `sampler.cpp`?

2022-11-22 05:36 UTC, Mstrutov commented on src/algorithms/hyfd/efficiency.h
> +class Sampler::Efficiency {
Можно, но хочется по-максимуму вынести выносимое, потому что `validator.cpp`, например, довольно тяжёлый, не хочется добавлять туда что-либо.

Хотя и много хедеров, которые используются лишь в одном файле, тоже наверное не очень. Хз, по-моему, что так, что так будут свои плюсы и минусы, и бы оставил как есть.

Ну, могу сделать директории `validator`, `sampler` и переместить туда всё, им принадлежащее, чтобы как-то виузально хотя бы обозначить, что куда относится.

2022-11-25 11:52 UTC, polyntsov commented on src/algorithms/hyfd/efficiency.h
> +class Sampler::Efficiency {
хм, мне наоборот кажется, что лучше держать локально, если оно нужно только в `validator.cpp`, чем выносить в отдельный файл. Но можно в целом и в директории объеденить

2022-11-25 13:43 UTC, polyntsov approved these changes
LGTM

2022-11-25 13:43 UTC, polyntsov commented on src/algorithms/hyfd/fd_validations.h
> +    void add(FDValidations&& other) noexcept {
Может выкинуть bad_alloc

2022-11-25 13:43 UTC, polyntsov commented on src/algorithms/hyfd/sampler.cpp
> +    for (size_t i = 0; i < (*compressed_records_)[0].size(); ++i) {
Кажется, все ещё не исправлено

2022-11-26 15:38 UTC, merged