Refactor config
Mstrutov/Desbordante pull request #153
Opened 2022-11-28 12:22 UTC by BUYT-1

Implementing Python bindings the way we want sensibly is impossible with the current method of configuration. This simplifies the way primitives are configured.

2022-11-28 17:49 UTC, polyntsov commented on src/model/typed_column_data.h
> +std::vector<TypedColumnData> CreateTypedColumnData(IDatasetStream& dataset_stream,
Не хватает хедера с ним?

2022-11-29 08:29 UTC, polyntsov requested changes

2022-11-29 08:29 UTC, polyntsov commented on src/algorithms/algo_factory.h
> +            }
Использовать исключения для control flow довольно плохое решение. Лучше, например, сделать if с проверкой перед вызовом `ExtractAnyFromMap`, что опция есть в мапе

2022-11-29 08:29 UTC, polyntsov commented on src/algorithms/algo_factory.h
> +boost::any ExtractAnyFromMap(OptionMap&& options, std::string_view const& option_name) {
По логике options тут должен приниматься не по универсальной ссылке, а кк `OptionMap const &`, передача владения мапом в эту функцию выглядит довольно бесмысленно

2022-11-29 08:29 UTC, polyntsov commented on src/algorithms/algo_factory.h
> +    const std::string string_opt{option_name};
неприятно конечно, что нужно эти конвертации писать. Но кажется, что ничего не сделать, хм

2022-11-29 08:29 UTC, polyntsov commented on src/algorithms/algo_factory.h
> +void ConfigureFromMap(Primitive& primitive, OptionMap&& options) {
Тоже `OptionMap const&`

2022-11-29 08:29 UTC, polyntsov commented on src/util/true_func.cpp
> +}
Выглядит совсем странно. Думаю, стоит просто передавать nullptr там, где проверка не нужна и зависимые опции должны выставляться всегда (и соответственно перед тем как вызывать функцию с проверкой условия проверить, что она не nullptr)

2022-11-29 08:29 UTC, polyntsov commented on src/util/enum_to_available_values.h
> +
Хотя мне кажется, что эта функция не должна быть в `util`, она переводит в строку достаточно специфичного формата, не вижу особо, как оно может быть полезно где-то кроме main'a (или кода, который выводит help в консоль в общем)

2022-11-29 08:38 UTC, BUYT-1 commented on src/algorithms/metric_verifier_enums.h
> +                                 * values */
> странное форматирование

В [AlgoFactory](https://github.com/Mstrutov/Desbordante/blob/main/src/algorithms/algo_factory.h#L39) такое


> думаю, этот файл скорее должен называться `metric_verifier_algorithm_types`

Метрика -- это не тип алгоритма. Хотя, в каком-то смысле может и да. Но тогда возможна путаница с `MetricAlgo`.

2022-11-29 08:44 UTC, polyntsov commented on src/algorithms/metric_verifier_enums.h
> +                                 * values */
Да не, я просто не внимательно посмотрел, тогда конечно что-то вроде `metric_verifier_possible_metrics`

2022-11-29 08:46 UTC, polyntsov commented on src/algorithms/metric_verifier_enums.h
> +                                 * values */
Кажется, тут выровнено нормально:
![image](https://user-images.githubusercontent.com/71596237/204481642-fefeb396-715d-4005-899a-ae74a531cecd.png)

2022-11-29 08:51 UTC, polyntsov commented on src/algorithms/metric_verifier_enums.h
> +                                 * values */
Да, я если что только про комменатрий

2022-11-29 09:02 UTC, BUYT-1 commented on src/algorithms/primitive_enum.h
> +        if constexpr (std::is_convertible_v<PrimitiveType *, PrimitiveBase *>) {
std::is_base_of<A, B>::value is true even if A is a private, protected, or ambiguous base class of B. In many situations, [std::is_convertible](http://en.cppreference.com/w/cpp/types/is_convertible)<B*, A*> is the more appropriate test.

По смыслу: мы же проверяем, что unique_ptr на один конвертируется в unique_ptr на другой, но разницы особой нет. Да и ситуаций как выше у нас не бывает.

2022-11-29 09:05 UTC, BUYT-1 commented on src/algorithms/primitive.h
> +    virtual void FitInternal(model::IDatasetStream& data_stream) = 0;
Не-не-не, это оверлоадится примитивами для их обработки данных (Fit) и выполнения (Execute).

2022-11-29 09:15 UTC, BUYT-1 commented on src/algorithms/primitive.h
> +    config::OptAddFunc GetOptAvailFunc();
Нет, там внутри лямбды метод, который меняет два поля в классе

2022-11-29 09:15 UTC, BUYT-1 commented on src/algorithms/fd_algorithm.cpp
> +        Vertical const &lhs = fd.GetLhs();
А, это я неаккуратно Ctrl+Alt+L нажал

2022-11-29 09:17 UTC, BUYT-1 commented on src/algorithms/primitive.h
> +    void MakeOptionsAvailable(std::string_view parent_name,
Тогда `IOption *`, Option -- шаблон

2022-11-29 09:20 UTC, BUYT-1 commented on src/algorithms/ar_algorithm.h
> +protected:
Понял. Так проще было определить OptionType для какой-то из опций, но в отсутствие OptionType это не актуально.

2022-11-29 09:24 UTC, BUYT-1 commented on src/algorithms/options/option.h
> +    void Set(boost::optional<boost::any> value_holder) override {
Это же шаблон, всё должно быть в хедере.

2022-11-29 09:35 UTC, BUYT-1 commented on src/algorithms/options/option.h
> +                            ? [default_value]() { return default_value.value(); }
Если убрать OptionType, то нет.
`RegisterOption(config::MakeOption(..., optional{0.01}))` <- вот тут оно уничтожится

2022-11-29 09:37 UTC, BUYT-1 commented on src/algorithms/options/option.h
> +           boost::optional<T> default_value)
Раз везде boost::any, то как будто бы везде должно быть и boost::optional. А мб и нет. Поменяю тогда.

2022-11-29 10:15 UTC, polyntsov commented on src/algorithms/options/option.h
> +    void Set(boost::optional<boost::any> value_holder) override {
Это не мешает определения вынести за пределы класса, ниже в этом ж файле

2022-11-29 10:16 UTC, polyntsov commented on src/algorithms/primitive_enum.h
> +        if constexpr (std::is_convertible_v<PrimitiveType *, PrimitiveBase *>) {
а откуда первое предложение?

2022-11-29 10:16 UTC, polyntsov commented on src/algorithms/primitive.h
> +    virtual void FitInternal(model::IDatasetStream& data_stream) = 0;
это не мешает ему быть приватным в Primitive, где он по идее только и должен вызываться

2022-11-29 10:20 UTC, polyntsov commented on src/algorithms/primitive.h
> +    config::OptAddFunc GetOptAvailFunc();
но эта функция сама по себе не меняет ничего же, а только возвращает эту лямбду, хм. Ладно, наверное тогда всё же стоит оставить так

2022-11-29 10:20 UTC, polyntsov commented on src/algorithms/primitive.h
> +    void MakeOptionsAvailable(std::string_view parent_name,
Да, это и имел в виду

2022-11-29 10:27 UTC, BUYT-1 commented on src/algorithms/options/option.h
> +                        : std::function<T()>{};
Нет, это не обсуждали. Тут optional как раз к месту - стандартного значения может и не быть, тогда при попытке его установить должна быть ошибка

2022-11-29 10:31 UTC, BUYT-1 commented on src/algorithms/options/option.h
> +                        : std::function<T()>{};
И это не value_or, тут значение сохраняется в функции

2022-11-29 10:34 UTC, BUYT-1 commented on src/algorithms/primitive_enum.h
> +        if constexpr (std::is_convertible_v<PrimitiveType *, PrimitiveBase *>) {
> а откуда первое предложение?

https://en.cppreference.com/w/cpp/types/is_base_of

2022-11-29 10:37 UTC, polyntsov commented on src/algorithms/options/option.h
> +                        : std::function<T()>{};
про `value_or` не прав и optional действительно не этот обсуждали, а тот, что в `Set`

2022-11-29 11:38 UTC, BUYT-1 commented on src/algorithms/ar_algorithm_enums.h
> +#pragma once
У этих (ещё `metric_verifier_enums.h`) файлов в общем-то только один смысл -- enum'ы, которые используются таким-то примитивом. Не вижу смысла дальше уточнять.

2022-11-29 12:24 UTC, BUYT-1 commented on src/algorithms/algo_factory.h
> +boost::any ExtractAnyFromMap(OptionMap&& options, std::string_view const& option_name) {
const не получится, т.к. из мапы извлекается пара ключ-значение, т.е. она меняется

2022-11-29 15:23 UTC, BUYT-1 commented on src/algorithms/primitive.cpp
> +        if (!it->second->IsSet()) {
Нет, оно же не пару возвращает.

2022-11-29 20:47 UTC, polyntsov commented on src/algorithms/options/option.h
> +    std::function<void(T &)> instance_check_{};
Комментарий про const только к instance_check_

2022-11-29 20:50 UTC, polyntsov commented on src/algorithms/primitive.cpp
> +        if (!it->second->IsSet()) {
Точно, а зачем тут тогда вообще итераторы?
```cpp
if (!possible_options_.at(name).IsSet()) {
    needed.insert(name);
}
```

2022-11-29 20:51 UTC, polyntsov commented on src/algorithms/algo_factory.h
> +boost::any ExtractAnyFromMap(OptionMap&& options, std::string_view const& option_name) {
да, просто ссылка

2022-11-30 17:07 UTC, polyntsov requested changes

2022-11-30 17:07 UTC, polyntsov commented on tests/test_metric_verifier.cpp
> +    auto mp = algos::StdParamsMap(map);
а зачем это копирование вообще нужно?

2022-11-30 17:07 UTC, polyntsov commented on tests/test_typo_miner.cpp
> +        std::string path = std::filesystem::current_path() / "input_data" / "TestEmpty.csv";
Повторение `std::filesystem::current_path() / "input_data"` во всем файле -- плохо, мы наоборот думаем о том, чтобы уйти от зависимости от пути до датасетов. Распространять эту зависимость не стоит

2022-11-30 17:46 UTC, BUYT-1 commented on src/algorithms/ar_algorithm.h
> +    InputFormat input_format_ = InputFormat::_values()[0];
Да тут не важно, что именно, надо просто что-то поставить, чтобы компилилось

2022-11-30 17:58 UTC, polyntsov commented on src/algorithms/ar_algorithm.h
> +    InputFormat input_format_ = InputFormat::_values()[0];
Лучше мой вариант

2022-11-30 18:26 UTC, BUYT-1 commented on src/algorithms/algo_factory.h
> +            else {
> Просто `OptionMap&`, не `const`

Не понял, к чему это

2022-11-30 18:33 UTC, BUYT-1 commented on tests/test_apriori.cpp
>      auto input_params = std::make_shared<model::Singular>(0, 1);
> Все еще думаю, что ее стоит перенести в main

algorithms/options/descriptions.h

2022-11-30 18:44 UTC, polyntsov commented on src/algorithms/algo_factory.h
> +            else {
Сначала там был комментарий, что стоит принимать мапу опций по `OptionMap const&`, но ты справедливо заметил, что она меняется. При этом передавать владение в эту функцию все еще смысла как будто не очень много, поэтому я предложил просто `OptionMap&`

2022-11-30 18:46 UTC, polyntsov commented on tests/test_apriori.cpp
>      auto input_params = std::make_shared<model::Singular>(0, 1);
и правда (твой комментарий явно не к нужному моему), но думаю, что ту функцию тогда и стоит перенести в `descriptions.h`

2022-11-30 18:47 UTC, BUYT-1 commented on tests/test_metric_verifier.cpp
> +    auto mp = algos::StdParamsMap(map);
Ссылка выдаётся константная, должна быть неконстантная, т.к. одна из функций извлекает пару из мапы

2022-11-30 18:48 UTC, BUYT-1 commented on tests/test_typo_miner.cpp
> +        std::string path = std::filesystem::current_path() / "input_data" / "TestEmpty.csv";
Не понял. Зависимости в целом и так нет, указывай что хочешь. А как в тестах от неё уходить (и зачем) -- непонятно. Или просто в переменную это засунуть, хочешь сказать?

2022-11-30 18:48 UTC, polyntsov commented on tests/test_metric_verifier.cpp
> +    auto mp = algos::StdParamsMap(map);
Так тогда аргумент надо просто принимать по значению. Заодно вызывающий код сможет сделать `std::move`

2022-11-30 18:49 UTC, BUYT-1 commented on tests/test_typo_miner.cpp
> +        std::string path = std::filesystem::current_path() / "input_data" / "TestEmpty.csv";
Тут всего два повторения, кстати

2022-11-30 18:50 UTC, polyntsov commented on tests/test_typo_miner.cpp
> +        std::string path = std::filesystem::current_path() / "input_data" / "TestEmpty.csv";
Зависимость в том, что датасеты должны лежать строго в `"input_data"`, иначе тесты упадут. В какой-то момент хотелось это поправить.
Да, можно просто положить в переменную хотя бы

2022-11-30 18:52 UTC, BUYT-1 commented on src/algorithms/typo_miner.h
> +        SetOption(RatioOpt.GetName(), std::optional<boost::any>{ratio});
Тьфу, `SetOption` и так делает `UnsetOption`

2022-11-30 20:37 UTC, polyntsov approved these changes
LGTM, nice work!

2022-11-30 20:48 UTC, merged