Python bindings
Mstrutov/Desbordante pull request #160
Opened 2022-12-01 20:18 UTC by BUYT-1

Only for FDAlgorithm (most primitives are FD algorithms), partial implementation for other primitives.

2022-12-02 12:56 UTC, polyntsov requested changes
@Mstrutov как думаешь, должна ли директория `python_bindings` лежать в `src` или рядом, как сейчас?

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/py_fd_primitive.h
> +    std::string ToString() {
nit: тоже `[[nodiscard]]` тогда уж

2022-12-02 12:56 UTC, polyntsov commented on src/algorithms/options/option.h
> +#include <typeindex>
Нужно напрямую включить `typeinfo`

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/py_to_any.cpp
> +    assert(0);
стоит убрать, раз исключение снизу

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/py_to_any.cpp
> +static std::array<std::pair<std::type_index, ConvFunc>, 11> converters{
11 лишнее, вывод шаблонных параметров должен сработать

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/bindings.cpp
> +            .def("execute", &PyMetricVerifier::Execute);
какой-то очень уж boiler plate код, думаю, можно сделать, например, макросами или подумать над чем-нибудь получше (пока что можно оставить и так)

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/py_primitive.h
> +}
`}  // namespace python_bindings`

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/py_to_any.cpp
> +{return boost::any(py::cast<type>(value));})
нужно нормально отформатировать (вряд ли clang-format осилит):
```cpp
#define NORMAL_CONV(type)                                        \
    std::make_pair(std::type_index(typeid(type)),                \
                   [](py::object const& value) {                 \
                       return boost::any(py::cast<type>(value)); \
                   });
```

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/py_to_any.cpp
> +{return boost::any(py::cast<type>(value));})
и `ENUM_CONV` тоже

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/py_to_any.cpp
> +{return boost::any(py::cast<type>(value));})
а еще дефайны вынести наверх до определения этого array, а-то странно выглядит и сложно читать

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/py_to_any.cpp
> +static std::array<std::pair<std::type_index, ConvFunc>, 11> converters{
Этот `array` пар ведь используется только как map, стоит и сделать его map'ом

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/py_fd_primitive.h
> +    std::vector<unsigned int> indices{};
не используется

2022-12-02 12:56 UTC, polyntsov commented on python_bindings/py_fd_primitive.h
> +    std::vector<PyFD> Execute(py::kwargs const& kwargs) {
Если `Execute()` возвращает намайненное, то как получить время, за которое оно отработало?

2022-12-02 17:40 UTC, BUYT-1 commented on python_bindings/py_to_any.cpp
> +static std::array<std::pair<std::type_index, ConvFunc>, 11> converters{
> 11 лишнее, вывод шаблонных параметров должен сработать

Вывод шаблонных параметров тут не работает.

> Этот array пар ведь используется только как map, стоит и сделать его map'ом

Так нельзя ж, non-trivially-destructible статический объект.

2022-12-02 17:52 UTC, BUYT-1 commented on python_bindings/py_fd_primitive.h
> +    std::vector<PyFD> Execute(py::kwargs const& kwargs) {
Зачем в питоне время?

2022-12-02 17:56 UTC, polyntsov commented on python_bindings/py_to_any.cpp
> +static std::array<std::pair<std::type_index, ConvFunc>, 11> converters{
> Вывод шаблонных параметров тут не работает.
А, да, частичный для классов не работает. Надо тогда и тип пары не указывать, а в макроссе указать его явно у `make_pair`

> Так нельзя ж, non-trivially-destructible статический объект.
он с внутренней линковкой и соответственно доступен только внутри этого translation unit, для таких объектов порядок удаления и создания фиксирован и известен, не думаю, что могут быть какие-то проблемы

2022-12-02 17:59 UTC, polyntsov commented on python_bindings/py_fd_primitive.h
> +    std::vector<PyFD> Execute(py::kwargs const& kwargs) {
не знаю, но не могу быть увереным, что оно точно не нужно. Возможно, какие-то скрипты с экспериментами будет удобнее писать сразу из питона

2022-12-03 09:12 UTC, polyntsov requested changes

2022-12-03 09:12 UTC, polyntsov commented on python_bindings/py_primitive.h
> +    PrimitiveType primitive;
`primitive_`

2022-12-03 09:12 UTC, polyntsov commented on python_bindings/py_fd_primitive.h
> +    PyFD(RawFD const& fd) : rhs_index_(fd.rhs_) {
nit: explicit

2022-12-03 09:12 UTC, polyntsov commented on python_bindings/py_primitive.h
> +protected:
модификаторы доступа в другом порядке

2022-12-03 09:12 UTC, polyntsov commented on python_bindings/pandas_reader.cpp
> +      column_names_(dataframe.attr("columns").attr("to_list")().cast<std::vector<std::string>>()) {}
а как оно работает, когда имён колонок нет? (как в iris.csv, например)

2022-12-03 09:32 UTC, BUYT-1 commented on python_bindings/pandas_reader.cpp
> +      column_names_(dataframe.attr("columns").attr("to_list")().cast<std::vector<std::string>>()) {}
У pd.Dataframe они всегда есть. Если их нет, то это просто инты. И я этот случай не учёл, правлю

2022-12-03 12:00 UTC, polyntsov approved these changes
LGTM

2022-12-03 12:00 UTC, merged