Add 'help', 'tests', 'jobs' and 'pybind' options for build script
Mstrutov/Desbordante pull request #166
Opened 2022-12-15 00:19 UTC by vs9h

In this commit, changes are made to the scripts for building from the repository with the web version. Added the following features:
* assembly of bindings for python is made optional;
* assembly of tests and datasets unpacking is made optional;
* support for multi-threaded build option;
* skip downloading all the history up for submodules (for example, for package `easyloggingpp` we would download 769kb instead of 30mb, similar for other packages)

2023-02-05 19:03 UTC, polyntsov requested changes

2023-02-05 19:03 UTC, polyntsov commented on build.sh
> +        -t|--tests) # Enable tests build and datasets unpacking
Думаю, тесты должны собираться по умолчанию. Этот скрипт ведь во многом нужен, чтобы человек мог просто склонить репозиторий и сделать `./build.sh` не особо думая, что происходит. @Mstrutov ?

2023-02-05 19:03 UTC, polyntsov commented on build.sh
> +cmake $PREFIX .. "-DCMAKE_BUILD_TYPE=RELEASE"
Стоит тогда и добавить опцию для build_type

2023-02-05 19:03 UTC, polyntsov commented on build.sh
> +git clone https://github.com/aantron/better-enums.git --branch 0.11.3 --depth 1
Думаю, стоит сначала проверить, что библиотеки ещё не склонированы и только в этом случае делать `git clone`

2023-02-05 19:03 UTC, polyntsov commented on CMakeLists.txt
> +option(ENABLE_TESTS_COMPILE "Build tests and unpack datasets" ON)
Байдинги для питона скорее должны быть выключены по умолчанию

2023-02-05 19:06 UTC, polyntsov commented on build.sh
> +git clone https://github.com/aantron/better-enums.git --branch 0.11.3 --depth 1
Или вообще перенести эти зависимости в `CMakeLists.txt`?

2023-02-05 20:44 UTC, vs9h commented on build.sh
> +git clone https://github.com/aantron/better-enums.git --branch 0.11.3 --depth 1
Добавил проверку, в `CMakeLists.txt` не переносил

2023-02-05 20:44 UTC, vs9h commented on build.sh
> +        -t|--tests) # Enable tests build and datasets unpacking
Добавил сборку тестов по умолчанию

2023-02-07 07:12 UTC, Mstrutov commented on build.sh
> +        -t|--tests) # Enable tests build and datasets unpacking
Да, лучше собирать тесты по умолчанию.
Только тогда надо заменить коммент
`# Enable tests build and datasets unpacking` --> `# Disable tests build`, `# Unpack datasets`

2023-02-07 07:14 UTC, Mstrutov commented on build.sh
> +git clone https://github.com/aantron/better-enums.git --branch 0.11.3 --depth 1
В `CMakeLists` перенесём отдельным PRом, если понадобится. А то Антону придётся почти всю логику из `sh` в `CMake` переносить, причём плюсы пока неочевидны.

2023-02-07 07:16 UTC, Mstrutov approved these changes

2023-02-07 07:19 UTC, Mstrutov commented
Единственное, коммиты без описания --- стоит хотя бы скопипастить в один из них описание PR'а, чтобы оно сохранилось в гит истории, а не только в ГХ.

2023-02-11 10:54 UTC, polyntsov requested changes
Надо в ридми дописать, что чтобы собрать с тестами и оно запустилось, нужно указывать опцию `-u` (иначе тесты упадут)

2023-02-11 10:54 UTC, polyntsov commented on CMakeLists.txt
> +    endif()
Надо скорее выше поставить if, что если включен `COMPILE_PYBIND`, то отключаем опцию `ASAN` (и возможно даже ворнинг какой-нибудь вывести). Потому что это то, что должно происходить концептуально

2023-02-11 10:54 UTC, polyntsov commented on build.sh
> +  -n,         --no-tests              Don't build test
```suggestion
  -n,         --no-tests              Don't build tests
```

2023-02-11 11:26 UTC, polyntsov approved these changes

2023-02-11 12:27 UTC, merged