Support repeated execution
Mstrutov/Desbordante pull request #171
Opened 2023-02-06 10:39 UTC by BUYT-1

Repeated execution didn't work correctly, this fixes it.
Progress bars are reset and found FDs are cleared before execution\*, all configuration options are unset after execution.

2023-02-11 13:26 UTC, polyntsov requested changes

2023-02-11 13:26 UTC, polyntsov commented on src/algorithms/primitive.cpp
> +    auto time_ms = ExecuteInternal();
На самом деле нужен абстрактный метод, который будет вызываться вот тут перед `ExecuteInternal()`. Какой-нибудь `PrepareExecute()` как раз (у нас метод с таким названием уже есть, но возможно его стоит переименовать во что-нибудь вроде `FinilizeFit`). Это позволит разделить логику и не вписывать везде в начало ExecuteInternal() код очищения состояния

2023-02-11 13:26 UTC, polyntsov commented on tests/test_algorithm.cpp
> +    auto algorithm = TestFixture::CreateAlgorithmInstance(path / "breast_cancer.csv", ',', true);
Датасет слишком большой для такого теста, поэтому долго выполняется, надо взять что-нибудь маленькое вроде WDC_ датасетов, их должно быть достаточно, чтобы найти возможные проблемы
Надо только убедиться, что список зависимостей не пустой на выбранном датасете

2023-02-11 13:26 UTC, polyntsov commented on tests/test_algorithm.cpp
> +    SUCCEED();
Ничего не делает

2023-02-11 13:26 UTC, polyntsov commented on tests/test_algorithm.cpp
> +        EXPECT_TRUE(CheckFdListEquality(first_res, algorithm->FdList()));
Скорее должно быть `ASSERT_TRUE`, если первая же итерация нашла другие зависимости, то вряд ли ещё одно выполнение `Execute()` исправит ситуацию

2023-02-11 13:26 UTC, polyntsov commented on tests/test_metric_verifier.cpp
> +    algos::ConfigureFromMap(*verifier, algos::StdParamsMap{params});
а зачем?

2023-02-11 13:26 UTC, polyntsov commented on tests/test_typo_miner.cpp
> +                    << ")" << std::endl;
копипасту конструирования строки с ошибкой следует вынести в отдельную функцию

2023-02-11 13:31 UTC, BUYT-1 commented on tests/test_metric_verifier.cpp
> +    algos::ConfigureFromMap(*verifier, algos::StdParamsMap{params});
После `Execute` все опции сбрасываются, надо ещё раз поставить

2023-02-11 13:33 UTC, BUYT-1 commented on src/algorithms/primitive.cpp
> +                          std::optional<boost::any> const &value) {
а ругается clang-format на меня

2023-02-11 13:52 UTC, polyntsov commented on src/algorithms/primitive.cpp
> +                          std::optional<boost::any> const &value) {
Это странно, хм

2023-02-11 13:52 UTC, polyntsov commented on src/algorithms/primitive.cpp
> +                          std::optional<boost::any> const &value) {
Или подожди, если clang-format на самом деле ругается, то все правки в другую сторону просто неправильные

2023-02-11 13:55 UTC, polyntsov commented on src/algorithms/primitive.cpp
> +                          std::optional<boost::any> const &value) {
Не, кажется, такого правила не должно быть в clang-formate и оба варианта верные. СКинь ссылку на ран, где ругается

2023-02-12 12:11 UTC, BUYT-1 commented on src/algorithms/primitive.cpp
> +                          std::optional<boost::any> const &value) {
> Не, кажется, такого правила не должно быть в clang-formate и оба варианта верные. Скинь ссылку на вокрфлоу ран, где ругается

https://github.com/Mstrutov/Desbordante/actions/runs/4102780357/jobs/7076158562

2023-02-12 12:36 UTC, polyntsov commented on src/algorithms/primitive.cpp
> +                          std::optional<boost::any> const &value) {
Я был не прав, это опция `DerivePointerAlignment` и по идее ругается по правилам. Только он всё ещё ругаться не должен, потому что ты это место не менял. В целом поэтому я и назвал их лишними, если править форматирование в чужом коде, который не затрагивается текущими изменениями, то целиком и отдельным коммитом.
Это баг воркфлоу, там `git diff` показывает слишком много контекста вокруг изменений, сейчас поправлю

2023-02-22 05:50 UTC, BUYT-1 commented on tests/test_algorithm.cpp
> +    auto algorithm = TestFixture::CreateAlgorithmInstance(path / "breast_cancer.csv", ',', true);
Не, тут были все датасеты, сейчас нормально всё с временем выполнения.

2023-02-22 17:48 UTC, BUYT-1 commented on tests/test_algorithm.cpp
> +    auto algorithm = TestFixture::CreateAlgorithmInstance(path / "breast_cancer.csv", ',', true);
Нет, всё равно было долго, поставил WDC_astronomical

2023-02-26 12:44 UTC, polyntsov requested changes

2023-02-26 12:44 UTC, polyntsov commented on src/algorithms/metric/metric_verifier.h
> +    void ResetState() final {};
nit: `metric_fd_hols_ = false`. Это конечно ни на что не влияет (в данный момент), но всё же начальное состояние такое

2023-02-26 12:44 UTC, polyntsov commented on src/algorithms/fdep/fdep.h
> +    void ResetStateFd() final {}
Тут нужно удалять объекты `neg_cover_tree_` и `pos_cover_tree_`

2023-02-26 12:44 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +    all_stats_ = std::vector<ColumnStats>{col_data_.size()};
nit: `all_stats_.assign(col_data.size(), ColumnStats())`, вектор целиком пересоздавать незачем

2023-02-26 12:44 UTC, polyntsov commented on src/algorithms/aidfd/aid.cpp
> +    fd_collection_.clear();
Это уже делается в `FDAlgorithm::ResetState`

2023-02-26 12:44 UTC, polyntsov commented on src/algorithms/aidfd/aid.cpp
>      prev_ratios_ = std::vector<double>(window_size_, 1.0);
nit: тут векторы тоже можно не пересоздавать целиком, а воспользоваться `assign` (и `reset()` для `constant_columns_`)

2023-02-26 12:44 UTC, polyntsov commented on tests/test_fd_mine.cpp
> +        // FIXME: hangs on this dataset
Я не думаю, что есть способ это пофиксить, поэтому комментарий "FIXME" misleading.
Ну и на деле он тут очень долго работает, а не зависает на совсем, скорее всего результата можно дождаться за конечное время

2023-02-26 12:44 UTC, polyntsov commented on tests/test_data_stats.cpp
> +}
nit: очень уж напоминает такой же метод, в `testing_utils.h`, их обобщить бы

2023-02-26 12:44 UTC, polyntsov commented on tests/test_data_stats.cpp
> +    auto stats_ptr = MakeStatPrimitive("TestDataStats.csv", ',', false);
nit: вынести бы имя файла в переменную, чтобы при следующим переименовании не пришлось менять n вхождений.

2023-02-26 12:44 UTC, polyntsov commented on tests/test_apriori.cpp
> +std::set<std::pair<std::set<std::string>, std::set<std::string>>> ToSet(
Должно быть `static`

2023-02-26 12:44 UTC, polyntsov commented on tests/test_data_stats.cpp
> +}
не в этом пулреквесте, примерно такой же есть ещё и в `test_apriori.cpp`

2023-02-27 13:13 UTC, BUYT-1 commented on src/algorithms/fdep/fdep.h
> +    void ResetStateFd() final {}
`neg_cover_tree` создаётся заново в `BuildNegativeCover`, `pos_cover_tree_` в `ExecuteInternal`. Убрать и сделать здесь?

2023-02-27 15:26 UTC, polyntsov commented on src/algorithms/fdep/fdep.h
> +    void ResetStateFd() final {}
Да, создаются заново, но всё же концептуально эти поля - часть состояния алгоритма и этот метод должен это состояние сбрасывать. Кроме того то, что сейчас они создаются в методах (причем разных) полностью заново не значит, что так будет после какого-нибудь рефакторинга

2023-02-28 07:24 UTC, BUYT-1 commented on src/algorithms/statistics/data_stats.cpp
> +    all_stats_ = std::vector<ColumnStats>{col_data_.size()};
> nit: `all_stats_.assign(col_data.size(), ColumnStats())`, вектор целиком пересоздавать незачем

Оно так [течёт](https://github.com/Mstrutov/Desbordante/actions/runs/4285749467/jobs/7464431087), надо ещё чистить вектор.

2023-02-28 07:39 UTC, BUYT-1 commented on src/algorithms/statistics/data_stats.cpp
> +    all_stats_ = std::vector<ColumnStats>{col_data_.size()};
Пусть кто-то другой с этим разбирается. Кажется, у `Statistic` что-то не так с присваиванием.

2023-03-03 18:12 UTC, polyntsov approved these changes

2023-03-03 18:15 UTC, merged

2023-04-06 21:41 UTC, BUYT-1 commented on src/algorithms/aidfd/aid.cpp
>      prev_ratios_ = std::vector<double>(window_size_, 1.0);
> и reset() для `constant_columns_`
Нет

2023-04-06 22:45 UTC, polyntsov commented on src/algorithms/aidfd/aid.cpp
>      prev_ratios_ = std::vector<double>(window_size_, 1.0);
`reset` не меняет размер битсета, только выставляет все биты в 0

2023-04-06 22:50 UTC, BUYT-1 commented on src/algorithms/aidfd/aid.cpp
>      prev_ratios_ = std::vector<double>(window_size_, 1.0);
Ой, это я про `clear`