Change 'data' field type, refactor 'main.cpp' file
Mstrutov/Desbordante pull request #172
Opened 2023-02-07 03:32 UTC by vs9h

* Change type for `data` from `std::string` to `std::filesystem::path`
* Refactor `main.cpp`

2023-02-11 12:09 UTC, polyntsov requested changes
Нужно описание к пру/коммиту о том, *зачем* эти изменения сделаны (про то, что они достаются в срр консьюмере в веб приложении и тд)

2023-02-11 12:09 UTC, polyntsov commented on src/algorithms/options/all_options.h
> +static auto infoOptions() {
Функции именуются с большой буквы

2023-02-11 12:09 UTC, polyntsov commented on src/algorithms/options/all_options.h
> +static auto infoOptions() {
По-моему ни одна функция из определенных в этом файле не должна быть тут определена, определение должно быть в соответствующем cpp файле

2023-02-11 12:09 UTC, polyntsov commented on src/algorithms/options/all_options.h
> +static const auto general_options = details::generalOptions();
а зачем нам для этого глобальные объекты? Почему не вызывать функцию в коде, где это нужно? По-моему это делается ровно один раз за программу

2023-02-11 12:09 UTC, polyntsov commented on src/algorithms/options/all_options.h
> +static std::string const kSeparatorOpt = std::string(algos::config::names::kSeparator) + ",s";
Почему это глобальная статическая переменная?

2023-02-11 12:09 UTC, polyntsov commented on src/algorithms/options/descriptions.h
> +constexpr auto kDHelp = "print the help message and exit";
Эти опции относятся к cli версии и только, которую планируется делать в питоне. В core библиотеке им по идее делать нечего

2023-02-13 19:53 UTC, vs9h commented on src/algorithms/options/all_options.h
> +static std::string const kSeparatorOpt = std::string(algos::config::names::kSeparator) + ",s";
Сделал её локальной статической переменной, т.к. мы передаём в список опций `char const *` и копирования не происходит, поэтмоу переменная должна жить и после выхода из функции.

2023-02-13 19:54 UTC, vs9h commented on src/algorithms/options/descriptions.h
> +constexpr auto kDHelp = "print the help message and exit";
Вынес `help`, `primitive` кажется отноится не только к cli версии

2023-02-20 12:46 UTC, polyntsov requested changes

2023-02-20 12:46 UTC, polyntsov commented on src/algorithms/options/all_options.h
> +}  // namespace algos
nit: странно проставленные пустые строки (и в cpp файле тоже)

2023-02-20 12:46 UTC, polyntsov commented on src/algorithms/options/all_options.h
> +namespace general {
Не очень подходящее имя для пространства имён кмк. Скорее должно быть `algos::config::general`, весь этот код ведь относится именно к конфигурации, а не к чему-то "общему" у алгоритмов

2023-02-20 12:46 UTC, polyntsov commented on src/algorithms/options/all_options.h
> +}  // namespace metric
Этот код нужен только в `all_options.cpp`, туда его и стоит поместить

2023-02-20 12:46 UTC, polyntsov commented on src/algorithms/options/all_options.h
> +}  // namespace metric
а зачем?

2023-02-20 12:46 UTC, polyntsov commented on src/main.cpp
> +    auto all_options = ::InfoOptions().add(GeneralOptions()).add(AlgoOptions());
nit: указание глобального неймспейса `::` не нужно, этот код и так в нём лежит. И `::kHelp` снизу тоже.

2023-02-28 17:50 UTC, vs9h commented on src/algorithms/options/all_options.h
> +}  // namespace metric
Функция validate должна быть определена в том же неймспейсе, что и енам, для которого вызывается.
В прошлой реализации в мэйне для каждого енама эта функция копипастилась, тут я сделал шаблонную функцию в algos и добавил этот using.

2023-02-28 17:55 UTC, polyntsov commented on src/algorithms/options/all_options.h
> +}  // namespace metric
> Функция validate должна быть определена в том же неймспейсе, что и енам, для которого вызывается.

Уверен, что такое требование есть?

2023-02-28 19:52 UTC, vs9h commented on src/main.cpp
> +    auto all_options = ::InfoOptions().add(GeneralOptions()).add(AlgoOptions());
Я оказывается определение для `InfoOptions` забыл убрать, поэтому в мэйне вызов этой функции был `ambiguous` и добавил ::, чтобы зарезолвить вызов функции.

2023-02-28 19:55 UTC, vs9h commented on src/algorithms/options/all_options.h
> +}  // namespace metric
Иначе не работает

2023-03-03 18:28 UTC, polyntsov requested changes
Форматированние. Надо поправить то, что репортить clang-format, либо обернуть в
```
// clang-format off
// clang-format on
```
места, где он репортит неправильно.
А ещё ребейз на мейн и там добавилось ещё несколько зависимостей от "input_data" в тестах, их тоже нужно поправить

2023-03-03 19:18 UTC, BUYT-1 requested changes

2023-03-03 19:18 UTC, BUYT-1 commented on src/algorithms/options/all_options.cpp
> +    fd_options.add(mfd_options).add(ar_options).add(ac_options).add(typo_options);
`.add` добавляет подраздел к разделу.
Здесь нужно создать `po::options_description algorithm_options("Algorithm options")` (в принципе, описание можно оставить пустым) а потом к нему это всё добавлять (`algorithm_options.add(fd_options).add(mfd_options)...)`), иначе отображаться неправильно будет.

2023-03-03 19:54 UTC, vs9h commented on src/algorithms/options/all_options.cpp
> +    using namespace descriptions;
Это нужно для того, чтобы использовать нэймспейс `algos::config::general::names` и `algos::config::general::descriptions`. Там лежит информация для опции `primitive`

2023-03-03 20:53 UTC, vs9h commented on src/algorithms/options/all_options.cpp
> +    using namespace descriptions;
upd: в итоге решили убрать неймспейс для general, поэтому убрал эти строки

2023-03-03 21:40 UTC, BUYT-1 commented on src/algorithms/options/all_options.cpp
> +    return fd_options;
`return algorithm_options;`

2023-03-03 23:20 UTC, polyntsov approved these changes

2023-03-04 00:15 UTC, merged