Implement FDVerifier
Mstrutov/Desbordante pull request #184
Opened 2023-02-28 13:53 UTC by Aviu00

Implements a primitive for verifying a particular FD, which also shows useful statistics for the user in case FD does not hold.

2023-03-03 23:06 UTC, polyntsov requested changes
а верификация AFD будет отдельным prом?

2023-03-03 23:06 UTC, polyntsov commented on src/algorithms/fd_verifier.cpp
> +            LOG(INFO) << GetRhsStringValue(index);
```suggestion
            LOG(DEBUG) << GetRhsStringValue(index);
```

2023-03-03 23:06 UTC, polyntsov commented on src/algorithms/fd_verifier.cpp
> +void FDVerifier::CalculateStatistics(std::deque<util::PLI::Cluster> const& clusters) {
Эти кластеры ведь больше нигде не используются и владеет ими вызывающая функция. Думаю, можно вполне принимать по значению тут, перемещать в вызывающем коде и в этой функции перемещать нужные в `highlights_`

2023-03-04 13:53 UTC, Aviu00 commented on src/algorithms/fd_verifier.cpp
> +    }
Если ифы убрать, то будет работать только с `MixedType`. Если строковый/числовой тип, то выдаст segmentation fault, а если `UndefinedType` выдаст исключение "Meaningless operation..."

2023-03-04 13:58 UTC, Aviu00 commented on src/algorithms/fd_verifier.cpp
> +void FDVerifier::CalculateStatistics(std::deque<util::PLI::Cluster> const& clusters) {
А как их перемещать, если `GetIndex()` по ссылке возвращает?

2023-03-04 14:00 UTC, Aviu00 commented on src/algorithms/fd_verifier.cpp
> +    }
Я не особо понял

2023-03-04 14:46 UTC, polyntsov commented on src/algorithms/fd_verifier.cpp
> +void FDVerifier::CalculateStatistics(std::deque<util::PLI::Cluster> const& clusters) {
Так по не константной же

2023-03-04 14:47 UTC, polyntsov commented on src/algorithms/fd_verifier.cpp
> +    }
Для верификации считаем, что если колонка в колонке встречаются значения больше, чем одного типа, то она вся строковая. То есть сравнения надо делать либо через `ValueToString()`, либо добавить в код вывода типов опцию, чтобы вместо `Mixed` колонок выводились типа `String`

2023-03-04 14:50 UTC, polyntsov commented on src/algorithms/fd_verifier.cpp
> +    }
Потому что нужно использовать не `ValueToString` у типов напрямую, а `TypedColumnData::GetDataAsString()`

2023-03-04 17:19 UTC, Aviu00 commented on src/algorithms/fd_verifier.cpp
> +void FDVerifier::CalculateStatistics(std::deque<util::PLI::Cluster> const& clusters) {
Константной

2023-03-07 15:03 UTC, Aviu00 commented
Вроде по AFD не будет prа

2023-03-08 10:17 UTC, Aviu00 commented on src/algorithms/fd_verifier.cpp
> +    }
Это так не будет работать. Если справа есть кластеры, а слева их вообще нет, например.

2023-03-08 13:42 UTC, polyntsov commented on src/algorithms/fd_verifier.cpp
> +    }
И правда

2023-03-09 10:25 UTC, polyntsov requested changes
И нужно, чтобы чек `clang-format` проходил

2023-03-09 10:25 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +    long double num_tuples_conflicting_on_rhs = 0.;
Почему количество пар - это `double`?

2023-03-09 10:25 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +        }
Это вполне можно вынести в отдельную static функцию, как и вычисление `num_most_frequent_rhs_value` снизу. Читать этот цикл довольно тяжело из-за того, что перемешана логика с инициализацией разных переменных

2023-03-09 10:25 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +        }
И вычисление `num_different_rhs_values` сверху тоже вполне себе можно вынести

2023-03-09 10:25 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +            if (pair.second > 1) {
Кажется, во `frequencies` не бывает значений, у которых `.second <= 1`, тут можно ассерт вставить вместо if'a

2023-03-09 10:25 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +    }
Странный `if` и логгирование ошибки. Кажется, что после цикла сверху `highlights_` в целом никогда не должен быть пустым (иначе фз удерживается и мы в этот метод попасть вообще не должны). Тут скорее должно быть `assert(!highlights_.empty());`

2023-03-09 10:25 UTC, polyntsov commented on src/algorithms/fd_verifier/highlight.h
> +};
Это скорее должно быть классом с приватными полями, потому что есть инвариант на `num_different_rhs_values` и `most_frequent_rhs_value_proportion`, не должно быть возможности поменять их напрямую через поля. Кажется, что геттеров будет достаточно

2023-03-09 10:25 UTC, polyntsov commented on src/algorithms/fd_verifier/fd_verifier.h
> +    model::CompareResult CompareTypes(util::PLI::Cluster::value_type i1,
На самом деле кажется, что этот метод не должен быть публичным (в `StatsCalculator`, этому классу он вообще не нужен). Он используется только для тестирования и проверки, что отсортировалось верно. Думаю, лучше это будет сделать примерно следующим способом:
сделать в `StatsCalculator` одну функцию `SortHighlights`, которая принимает компаратор и n статическиз функций, возвращающих компараторы. `FDVerifier` в методах `SortHighlightsBy...` будет вызывать `StatsCalculator::Sort` с нужным компаратаром. Для тестирования того, что все отсортировалось как нужно достаточно будет сделать `std::is_sorted(highlights.begin(), highlights.end(), StatsCalculator::CompareByProportionAsc()`, где `StatsCalculator::CompareByProportionAsc()` возвращает компаратор с нужным условием

2023-03-09 10:25 UTC, polyntsov commented on tests/test_fd_verifier.cpp
> +    // Test sorting
думаю, можно вынести в отдельную статическую функцию

2023-03-10 09:08 UTC, Aviu00 commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +            if (pair.second > 1) {
Вообще-то бывает

2023-03-10 09:21 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +            if (pair.second > 1) {
Мы делаем `frequencies[value]++`, когда `value != singleton_value_id_`. Это, кажется, означате, что `value` встречается в таблице больше одного раза. А остальные `value` во `frequencies` не попадают

2023-03-10 17:38 UTC, Aviu00 commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +            if (pair.second > 1) {
Может быть такое, что lhs кластер, который мы рассматриваем пересекается с каким-либо кластером в правой части только на одном значении. В таком случае frequency будет 1

2023-03-10 17:39 UTC, Aviu00 commented on tests/test_fd_verifier.cpp
> +    // Test sorting
Тесты сортировок вынести?

2023-03-10 17:41 UTC, Aviu00 commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +    }
Ну, если `highlights` пустой, то это не критично, просто лишняя работа выполнилась. Не думаю, что `assert` тут нужен

2023-03-10 17:45 UTC, Aviu00 commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +    long double num_tuples_conflicting_on_rhs = 0.;
Вроде как `falling_factorial` возвращает `double`, да и потом все равно бы пришлось кастовать при делении. Вообще, можно не вызывать `falling_factorial`, а просто 2 числа умножить

2023-03-10 17:47 UTC, polyntsov commented on tests/test_fd_verifier.cpp
> +    // Test sorting
ага, но можно и оставить, в целом не критично :)

2023-03-10 17:54 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +    }
Тогда я чего-то не понимаю. Вот это, получается, не правда?
>  Кажется, что после цикла сверху highlights_ в целом никогда не должен быть пустым (иначе фз удерживается и мы в этот метод попасть вообще не должны).

2023-03-10 17:56 UTC, Aviu00 commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +    }
Нет, не может. Там ведь `ERROR` и выводится. Могу убрать его

2023-03-10 17:57 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +    long double num_tuples_conflicting_on_rhs = 0.;
Тогда как будто лучше перемножать два числа. Мы так точно не попадем в ситуацию, где количество пар считается неправильно из-за неточной арифметики и округлений вниз

2023-03-10 18:01 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +            if (pair.second > 1) {
а, действительно, `frequencies` ведь строится по кластерам после пересечений.
Кажется, что на такие вопросы в ревью лучше отвечать прямо в коде комментариями, потому что если у меня такой вопрос возник, то вероятно он возникнет и у следующего человека, читающего код

2023-03-10 18:03 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.cpp
> +    }
а почему тогда `assert` не подходит? Он ведь проверяет инвариант, который должен тут удерживаться всегда, если переданы правильные аргументы и в коде нет багов, а это то, что у нас тут происходит

2023-03-11 12:14 UTC, Aviu00 commented on src/algorithms/fd_verifier/fd_verifier.h
> +    model::CompareResult CompareTypes(util::PLI::Cluster::value_type i1,
Там только методы сравнения по LHS не получится статическими сделать

2023-03-11 14:47 UTC, polyntsov approved these changes

2023-03-11 14:47 UTC, polyntsov commented on src/algorithms/fd_verifier/stats_calculator.h
> +            std::unordered_map<ClusterIndex, unsigned> const& frequencies);
nit: Думаю, с точки зрения дизайна было бы лучше поместить эти классы в анонимный неймспейс в `cpp`, они всё же реализуют очень маленькую часть логики конкретного метода подсчета `highlights` и по отдельности вне его имеют мало смысла

2023-03-11 14:47 UTC, polyntsov commented on tests/test_fd_verifier.cpp
> +void TestSorting(std::unique_ptr<FDVerifier> verifier) {
nit: кажется, что лучше принимать raw pointer/объект по ссылке, потому что такая сигнатура функции заставляет вызывать её в конце тестирующего `verifier` метода. Но сейчас, поскольку тестирующий метод всего один и эта функция там вызывается в конце, это ни на что не влияет

2023-03-11 14:47 UTC, merged