Expose some MetricVerifier configuration options
Mstrutov/Desbordante pull request #187
Opened 2023-03-07 16:57 UTC by yaroslav2k

In order to allow backend cpp-consumer service to generate MFD highlights some of MetricVerifier configuration options have to be publicly available.

See https://github.com/vs9h/Desbordante/pull/77 for details

2023-03-07 17:29 UTC, polyntsov requested changes

2023-03-07 17:46 UTC, yaroslav2k commented on src/algorithms/metric/metric_verifier.h
> +    std::vector<unsigned int> GetRhsIndices() const {
исправил, спасибо!

2023-03-07 18:53 UTC, polyntsov requested changes

2023-03-07 18:53 UTC, polyntsov commented on src/algorithms/metric/metric_verifier.h
> +                               ClusterIndex row_index) const;
Этот метод точно не должен быть публичным. Он сейчас вообще существует только потому что С++ desbordante не умеет в нормальный CLI, как-только CLI сделают, этот метод скорее всего будет удален. Если он нужен на бекенде -- то скорее всего вы делаете что-то не так

2023-03-07 18:56 UTC, polyntsov commented on src/algorithms/metric/metric_verifier.h
> +                               ClusterIndex row_index) const;
Алгоритм возвращает результат в качестве индексов в таблице (метод `GetHighlights`) -- его и стоит использовать. А конкретные значения строк уже находить по этим индексам на сервере и преобразовывать их как нужно

2023-03-14 14:49 UTC, yaroslav2k commented on src/algorithms/metric/metric_verifier.h
> +                               ClusterIndex row_index) const;
Да, спасибо, этот метод действительно не нужен. Убрал

2023-03-14 16:29 UTC, polyntsov requested changes

2023-03-14 16:29 UTC, polyntsov commented on src/algorithms/metric/metric_verifier.h
> +    std::vector<unsigned int> const& GetLhsIndices() const {
Теперь тут возвращаемый тип `config::IndicesType`, и в `GetRhsIndices` тоже :)

2023-03-18 12:22 UTC, polyntsov approved these changes

2023-03-18 13:50 UTC, merged