Add exceptions collecting to ACAlgorithm
Mstrutov/Desbordante pull request #190
Opened 2023-03-10 16:52 UTC by Sched71

This commit provides functionality of discovering exceptional records (rows) for ACAlgorithm. The row is exceptional, if for at least one pair of columns binary operation on values from that row didn't belong to ranges, that were previosly found by the algorithm.
Also `ReconstructRangesByColumns` method was added.

2023-03-10 17:10 UTC, Sched71 commented on src/algorithms/options/descriptions.h
> -                                    "against approximate FDs";
После прогона clang-format`а. Нормально, что так всё съехало?

2023-03-10 17:14 UTC, polyntsov commented on src/algorithms/options/descriptions.h
> -                                    "against approximate FDs";
Не знаю, что ему не понравилось в предыдущем варианте, но вообще фортматировать надо только дифф, чтобы старый код не задевался

2023-03-10 17:15 UTC, Sched71 commented on src/algorithms/ac_algorithm.cpp
> +        InvokeBinop(l, r, res.get());
Еще есть один вариант. У меня хранятся все AC, по которым строились промежутки, и если есть AC с индексом `i`, то пропускаем итерацию. Но я не знаю, лучше ли это, чем просто заново подряд всё складывать/вычитать/...

2023-03-10 17:16 UTC, Sched71 commented on src/algorithms/options/descriptions.h
> -                                    "against approximate FDs";
Ох, хорошо..

2023-03-11 15:08 UTC, polyntsov requested changes
Нужно описание к классу `ACAlgorithm`, достаточно подробное, чтобы из него можно было понять, что мы вообще тут ищем, с ссылкой на статью для further reading. Сразу отсылать к статье людей, желающих разобаться, что этот алгоритм вообще майнит - жестоко :)
Описание и про ranges, и про constraints, и про exceptions. Потому что я сейчас вообще не понимаю, какую функциональность этот код должен добавлять (да и не помню, что за constraints вообще).
Примерно то, что про exceptions написано в описании пра, но в коде и возможно в коммит месседжах (оставлять важные описания только в ревью туле вообще довольно плохая идея).
И ещё, коммиты должны соответствовать стайлгайду оформления, о них есть в [вики](https://github.com/Mstrutov/Desbordante/wiki/Development).

2023-03-11 18:22 UTC, Sched71 commented on src/model/ac.h
> +            return false;
> 



> Нужно описание к классу `ACAlgorithm`, достаточно подробное, чтобы из него можно было понять, что мы вообще тут ищем, с ссылкой на статью для further reading. Сразу отсылать к статье людей, желающих разобаться, что этот алгоритм вообще майнит - жестоко :) Описание и про ranges, и про constraints, и про exceptions. Потому что я сейчас вообще не понимаю, какую функциональность этот код должен добавлять (да и не помню, что за constraints вообще). Примерно то, что про exceptions написано в описании пра, но в коде и возможно в коммит месседжах (оставлять важные описания только в ревью туле вообще довольно плохая идея). И ещё, коммиты должны соответствовать стайлгайду оформления, о них есть в [вики](https://github.com/Mstrutov/Desbordante/wiki/Development).

То есть накидать исчерпывающих описаний комментами в заголовниках к перечисленному? К функциям никаким не надо? Как вообще это всё по-хорошему делается...

2023-03-11 18:24 UTC, Sched71 commented
> Нужно описание к классу `ACAlgorithm`, достаточно подробное, чтобы из него можно было понять, что мы вообще тут ищем, с ссылкой на статью для further reading. Сразу отсылать к статье людей, желающих разобаться, что этот алгоритм вообще майнит - жестоко :) Описание и про ranges, и про constraints, и про exceptions. Потому что я сейчас вообще не понимаю, какую функциональность этот код должен добавлять (да и не помню, что за constraints вообще). Примерно то, что про exceptions написано в описании пра, но в коде и возможно в коммит месседжах (оставлять важные описания только в ревью туле вообще довольно плохая идея). И ещё, коммиты должны соответствовать стайлгайду оформления, о них есть в [вики](https://github.com/Mstrutov/Desbordante/wiki/Development).

То есть накидать исчерпывающих описаний комментами в заголовниках к перечисленному? К функциям никаким не надо? Как вообще это всё по-хорошему делается...

2023-03-11 23:16 UTC, polyntsov commented
> То есть накидать исчерпывающих описаний комментами в заголовниках к перечисленному? К функциям никаким не надо? Как вообще это всё по-хорошему делается...
Сначала прочитать [часть про комментарии](https://google.github.io/styleguide/cppguide.html#Comments) в гугл стайл гайде. Отвечая на вопрос -- думаю, будет достаточно описания к классу, что он вообще майнит (включая определения algebraic constraints и тд) и какие опции на майнинг влияют. К функциям (особенно публичным) можно написать комментарии объясняющие, что они возвращают, если это не очевидно. Например, для `GetACExceptions()` это очевидно, если описание того, что такое `ACException` будет в описании к классу, а вот для `ReconstructRangesByColumns` - не особо очевидно (ну или это потому что я не знаю, что такое ranges)

2023-03-14 17:33 UTC, Sched71 commented on src/model/ac.h
> +            return false;
Позор мне

2023-03-30 18:05 UTC, polyntsov requested changes
`ACAlgorithm` становится слишком большим. Там есть сам алгоритм поиска ac, алгоритм поиска ranges, алгоритм поиска exceptions. Три эти алгоритма довольно слабо связаны между собой и кажется, что станет гораздо читабельнее, если в `ACAlgorithm` оставить только алгоритм поиска ac, а остальное вынести в условные `RangesFinder` и `ACExceptionsFinder`, которые будут вызываться из `ACAlgorithm`. В них же будет инкапсулирована вся нужная им логика (то есть приватные функции, которые нужны *только* для поиска чего-то конкретного, как, например, `CollectColumnPairExceptions` и `AddException`). А-то получается, что есть какие-то наборы приватных функций, которые реализуют конкретный кусок функциональности и "локальны" для него, что [не очень хорошо](https://en.wikipedia.org/wiki/Cohesion_(computer_science)).
А ещё не стоит объединять в один коммит и переименование чего-либо в старом коде, и добавление комментариев к старому коду, и добавление новой функциональности, ревьюить трудно :)
Да и история не очень получится

2023-03-31 06:39 UTC, Sched71 commented on src/algorithms/ac_algorithm.cpp
> +        InvokeBinop(l, r, res.get());
На первое почему: потенциально действительно значения могут быть из разных строк, если будет правило разбиения на пары `(pairing rule)` нетривиальное. Нетривиальное разбиение выглядит как `JOIN` или `SELF JOIN`. Георгий не видит особо смысла в этом, и самому мне сложно его там найти. Так что в какой-то момент я просто начал писать всё под тривиальное разбиение на пары (как раз, когда значения из одной строки)

2023-03-31 06:40 UTC, Sched71 commented on src/algorithms/ac_algorithm.cpp
> +        InvokeBinop(l, r, res.get());
И я как-то не решаюсь открыто заявить, что тут у нас тривиальные алгебраические зависимости, потому что несолидно звучит...

2023-03-31 08:53 UTC, Sched71 commented
> `ACAlgorithm` становится слишком большим. Там есть сам алгоритм поиска ac, алгоритм поиска ranges, алгоритм поиска exceptions. Три эти алгоритма довольно слабо связаны между собой и кажется, что станет гораздо читабельнее, если в `ACAlgorithm` оставить только алгоритм поиска ac, а остальное вынести в условные `RangesFinder` и `ACExceptionsFinder`, которые будут вызываться из `ACAlgorithm`. В них же будет инкапсулирована вся нужная им логика (то есть приватные функции, которые нужны _только_ для поиска чего-то конкретного, как, например, `CollectColumnPairExceptions` и `AddException`). А-то получается, что есть какие-то наборы приватных функций, которые реализуют конкретный кусок функциональности и "локальны" для него, что [не очень хорошо]

ranges в каком-то смысле и есть AC, то есть это основная часть AC, так что не хочется их разделять. А вот `ACExceptions` да, точно стоит отделить

2023-03-31 08:59 UTC, Sched71 commented
Еще, наверное, стоит перенести ac.h из model в util?

2023-04-26 11:30 UTC, Sched71 commented
@polyntsov мне стоит пытаться разбить на несколько коммитов тот первый, который ты уже проверил?

2023-05-01 10:26 UTC, polyntsov commented
> @polyntsov мне стоит пытаться разбить на несколько коммитов тот первый, который ты уже проверял?

Ну, если это улучшит логическое разделение, то да, иначе нет

2023-05-01 10:42 UTC, polyntsov commented on src/algorithms/ac_algorithm.cpp
> +        InvokeBinop(l, r, res.get());
> И я как-то не решаюсь открыто заявить, что тут у нас тривиальные алгебраические зависимости, потому что несолидно звучит...

Ну в комментариях к коду это всё же надо явно обозначить, потому что иначе они коду просто не соответсвуют и это вызывает вопросы

2023-05-01 11:33 UTC, polyntsov requested changes

2023-05-01 11:33 UTC, polyntsov commented on src/algorithms/ac_exception_finder.cpp
> +void ACExceptionFinder::AddException(size_t row_i, std::pair<size_t, size_t> col_pair) {
```suggestion
void ACExceptionFinder::AddException(size_t row_i, std::pair<size_t, size_t> const& col_pair) {
```

2023-05-01 11:33 UTC, polyntsov commented on tests/test_ac_algorithm.cpp
>  void AssertRanges(std::vector<std::string>& expected_ranges,
`static` или анонимный неймспейс

2023-05-01 11:33 UTC, polyntsov commented on tests/test_ac_algorithm.cpp
> +void AssertACExceptions(
`static` или анонимный неймспейс

2023-05-01 11:33 UTC, polyntsov commented on tests/test_ac_algorithm.cpp
> +        std::vector<algos::ACExceptionFinder::ACException> const& actual_ACexceptions) {
```suggestion
        std::vector<algos::ACExceptionFinder::ACException>& expected_ac_exceptions,
        std::vector<algos::ACExceptionFinder::ACException> const& actual_ac_exceptions) {
```

2023-05-01 11:33 UTC, polyntsov commented on src/algorithms/ac_exception_finder.h
> +    };
Не должно определятся в этом классе. Этот класс часть имплементации `ACAlgorithm`, вынесенная в отдельное место для лучшего разделения логики. С точки зрения интерфейса, `ACException` не должен быть частью `ACExceptionFinder` (и пользователь вообще не должен знать про существование этого класса)

2023-05-01 11:33 UTC, polyntsov commented on src/algorithms/algebraic_constraints/ac.h
А почему? Все классы, которые представляют собой описание сущностей, которые являются результатом работы алгоритма, должны лежать в model в отдельном от самого алгоритма месте. Это позволяет сделать логическое разделение и добавляет возможность переиспользования этих классов в других алгоритмах, которые ищут тот же примитив.

2023-05-01 11:56 UTC, Sched71 commented on src/algorithms/algebraic_constraints/ac.h
У нас в Вики просто вот так написано "model -- структуры данных для базового представления таблицы". Видимо, я просто не понимаю, что такое базовое представление таблицы

2023-05-01 12:01 UTC, polyntsov commented on src/algorithms/algebraic_constraints/ac.h
В вики просто сильно устаревшая информация. Сейчас в model лежат классы всех примитивов и думаю туда и стоит добавлять новые, потом сделаем это лучше в #174

2023-05-01 12:07 UTC, Sched71 commented on src/algorithms/algebraic_constraints/ac.h
У ребят там еще много директорий прямо в '/algorithms'. По какому принципу нужно файлы от алгоритма так хранить?

2023-05-01 12:09 UTC, polyntsov commented on src/algorithms/algebraic_constraints/ac.h
Сейчас однозначно правильного решения/договоренности нет и оно придет с мержем #174. Думаю, лучший вариант -- сделать папку с названием твоего алгоритма (либо класса алгоритмов, если такое разделение есть), а в неё уже положить все файлы, которые нужны для его имплементации.

2023-05-06 13:36 UTC, polyntsov commented
Кстати, а на то, что `ACPairs` считаются правильно тестов ведь нет? Надо сделать, если нет.

2023-05-06 13:37 UTC, polyntsov approved these changes

2023-05-07 08:09 UTC, Sched71 commented
> Кстати, а на то, что `ACPairs` считаются правильно тестов ведь нет? Надо сделать, если нет.

Напрямую нет. Просто правильно по считанные `ranges_` значит, что и пары верные. 
Пары ведь получаются просто операцией между двумя элементами из одной строки, больше там никаких  действий для их появления не происходит

2023-05-07 13:35 UTC, merged