Add statistic-part2
Mstrutov/Desbordante pull request #193
Opened 2023-03-13 23:44 UTC by xJoskiy

Implemented num_zeros, num_negatives and sum_of_squares
statistics. Also added corresponding get methods and tests
for each.

2023-03-18 20:18 UTC, polyntsov requested changes

2023-03-18 20:18 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +    bool isDouble = col.GetTypeId() == +mo::TypeId::kDouble;
Всю эту логику, которая преобразует `int` в значение нужного типа (`IntType` или `DoubleType`) можно вынести в отдельную функцию, чтобы не копировать её везде. Да и в общем выглядит полезно для подсчета статистик.

2023-03-18 20:18 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +    mo::DoubleType().Power(res, 1 / (long double)this->NumberOfValues(index), res);
Объект `DoubleType` уже ведь создан выше

2023-03-18 20:18 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +    res = double_type.MakeFrom(temp, type);
`MakeFrom` - статическая функция, стоит вызывать её через обычный синтаксис, чтобы сразу было видно, что она не зависит от конкретного объекта: `DoubleType::MakeFrom(temp, type)`.

2023-03-18 20:18 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +Statistic DataStats::GetNumberOfNegatives(size_t index) const {
Эта функция отличается от `GetNumberOfZeros` одной строчкой в цикле (312), стоит всю общую логику вынести в отдельное место, чтобы избежать копирования кода. Сделать отдельную функцию, которая будет возвращать количество значений в колонке, для которых верен конкретный предикат, переданный ей как параметр. А в этих функциях вызывать её и передавать ей в качестве предиката нужную проверку

2023-03-18 20:18 UTC, polyntsov commented on tests/test_data_stats.cpp
> +    auto stats_ptr = MakeStatPrimitive("TestMetric.csv");
Имя повторяющегося датасета стоит вынести в отдельную переменную, чтобы если датасет переименуют, то исправлять пришлось только одно вхождение, а не n

2023-03-20 16:00 UTC, xJoskiy commented on tests/input_data/TestNumberOfZeros.csv
В метриках я не нашёл double нулей, да и вообще ни в каких других датасетах

2023-03-24 18:00 UTC, xJoskiy commented on src/algorithms/statistics/data_stats.cpp
> +    bool isDouble = col.GetTypeId() == +mo::TypeId::kDouble;
А где и куда лучше будет вынести эту логику? Как метод класса оно со статистиками не особо вяжется, как дружественную объявить?

2023-03-30 14:10 UTC, polyntsov requested changes
В длинных функциях стоит логически связанные блоки кода разделать пустыми строчками, повысится читаемость :)

2023-03-30 14:10 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +Statistic DataStats::GetMAD(size_t index) const {
По-моему эта функция считает что-то другое, а не Median Absolute Deviation. Она берёт *среднее*, не медиану, ищет разность этого среднего и значений, а дальше ищет опять же *среднее* (вместо медианы) посчитанных разностей

2023-03-30 14:10 UTC, polyntsov commented on src/algorithms/statistics/data_stats.h
> +    size_t CountIf(Predicate, size_t) const;
Эта функция не должна быть публичной просто логически, но и на самом деле её даже вызывать не получится снаружи из-за шаблонного параметра. Тело в хедере недоступно, а значит template substitution просто не выполнить. При этом шаблонный параметр будет всегда разный тип иметь, то есть линкер не слинкует вызов этой функции из-за type mismatch.
В общем, стоит сделать её приватной

2023-03-30 14:10 UTC, polyntsov commented on tests/test_data_stats.cpp
> +    auto test = [](const std::string &file_name, size_t &&index, bool has_header = true) {
Опять же, `rvalue` ссылка на `size_t` не нужна, просто по значению

2023-03-31 21:08 UTC, xJoskiy commented on tests/input_data/TestDataStats.csv
> +,,,5,,5,grg,901.72,134,1.
Просто там полно датасетов без переноса строки, вот я и убрал
И ещё, я спрашивал, с переносом warning'и кидает в тестах

2023-04-01 13:06 UTC, polyntsov commented on tests/input_data/TestDataStats.csv
> +,,,5,,5,grg,901.72,134,1.
> Просто там полно датасетов без переноса строки, вот я и убрал

Это проблемы старых датасетов

> И ещё, я спрашивал, с переносом warning'и кидает в тестах

Сомневаюсь, что дело в переносах. А если действительно в них, то в парсере вероятно баг

2023-04-12 16:43 UTC, xJoskiy commented on src/algorithms/statistics/data_stats.cpp
> +    auto avg = avg_stat.GetData();
Да, но там все тесты так написаны, я решил не изменять традициям

2023-04-12 21:43 UTC, xJoskiy commented on tests/input_data/TestDataStats.csv
> +,,,5,,5,grg,901.72,134,1.
Сделаю коммит с переносами, но там теперь warning`и (появляются только с переносами ¯\_(ツ)_/¯ )

2023-04-12 21:45 UTC, xJoskiy commented on src/algorithms/statistics/data_stats.cpp
> +Statistic DataStats::GetMAD(size_t index) const {
Поменяю название на MeanAbsoluteDeviation, их обе реализовывать нужно

2023-04-12 21:46 UTC, xJoskiy commented on tests/test_data_stats.cpp
> +    EXPECT_EQ(6, stats.Distinct(5));  // mixed column
Старый код вообще не трогал, странно, что он что-то поправил

2023-04-20 16:54 UTC, xJoskiy commented on tests/test_data_stats.cpp
> +        for (const auto &str : row) {
Так в том-то и дело, что ругался, я поэтому и поменял
https://github.com/Mstrutov/Desbordante/actions/runs/4694248566/jobs/8336412963

2023-04-20 17:02 UTC, polyntsov commented on tests/test_data_stats.cpp
> +        for (const auto &str : row) {
По-моему он там ругался, потому что какой-то из коммитов в эти `for` пробел добавлял перед скобкой

2023-04-23 15:21 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +    type.Div(res, num, res);
Если `type` -- это `IntType`, то деление тут целочисленное, мы точно хотим среднее так считать?

2023-04-23 15:31 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +    const auto& all_stats_ = GetAllStats();
Лишняя строчка

2023-04-23 15:33 UTC, xJoskiy commented on src/algorithms/statistics/data_stats.cpp
> +    type.Div(res, num, res);
Да, я только когда с медианным значением стал делать, заметил, что так не надо
Добавлю попозже исправленную версию

2023-04-23 15:38 UTC, xJoskiy commented on src/algorithms/statistics/data_stats.cpp
> +    type.Div(res, num, res);
И так же, если avarage/median типа `DoubleType`, то нужно все слагаемые приводить к `DoubleType`

2023-04-23 16:33 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +    type.Div(res, num, res);
`GetAvg` вроде всегда `DoubleType` возвращает, кстати. Передавать его в `IntType::Sub` -- UB

2023-04-23 16:38 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +    type.Div(res, num, res);
Это, кстати, проблема, что такое никак не проверяется в рантайме, хм

2023-04-28 21:12 UTC, polyntsov approved these changes

2023-04-28 21:12 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +Statistic DataStats::BaseZerosNegs(size_t index, mo::CompareResult res) const {
nit: Не очень хорошее название для функции. Она конечно соотвествует описанию "Base method for number of negatives and number of zeros statistics", но Base -- это слишком общё и означать в целом очень многое может, думаю, можно придумать более конкретное название, что-то вроде `CountIfInBinaryRelationWithZero`. 
Просто на будущее: то, что одная функция логически отделима и переиспользуются из двух других, не значит, что её стоит называть "базовой" для них (в большинстве случаев по крайней мере). Если её логика вынесена в отдельное место, то, наверное, она делает что-то логически отделимое и цельное сама по себе и без других функций, называть её и следует основываясь на этом "что-то".

2023-04-28 21:12 UTC, polyntsov commented on src/algorithms/statistics/data_stats.cpp
> +        temp = mo::DoubleType::MakeFrom(data[i], col_type);
consider: можно сделать версию `MakeFrom`, которая принимает готовый указатель и кладет туда сконвертированное, чтобы не аллоцировать память на каждой итерации, когда это на самом деле не нужно

2023-04-28 21:17 UTC, polyntsov commented on src/algorithms/statistics/statistic.h
> +            num_zeros, num_negatives, sum_of_squares, geometric_mean, MeanAD;
Раньше не заметил, но поля именуются `snake_case`, то есть тут `mean_ad`, это нужно исправить.

2023-05-02 06:55 UTC, Mstrutov commented
Сорри за мёрж коммит, его надо просто дропнуть. Настройки сбились, в следующий раз обновлю через rebase.

2023-05-04 21:36 UTC, merged