Add deduplication example
Mstrutov/Desbordante pull request #195
Opened 2023-03-22 11:41 UTC by BUYT-1

Add Python deduplication example, remove unnecessary info from typo miner example's config string.

2023-03-22 18:16 UTC, Elluran requested changes

2023-03-30 14:15 UTC, polyntsov approved these changes
Переименуй, пожалуйста, второй коммит во что-нибудь вроде "Implement deduplication demo example", а-то что такое dedupe.py не особо понятно и зачем он добавлен тоже

2023-03-30 14:15 UTC, polyntsov commented on python_bindings/examples/mine_typos.py
> -{FD_INDEX=}"""
А почему он irrelevant? @Elluran это не сломает streamlit пример?

2023-03-30 16:02 UTC, BUYT-1 commented on python_bindings/examples/mine_typos.py
> -{FD_INDEX=}"""
Это не параметр самого поиска опечаток. Ч попросил убрать поэтому.

2023-03-30 16:44 UTC, polyntsov commented on python_bindings/examples/mine_typos.py
> -{FD_INDEX=}"""
хм, окей

2023-03-31 10:07 UTC, Elluran approved these changes

2023-03-31 10:18 UTC, Elluran commented on python_bindings/examples/mine_typos.py
> -{FD_INDEX=}"""
@polyntsov норм

2023-03-31 10:44 UTC, merged