Simplify configuration
Mstrutov/Desbordante pull request #196
Opened 2023-03-28 15:43 UTC by BUYT-1

Make option creation less verbose, separate types from options, clean up TypoMiner error check, add header with names and descriptions, simplify option-related classes, rewrite configuration accordingly, simplify option value type.

2023-04-03 13:58 UTC, polyntsov requested changes
И напиши, пожалуйста, комментарии к хотя бы основным классам вроде `CommonOptionFactory` и `Option`, чтобы было понятно, как их использовать

2023-04-03 13:58 UTC, polyntsov commented on src/algorithms/options/factory.h
> +    [[nodiscard]] Option<T> operator()(T *value_ptr) const {
Думаю, лучше сделать это методом с каким-нибудь названием типа `Build`. Странно, что фабрика -- callable объект

2023-04-03 13:58 UTC, polyntsov commented on src/algorithms/options/option.h
> +        : Option(value_ptr, name, description, [default_value]() { return default_value; }) {}
nit: `[default_value = std::move(default_value)]`

2023-04-03 13:58 UTC, polyntsov commented on src/algorithms/fastfds.cpp
> +    MakeOptionsAvailable({config::MaxLhsOpt.GetName(), config::ThreadNumberOpt.GetName()});
Optional: `MakeOptionsAvailable` часто вызывается для уже созданных опций и приходится у них вызывать явно `.GetName()`, можно сделать перегрузку, которая принимает `std::vector<IOption const*>` и уже внутри себя вызывает `MakeOptionsAvailable()` от имён. Уменьшит такое minor копирование кода

2023-04-04 12:31 UTC, BUYT-1 commented on src/algorithms/fastfds.cpp
> +    MakeOptionsAvailable({config::MaxLhsOpt.GetName(), config::ThreadNumberOpt.GetName()});
Решу позже. Можно в `RegisterOption` это указывать

2023-04-06 08:46 UTC, BUYT-1 commented on src/algorithms/fastfds.cpp
> +    MakeOptionsAvailable({config::MaxLhsOpt.GetName(), config::ThreadNumberOpt.GetName()});
Пофиксил в #200

2023-04-06 16:46 UTC, BUYT-1 commented
Никак не могу решить, как лучше писать типы параметров в лямбдах из `RegisterOptions`: `auto`, `decltype(поле)` или явно.

2023-04-08 12:16 UTC, polyntsov requested changes

2023-04-08 12:16 UTC, polyntsov commented on src/algorithms/options/error/option.cpp
> +        kError, kDError, 0.01, {}, [](ErrorType error) {
а почему 0.01 значение по умолчанию, а не 0?

2023-04-08 12:16 UTC, polyntsov commented on src/algorithms/options/option.h
> +    DefaultFunc const default_func_;
Не уверен, что стоит делать поля константными. Странно получается, что объект опции неперемещаем (перемещающего operator= нет, а конструктор при этом есть и ведёт себя как копирующий), так быть не должно. Опцию вполне стоит сделать и копируемой, и перемещаемой

2023-04-08 12:16 UTC, polyntsov commented on src/algorithms/options/option.h
> +    *value_ptr_ = converted_value;
nit: `std::move(converted_value)`

2023-04-08 12:16 UTC, polyntsov commented on src/algorithms/options/option.h
> +std::vector<std::string_view> Option<T>::Set(boost::any value) {
Кажется, что тут тоже стоит сделать `boost::any const& value)`

2023-04-08 21:56 UTC, BUYT-1 commented on src/algorithms/options/error/option.cpp
> +        kError, kDError, 0.01, {}, [](ErrorType error) {
В `src/configuration.h` 0.01 было, а в `main.cpp` 0.0. Сейчас поменяю

2023-04-08 21:58 UTC, BUYT-1 commented on src/algorithms/options/option.h
> +    *value_ptr_ = converted_value;
Нет, оно потом используется ниже

2023-04-08 22:08 UTC, BUYT-1 commented on src/algorithms/options/option.h
> +    *value_ptr_ = converted_value;
Но это можно поменять

2023-04-09 13:31 UTC, polyntsov commented on src/algorithms/options/error/option.cpp
> +        kError, kDError, 0.01, {}, [](ErrorType error) {
На самом деле кажется, что приемлемое значение по умолчанию сильно зависит от конкретного алгоритма. Для `TypoMiner` оно должно быть ненулевым по идее, для `Pyro` скорее нулевым. Возможно, стоит не указывать вообще никакое тут?

2023-04-09 16:25 UTC, BUYT-1 commented on src/algorithms/options/error/option.cpp
> +        kError, kDError, 0.01, {}, [](ErrorType error) {
В TypoMiner это не является опцией, он её только "перехватывает" и проверяет дополнительно.

2023-04-09 16:29 UTC, BUYT-1 commented on src/algorithms/options/error/option.cpp
> +        kError, kDError, 0.01, {}, [](ErrorType error) {
Т.е. надо думать, что здесь должен быть ноль всё-таки.

2023-04-09 18:23 UTC, polyntsov commented on src/algorithms/options/error/option.cpp
> +        kError, kDError, 0.01, {}, [](ErrorType error) {
Хм, да, наверное. Но всё же кажется, что в будущем могут появится алгоритмы, которым 0 не подходит, но пока оставляем так.

2023-04-09 18:23 UTC, polyntsov approved these changes

2023-04-09 18:23 UTC, merged