Rewrite bindings
Mstrutov/Desbordante pull request #197
Opened 2023-03-29 21:06 UTC by BUYT-1

Ignore irrelevant options in `fit` and `execute` instead of erroring out. Rename `GetResults` methods. Add bases for all algorithm classes. Add new methods for REPL-style scripts. Handle `pd.Dataframe`'s nulls. Add a special dataframe case that allows to read faster. Reduce macro usage.

2023-04-23 14:41 UTC, polyntsov requested changes
nit: commit names:
"[Use templated variables in PyToAny](https://github.com/Mstrutov/Desbordante/pull/197/commits/c0c5441f9e9b0bddc09e5a836f70294010049883)" -> "Use template variables in PyToAny"
"[Rewrite PandasReader](https://github.com/Mstrutov/Desbordante/pull/197/commits/f379409a57a9dfddc6bc4ee1cf6d32768dd02282)" -- описание коммита хорошее, но из названия ничего не понять кроме того, что меняется PandasReader
"[Rewrite PyFD](https://github.com/Mstrutov/Desbordante/pull/197/commits/21a3bca5d214ed23a72fcf1681fc2154e405cfca)" -- то же не понять по названию, что коммит делает, кроме того, что как-то меняет PyFD

2023-04-23 14:41 UTC, polyntsov commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
Этот класс выглядит слегка излишним, он ведь совсем ничего не делает кроме каста к конкретному типу, сделать `PyAlgorithmBase` шаблонным с одним параметром `AlgorithmType` не лучше? Или оставить только внешнюю функцию `GetAlgorithm`. А-то добавлять ещё один класс в иерархию насследования, который при этом не расширяет внешний интерфейс, ради одной функции не выглядит правильным

2023-04-23 14:41 UTC, polyntsov commented on python_bindings/py_to_any.cpp
> +        }};
в анонимный неймспейс или `static`

2023-04-24 08:50 UTC, BUYT-1 commented on python_bindings/pandas_reader.cpp
> +            strings.emplace_back("NULL");
`pandas` представляет нуллы как `float('nan')`

2023-04-24 10:08 UTC, BUYT-1 commented on python_bindings/get_py_type.cpp
> +    // statically is unpredictable and can lead to errors.
Написал более точно

2023-04-24 11:53 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
В питоне хотелось бы иметь класс `Algorithm` и классы для типов алгоритмов типа `FdAlgorithm`, чтобы можно было делать проверку типа с помощью `isinstance(obj, desb.FdAlgorithm)`. То есть нужно с помощью `pybind11::class_` зарегистрировать этот класс, а затем указать его среди шаблонных параметров классов алгоритмов. Если сделать `PyAlgorithmBase` шаблонным, т.е. как раньше было, такого сделать не получится.

> сделать `PyAlgorithmBase` шаблонным с одним параметром `AlgorithmType` не лучше

2023-04-24 13:53 UTC, polyntsov commented on python_bindings/pandas_reader.cpp
> +            strings.emplace_back("NULL");
Только нуллы и ничего больше? Если так, то это нужно отбразить комментарием в коде, потому что думаю у любого человека читающего этот код такой вопрос возникнет

2023-04-24 13:59 UTC, polyntsov commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
>  чтобы можно было делать проверку типа с помощью `isinstance(obj, desb.FdAlgorithm)`

а когда это может быть полезно?
Я всё же не очень понимаю. Возьмем `PyFDAlgorithm`:
```cpp
class PyFdAlgorithmBase : public PyAlgorithmBase { /* ... */ };

template <typename T>
class PyFDAlgorithm : public PyAlgorithm<T, PyFdAlgorithmBase> {};
```
Какую роль здесь выполняет `PyAlgorithm`?

2023-04-24 19:02 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
> а когда это может быть полезно?

Как вариант, функция, параметризуемая алгоритмом. Т.к. это питон, то в такой функции нужно проверить, является ли переданный объект алгоритмом или даже конкретно ФЗ алгоритмом.

Вообще всё работает вот так: в базе `PyAlgorithmBase` находятся функции, которые используют все алгоритмы (`Fit`, `Execute`), конструктор у неё -- это `unique_ptr` на алгоритм. А `PyAlgorithm` создаёт сам алгоритм, который является шаблонным параметром.
Далее есть базы для алгоритмов вроде `FdAlgorithm`, в которых содержатся методы получения ответа. Для алгоритмов типа `MetricVerifier` такого нет, они наследуются напрямую от `PyAlgorithmBase`.
Базы зарегистрированы средствами `pybind11` как классы в питоне. И все питоновские прослойки для алгоритмов указывают эти базы в шаблонных параметрах как своих наследников, чем получают в питоне их методы и работающие проверки `isinstance` и `issubclass`.
Это всё в `bindings.cpp` за макросами.

Т.е. прослойке для алгоритма нужно наследование от её базы (`PyFDAlgorithmBase`) и при этом правильный тип в конструкторе (`T` в `PyAlgorithm<T, Base>`). В принципе, виртуальное наследование тоже должно сработать.

Вот то, что вообще должно работать и в этом варианте работает:
Обязательно:
* создание, `Fit`, `Execute`
* получение результатов
Желательно:
* Всякие вкусности для REPL-скриптов вроде установки параметров по одному, получение типа параметра и всё такое
* `isinstance(obj, desb.Algorithm)`
* `isinstance(obj, desb.FdAlgorithm)`
Хотелось бы:
* `issubclass(desb.Pyro, desb.FdAlgorithm)`
* `issubclass(desb.MetricVerifier, desb.Algorithm)`
Было бы хорошо:
* `issubclass(desb.FdAlgorithm, desb.Algorithm)`
Для красоты, так наследование срабатывает в обычных случаях в питоне:
```
pyro = desb.Pyro()
desb.FdAlgorithm.fit(pyro, df)
```

2023-04-24 19:56 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
Обнаружил, что в `py::init` можно передать функцию

2023-04-25 08:42 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
> Обнаружил, что в `py::init` можно передать функцию

Нет, так не получается, надо на каждый класс в питоне иметь класс в плюсах

2023-04-25 08:43 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
Итого: нужно ли делать виртуальное наследование или оставить так?

2023-04-28 21:49 UTC, polyntsov commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
>  А PyAlgorithm в своём конструкторе создаёт сам алгоритм, тип которого является шаблонным параметром AlgorithmType.

А мы не можем это делать в `PyFDAlgorithm`? Я просто всё ещё не понимаю, какую полезную роль выполняет `PyAlgorithm`.

2023-04-29 09:50 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
Нет, у нас же есть алгоритмы, которые не FD

2023-04-29 10:25 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
> какую полезную роль выполняет `PyAlgorithm`

Роль шаблона `PyAlgorithm` -- каждому классу в питоне сопоставить собственный класс в плюсах. Нам это надо, т.к. `pybind11` требует для каждого класса в питоне иметь класс плюсовый. Можно, конечно, выкинуть эту библиотеку и работать напрямую с Python API, но это тяжко.

2023-04-29 10:26 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
`GetAlgorithm` убрал, она, наверное, и правда может путать.

2023-04-29 10:41 UTC, polyntsov commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
> Роль шаблона `PyAlgorithm` -- каждому классу в питоне сопоставить собственный класс в плюсах. 

А в какой момент это происходит?

2023-04-29 12:51 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +class PyAlgorithm : public Base {
В `bindings.cpp` за макросом, `py::class` эту регистрацию выполняет.
`py::class<cls, parent>(module, "cls")`, `module` -- это объект модуля, из `PYBIND11_MODULE(desbordante, module)`

2023-04-29 19:15 UTC, polyntsov approved these changes
Well done

2023-04-29 20:14 UTC, merged