Inherit ACAlgorithm from Algorithm
Mstrutov/Desbordante pull request #209
Opened 2023-05-08 09:10 UTC by Sched71

This PR deletes pairing_rule option from ACAlgorithm, because implementation was intended only for trivial pairing rule. Also it inherits ACAlgorithm from Algorithm class

2023-05-08 19:32 UTC, BUYT-1 commented
> realization

implementation

Попался на друга переводчика.

2023-05-08 19:46 UTC, BUYT-1 commented
src/algorithms/legacy_*.h файлы надо ещё убрать.

2023-05-08 19:49 UTC, Sched71 commented
> > realization
> 
> implementation
> 
> Попался на друга переводчика.

Неправда, сам писал!!!

2023-05-09 13:01 UTC, BUYT-1 commented
> > > realization
> > 
> > 
> > implementation
> > Попался на друга переводчика.
> 
> Неправда, сам писал!!!

Потому и попался)
![image](https://github.com/Mstrutov/Desbordante/assets/59949541/336a826c-c42e-4cf1-8527-75cfb2a476a6)

2023-05-17 14:54 UTC, polyntsov requested changes
Хорошее решенее с `BETTER_ENUM`.
Не уверен только, что стоит удалять `pairing_rule`. Кажется, в будущем вполне может добавиться другое. Хотя возможно когда добавится, тогда и `pairing_rule` добавят

2023-05-17 14:54 UTC, polyntsov commented on src/algorithms/options/descriptions.h
> +        "probability, the fraction of exceptional records that"
```suggestion
        "probability, the fraction of exceptional records that "
```

2023-05-17 14:54 UTC, polyntsov commented on src/algorithms/algebraic_constraints/ac_algorithm.h
> +#include <enum.h>
Это библиотечный хедер, он должен быть включен ниже стандартных и выше локальных проекта

2023-05-17 17:49 UTC, vs9h commented on src/algorithms/algebraic_constraints/bin_operation_enum.h
> +BETTER_ENUM(Binop, char, Plus = '+', Minus = '-', Multiplication = '*', Division = '/');
nit: здесь идёт некоторое смешивание языка "плюс, минус, умножение и деление". Кажется, что в таком случае должно быть "сложение, вычитание, умножение и деление"

2023-05-18 06:13 UTC, BUYT-1 commented
В описании тоже `Primitive` ещё

2023-06-01 06:37 UTC, BUYT-1 commented
Название коммита: "Inherit ACAlgorithm from Primitive" -> Inherit ACAlgorithm from Algorithm"

2023-06-06 10:22 UTC, BUYT-1 commented
Ещё надо добавить твой алгоритм в `src/algorithms/create_algorithm.h`

2023-06-19 13:44 UTC, polyntsov commented on src/util/config/descriptions.h
> +constexpr auto kDBinaryOperation = "one of available operations: /, *, +, - ";
```suggestion
constexpr auto kDBinaryOperation = "one of available operations: /, *, +, -";
```

2023-06-19 14:49 UTC, polyntsov approved these changes

2023-06-19 14:49 UTC, merged