Miscellaneous config fixups
Mstrutov/Desbordante pull request #214
Opened 2023-05-19 14:13 UTC by BUYT-1

Move config to util, add `ConfigureFromFunction`, pipeline fixes.

2023-05-19 19:25 UTC, polyntsov requested changes

2023-05-19 19:25 UTC, polyntsov commented on src/util/config/descriptions.h
> +extern const char* const kDData;
Не понимаю логику этого изменения. Два файла на описания (или имена) опций выглядит как перебор

2023-05-19 19:25 UTC, polyntsov commented on src/util/config/new_options_shorthands.h
> +#define NEW_OPTIONS_SHORTHANDS                  \
Не нравится макрос ради такого сокращения кода. Не проще в нужных функциях `using namespace util::config` писать? Они довольно короткие в большинстве своем

2023-05-19 19:25 UTC, polyntsov commented on src/algorithms/typo_miner.cpp
> +        return static_cast<bool>(TrySetOption(option_name, util::config::ErrorType{0.0}, value));
Кажется, что `TrySetOption(option_name, util::config::ErrorType{0.0}, value) != 0` читабельнее.

2023-05-19 19:25 UTC, polyntsov commented on src/algorithms/typo_miner.cpp
> +        return static_cast<bool>(TrySetOption(option_name, util::config::ErrorType{0.0}, value));
Сейчас посмотрел на имплементацию `TrySetOption` (как раз чтобы понять, что она возвращает и почему возвращаемое значение кастится к `bool`) и понял, что мы там используем исключения для control flow, что не очень хорошо. Сделать бы у `SetOption` возвращаемое значение, которое показывало бы, установилась опция или нет и чтобы можно было как-нибудь контролировать должна ли функция кидать исключение в случае плохого аргумента

2023-05-19 19:33 UTC, BUYT-1 commented on src/algorithms/algo_factory.h
> +                           std::function<boost::any(std::string_view)> const& get_value);
> nit: Думаю, стоит сделать `get_value` шаблонным параметром вместо `std::function`. Тут нет никаких особых причин использовать `std::function`

Можно подробнее? Почему нужны какие-то дополнительные причины, чтобы использовать `std::function` для передачи функции здесь?

2023-05-19 19:55 UTC, BUYT-1 commented on src/algorithms/algorithm.cpp
> +    bool ext_opt_set = SetExternalOption(option_name, value);
> почему она называется `External`

Опцию, которая относится к алгоритмам, используемыми пайплайном, я называю "внешней". "Внешней" она называется из-за #200, там конфигурация отделена в свой класс и все опции, не относящиеся к конкретному объекту конфигурации, который выполняет `SetOption`, являются "внешними", вроде бы логично. А тут можно сказать, что они "внешние", т.к. не относятся к самому алгоритму (пайплайну).

> устанавливаться этой функцией, если ее имени нет среди `possible_options_` и не устанавливаться в другом случае

Попытаться поставить опцию надо в любом случае. `is_null_equal_null` есть как у `TypoMiner`, так и у всех FD алгоритмов, например, и с такой логикой (она как раз такая и была) надо делать выкрутасы типа выставления этой опции в `TypoMiner::LoadDataInternal`, удалением из множества нужных, и что-то там ещё. Костыльно. Поэтому тут логика такая:

* Поставил для алгоритмов в пайплайне, записал, получилось или нет.
* Если опции нет, но она поставилась раньше, всё норм. Если не поставилась, значит её нигде нет — ошибка.
* Если опция есть, то не важно, поставилась или нет.

2023-05-19 20:14 UTC, BUYT-1 commented on src/util/config/descriptions.h
> +extern const char* const kDData;
См. #205 (`src/algorithms/algorithm_with_data.h`). Там все алгоритмы используют шаблон `AlgorithmWithData`, который регистрирует опцию "data". Для этой регистрации нужны `kData` и `kDData`, которые сидят в этих заголовочниках. Но если их включить, то во всех алгоритмах транзитивно будут доступны абсолютно все названия опций, что не хорошо. Так что вместо включения заголовочников с названиями и описаниями я объявляю только нужные мне строки, а для этого надо сделать их `extern`. Может быть, имеет смысл так только для `kData` и `kDData` сделать.

2023-05-19 20:22 UTC, BUYT-1 commented on src/algorithms/typo_miner.cpp
> +        return static_cast<bool>(TrySetOption(option_name, util::config::ErrorType{0.0}, value));
Вообще я думал сделать так: [src/algorithms/options/configuration.cpp](https://github.com/Mstrutov/Desbordante/pull/200/files#diff-2a895dccfc0fddfea44046d87f71fc0eb76a19f924582f918849b2ebfa43225e), см. `Configuration::SetOption`. Т.е. я хочу выкидывать ошибки, которые кидают сами алгоритмы, если опцию установить не получилось.

2023-05-19 20:28 UTC, BUYT-1 commented on src/util/config/descriptions.h
> +extern const char* const kDData;
Пока уберу

2023-05-19 20:39 UTC, BUYT-1 commented on src/util/config/new_options_shorthands.h
> +#define NEW_OPTIONS_SHORTHANDS                  \
Посмотри на `metric_verifier.cpp`. Там если сделать `using namespace util::config`, то в каждом конструкторе `Option` придётся писать `names::k...`, `descriptions::kD...` вместо прошлого `k...`, `kD...`. К тому же если с неймспейсами `util::config::{names,descriptions}` понятно, что происходит — там только кучка констант с одним шаблоном имени, — то что может однажды появиться в `util::config` и что-нибудь сломать, я не знаю.

2023-05-20 18:39 UTC, polyntsov commented on src/algorithms/algo_factory.h
> +                           std::function<boost::any(std::string_view)> const& get_value);
Первый ответ [здесь](https://stackoverflow.com/questions/14677997/stdfunction-vs-template)

2023-05-20 18:56 UTC, polyntsov commented on src/algorithms/typo_miner.cpp
> +        return static_cast<bool>(TrySetOption(option_name, util::config::ErrorType{0.0}, value));
хм, пока не очень понимаю, как это поможет с этой проблемой, но ладно

2023-05-20 19:00 UTC, polyntsov commented on src/algorithms/algorithm.cpp
> +    bool ext_opt_set = SetExternalOption(option_name, value);
То есть по сути предполагается, что внешняя опция может быть одновременно и внешней, и невнешней? Когда у пайплайна выставляется `is_null_equal_null`, то она сразу выставляется и у самого пайплайна, и у алгоритмов, всегда в одно и то же значение?

2023-05-20 19:05 UTC, polyntsov commented on src/util/config/new_options_shorthands.h
> +#define NEW_OPTIONS_SHORTHANDS                  \
Окей, наверное, пойдет (но макросы все равно зло). Нужно тогда название более понятным сделать, вроде `USING_OPTION`.
И я бы не ставил тогда в конце `using util::config::Option` точку с запятой, чтобы её ставил использующий макрос код, а-то строчки без `;` на мой взгляд выглядят странно и привлекают к себе внимание. Но это вкусовщина в принципе

2023-05-20 19:06 UTC, BUYT-1 commented on src/algorithms/typo_miner.cpp
> +        return static_cast<bool>(TrySetOption(option_name, util::config::ErrorType{0.0}, value));
А то, что мы выкидываем ошибки для неправильных значений, само по себе не является использованием исключений для control flow

2023-05-20 19:08 UTC, BUYT-1 commented on src/algorithms/algorithm.cpp
> +    bool ext_opt_set = SetExternalOption(option_name, value);
> она сразу выставляется и у самого пайплайна, и у алгоритмов, всегда в одно и то же значение

Должно быть так, да.

2023-05-20 19:08 UTC, BUYT-1 commented on src/algorithms/algorithm.cpp
> +    bool ext_opt_set = SetExternalOption(option_name, value);
> может быть одновременно и внешней, и невнешней

Можно сказать и так

2023-05-20 19:09 UTC, polyntsov commented on src/algorithms/algorithm.cpp
> +    bool ext_opt_set = SetExternalOption(option_name, value);
Вот кажется, что существуют примеры пайплайнов, где это плохое поведение. Впрочем думаю, пока можно оставить так, а как только появится пайплайн, где нужно иначе, тогда и переделаем. Только напиши пж комменатрий поясняющий, что это задуманное поведение (что опция выставляется и там, и там, в одно и тоже значение)

2023-05-20 19:11 UTC, polyntsov commented on src/algorithms/typo_miner.cpp
> +        return static_cast<bool>(TrySetOption(option_name, util::config::ErrorType{0.0}, value));
хм, ладно. Пока (в этом пулреквесте) не стоит трогать имплементацию `TrySetOption`, думаю

2023-05-20 19:44 UTC, polyntsov approved these changes

2023-05-20 20:33 UTC, merged