Implement HyUCC
Mstrutov/Desbordante pull request #215
Opened 2023-05-20 15:57 UTC by polyntsov

This PR adds UCC discovery algorithm named HyUCC implementation and a test module for UCC mining algorithms and the HyUCC itself.
It also introduces aliases for the cluster id and for the raw/column position in the table and uses them in HyFD to make the code more readable and to ease any refactoring in the future.

2023-05-20 16:07 UTC, polyntsov commented on src/algorithms/ucc/hyucc/structures/ucc_tree.cpp
> +    if (is_new) {
> **src/algorithms/ucc/hyucc/structures/ucc_tree.cpp:8**: Loop condition is false. Execution continues on line 18
false positive: Loop condition can't be false, `assert(ucc.any())` guarantees that.

2023-05-23 16:06 UTC, Mstrutov requested changes
Красота, пару моментов посмотреть и в мёрж.

2023-05-23 21:42 UTC, polyntsov commented on src/algorithms/hycommon/validator_helpers.cpp
> +        if (cluster_id == (ClusterId)-1) {
Случайно вероятно, когда переписывал эту часть

2023-05-24 04:03 UTC, Mstrutov approved these changes

2023-05-24 13:40 UTC, merged