Pass data as option
Mstrutov/Desbordante pull request #218
Opened 2023-05-21 10:27 UTC by BUYT-1

This makes it easier to implement algorithms that accept anything other than a table.
Also fixes the code repetition problem in `PliBasedAlgorithm::LoadData`.

2023-05-21 17:13 UTC, BUYT-1 commented
Момент, когда хочется модулей 😋

2023-06-18 21:38 UTC, polyntsov requested changes
Теперь  `Algorithm::LoadData` не принимает параметров, но все еще должен быть обязательно вызван перед `Execute`, что не всегда нужно. Cтоит подумать о том, чтобы разрешить вызывать `Execute` без `LoadData` перед этим.

2023-06-18 21:38 UTC, polyntsov commented on src/algorithms/ar_algorithm.h
> -    using MinSupType = double;
а зачем?

2023-06-18 21:38 UTC, polyntsov commented on src/algorithms/aidfd/aid.cpp
> +        const std::basic_string<char>& column_name =
Думаю, тут заодно можно `std::basic_string<char>` заменить на `std::string`

2023-06-18 21:38 UTC, polyntsov commented on src/algorithms/algo_factory.h
> +boost::any GetOrEmpty(OptionMap const& options, std::string_view option_name) {
думаю, можно в `details` переместить

2023-06-18 21:38 UTC, polyntsov commented on python_bindings/py_algorithm.cpp
> +using util::config::names::kRelation;
Нужно перенести в `namespace python_bindigs`, и `void_index` тоже.

2023-06-18 21:38 UTC, polyntsov commented on python_bindings/create_dataframe_reader.cpp
> +        return std::make_shared<ArbitraryDataframeReader>(dataframe, std::move(name));
Фигурные скобки, слишком длинное тело

2023-06-18 21:38 UTC, polyntsov commented on python_bindings/py_algorithm.h
> +    void LoadData(std::string_view path, char separator, bool has_header,
Не очень ясно, зачем тут оставлять `LoadData` с параметрами, если в C++ коде мы полностью переходим к тому, что данные задаются опции и каждый тип алгоритма сам решает, как эти данные выглядят. Как-то неконсистентно получается

2023-06-19 06:15 UTC, BUYT-1 commented on src/algorithms/ucc/ucc_algorithm.cpp
> +            {util::config::RelationOpt.GetName(), util::config::EqualNullsOpt.GetName()});
Идея в том, чтобы привязать логически это имя к самой опции. Хз, может, и правда не надо.

2023-06-19 06:19 UTC, BUYT-1 commented on src/algorithms/ar_algorithm.h
> -    using MinSupType = double;
Это осталось со времени `OptionType`, сейчас оно не нужно.

2023-06-19 06:22 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +    void LoadData(std::string_view path, char separator, bool has_header,
Изначально в питоне такой интерфейс предлагали. Мне казалось, что это надо аккуратнее менять.

2023-06-19 06:38 UTC, BUYT-1 commented on src/model/column_layout_relation_data.h
> +    static std::shared_ptr<ColumnLayoutRelationData> CreateFrom(model::IDatasetStream& data_stream,
Посмотрел внимательнее — никакую. Если там `unique_ptr` то при записи в поле `relation_` вызывается конструктор у `shared_ptr`, который отбирает указатель у возвращённого `unique_ptr`, и дальше уже нормально копируется `shared_ptr`.

2023-06-19 06:58 UTC, BUYT-1 commented on src/algorithms/pli_based_fd_algorithm.cpp
>  }
Эти опции показываются пользователю. Странно было бы у пользователя запрашивать сразу готовые данные. А здесь особая ситуация, когда данные уже есть, работаем с ней по-особому.
"Альтернативным" я это назвал, потому что не знал, что тут происходит. А так тут данных либо нет, тогда надо честно выставлять все параметры, либо они есть и можно на параметры забить.

2023-06-19 07:11 UTC, BUYT-1 commented on python_bindings/get_py_type.cpp
> +    return reinterpret_cast<PyObject*>(py_type_ptr);
standard layout он быть не перестанет, потому что это сишный `struct`. А внутренним макросом пользоваться не хочется, т.к. в доках написано, что внутренние макросы могут в любой момент убрать или переименовать. Хотя конкретно с этим такое вряд ли случится.
Просто приходилось периодически видеть, как люди используют какой-нибудь макрос в glibc, а потом после апдейта их программа ломается. Не хочется наступать на эти же грабли.
Документация C-API питоновского пишет, что все функции для `PyObject*` могут использоваться и для `PyTypeObject*`, что в плюсах, в условиях использования сишных структур, соответствует C-style касту, который в контексте имеет значение `reinterpret_cast`. Могу разве что поменять на `return (PyObject*) py_type_ptr`

2023-06-19 13:09 UTC, polyntsov commented on python_bindings/get_py_type.cpp
> +    return reinterpret_cast<PyObject*>(py_type_ptr);
Если layout `PyTypeObject` фиксирован в python C-Api, то тогда все норм и можно оставить так

2023-06-21 19:19 UTC, BUYT-1 commented on python_bindings/create_dataframe_reader.cpp
> +    } catch (py::error_already_set&) {
написал коммент

2023-06-21 19:19 UTC, BUYT-1 commented on python_bindings/get_py_type.cpp
> +                 } catch (py::error_already_set&) {
написал коммент

2023-06-21 19:26 UTC, BUYT-1 commented on python_bindings/py_algorithm.h
> +    void LoadData(std::string_view path, char separator, bool has_header,
Плюс этот класс только для алгоритмов с таблицей пока что.

2023-06-23 06:11 UTC, BUYT-1 commented on src/algorithms/pli_based_fd_algorithm.cpp
>  }
Хотя чисто в теории возможно и такое провернуть, но надо будет механизм с опциями переделать.

2023-06-23 06:21 UTC, BUYT-1 commented on src/algorithms/pli_based_fd_algorithm.cpp
>  }
Есть идеи, но не в этом ПРе.

2023-06-25 20:44 UTC, polyntsov commented on src/util/config/relational_data/input_relation_type.h
> +using InputRelation = std::shared_ptr<model::IDatasetStream>;
да, согласен

2023-06-25 20:50 UTC, polyntsov commented on src/algorithms/pli_based_fd_algorithm.cpp
>  }
Ну `table` тоже показывается пользователю, но инициализируется она датафреймом/парсером, что странно в случае cli?

2023-06-25 20:59 UTC, BUYT-1 commented on src/algorithms/pli_based_fd_algorithm.cpp
>  }
> Ну `table` тоже показывается пользователю, но инициализируется она датафреймом/парсером, что странно в случае cli?

Да, наверное
Есть идея сделать отдельную стадию конфигурации для этого, и в альтернативном конструкторе её ставить, только надо понять, как это правильно сделать.
Но не в этом ПРе, тут никаких стадий формально ещё нет.

2023-06-25 22:00 UTC, polyntsov requested changes

2023-06-25 22:00 UTC, polyntsov commented on src/algorithms/pli_based_fd_algorithm.cpp
>  }
Окей. Тогда наверное временно оставим этот некрасивый `LoadDataCommon`

2023-06-25 22:00 UTC, polyntsov commented on src/algorithms/fd_algorithm.cpp
> +            }));
Кажется, что этот `assert` можно переместить в цикл ниже, что `col->GetSchema() == fds_count_per_col.front().first->GetSchema()` и оно станет читабельнее

2023-06-25 22:00 UTC, polyntsov commented on src/algorithms/cfd/cfd_discovery.cpp
> +            {util::config::TableOpt.GetName(), kEqualNulls, kCfdColumnsNumber, kCfdTuplesNumber});
Ну тут для консисентности с остальными опциями ведь `kTable` должно быть. Иначе не понимаю, какую консистентность ты имел в виду

2023-06-25 22:00 UTC, polyntsov commented on src/algorithms/ar_algorithm.cpp
> +    MakeOptionsAvailable({util::config::TableOpt.GetName(), kInputFormat});
Тут тоже `kTable`

2023-06-25 22:00 UTC, polyntsov commented on src/algorithms/aidfd/aid.cpp
> +        std::string const& column_name = input_table_->GetColumnName(static_cast<int>(i));
`const` потерял

2023-06-25 22:00 UTC, polyntsov commented on python_bindings/get_py_type.cpp
> +        // Import failed.
Думаю, если здесь точно не может быть других исключений, то лучше вставить `assert`, что исключение именное такое. Либо проверку, что исключение такое с rethrow в противном случае.

2023-06-25 22:00 UTC, polyntsov commented on python_bindings/get_py_type.cpp
> +        PyObject* df_type = py::module::import("pandas").attr("DataFrame").ptr();
Кажется, что можно `py::module::import("pandas.DataFrame")` и это будет правильнее, `pandas` целиком слишком накладно импортировать

2023-06-25 22:00 UTC, polyntsov commented on python_bindings/get_py_type.cpp
> +        // Import failed.
В других местах, где этот паттерн, то же самое

2023-06-25 22:00 UTC, polyntsov commented on python_bindings/py_algorithm.h
> +    void LoadData(std::string_view path, char separator, bool has_header,
Ну вообще кажется, что в этом классе только эти `LoadData` из специфичного для алгоритмов с таблицей. Но согласен, что изменение этого стоит отдельно делать

2023-06-25 22:00 UTC, polyntsov commented on python_bindings/py_algorithm.cpp
> +                                std::function<boost::any()> const& create_data_reader) {
nit: `std::function` -> template parameter

2023-06-25 22:00 UTC, polyntsov commented on python_bindings/get_py_type.cpp
> +py::frozenset GetPyInputTableType() {
`static` or better anonymous namespace

2023-06-25 22:03 UTC, polyntsov commented on src/algorithms/pli_based_fd_algorithm.cpp
>  }
а, ты его убрал, ну тоже норм

2023-06-25 22:17 UTC, BUYT-1 commented on src/algorithms/aidfd/aid.cpp
> +        std::string const& column_name = input_table_->GetColumnName(static_cast<int>(i));
Да нет, всё на месте. Хотя для согласованности и стоит написать `const` сначала

2023-06-25 22:21 UTC, BUYT-1 commented on python_bindings/get_py_type.cpp
> +        PyObject* df_type = py::module::import("pandas").attr("DataFrame").ptr();
> Кажется, что можно `py::module::import("pandas.DataFrame")` и это будет правильнее, `pandas` целиком слишком накладно импортировать

Не, так нельзя импортировать. Да и всё равно придётся весь модуль подгружать. А так питон кэширует эти модули.
На самом деле стоит иметь какую-то глобальную структуру, чтобы эти импорты производились при загрузке модуля, но проблему её корректного уничтожения ещё надо решить, так что потом.

2023-06-25 22:26 UTC, polyntsov commented on src/algorithms/aidfd/aid.cpp
> +        std::string const& column_name = input_table_->GetColumnName(static_cast<int>(i));
и правда на месте..

2023-06-25 22:29 UTC, polyntsov commented on python_bindings/get_py_type.cpp
> +        PyObject* df_type = py::module::import("pandas").attr("DataFrame").ptr();
видимо такое не работает на классы, ладно. Этот код просто немного странным выглядит (особенно в месте, где нам надо проверить, что объект -- это датафрем, а мы ради этого делаем `import pandas`)

2023-06-25 22:30 UTC, BUYT-1 commented on src/algorithms/ar_algorithm.cpp
> +    MakeOptionsAvailable({util::config::TableOpt.GetName(), kInputFormat});
В общем, везде предлагаешь убрать эти `GetName`?

2023-06-25 22:33 UTC, polyntsov commented on src/algorithms/ar_algorithm.cpp
> +    MakeOptionsAvailable({util::config::TableOpt.GetName(), kInputFormat});
Ну не везде, а как минимум в местах, где остальные имена опций через константу задаются. Такая неконсистентность просто странно выглядит.
А как правильнее ссылаться на имена, через константы или `GetName()`, не знаю. `GetName()` как будто чуть лучше. Но кажется важнее в пределах одной функции писать одинаково

2023-06-25 22:44 UTC, BUYT-1 commented on python_bindings/get_py_type.cpp
> +        PyObject* df_type = py::module::import("pandas").attr("DataFrame").ptr();
> видимо такое не работает на классы, ладно.

Питоновское ключевое слово `import` импортирует так только подмодули, да. Но внешний модуль всё равно всегда загружается.

> Этот код просто немного странным выглядит (особенно в месте, где нам надо проверить, что объект -- это датафрейм, а мы ради этого делаем `import pandas`)

Надо же нам как-то достать датафрейм. Особой поддержки для `pandas` у `pybind11` нет, да и не появится — сишного апи, в отличие от `numpy` у `pandas` нет, и, надо думать, не будет — `pandas` на чистом питоне написана.

2023-06-25 22:46 UTC, BUYT-1 commented on src/algorithms/ar_algorithm.cpp
> +    MakeOptionsAvailable({util::config::TableOpt.GetName(), kInputFormat});
Могу сказать, что такие ссылки на имена уйдут потом, только в `TypoMiner` останется `ErrorOpt.GetName()`

2023-06-25 23:17 UTC, polyntsov commented on src/algorithms/ar_algorithm.cpp
> +    MakeOptionsAvailable({util::config::TableOpt.GetName(), kInputFormat});
Ну тогда тут точно разница минимальная. Сделай как тебе больше нравится, но консистентно в пределах одной функции

2023-06-26 18:21 UTC, polyntsov commented on python_bindings/py_algorithm.cpp
> +                                std::function<boost::any()> const& create_data_reader) {
окей, тогда оставь как есть

2023-06-26 18:22 UTC, polyntsov commented on python_bindings/py_algorithm.cpp
> +                                std::function<boost::any()> const& create_data_reader) {
Ну либо `kTable` и `kDTable` в отдельный файл :)

2023-06-26 18:47 UTC, BUYT-1 commented on python_bindings/py_algorithm.cpp
> +                                std::function<boost::any()> const& create_data_reader) {
Внезапно понял, что функция тут на самом деле не нужна.

2023-07-01 18:34 UTC, polyntsov commented on python_bindings/py_algorithm.cpp
> +                }
Не очень понимаю логику. Если среди опций указана `kTable`, то ожидается, что в эту функцию уже передали готовый парсер? Какое тогда значение у опции `kTable`?

2023-07-01 19:02 UTC, BUYT-1 commented on python_bindings/py_algorithm.cpp
> +                }
Сейчас `PyAlgorithm` приспособлен только для табличных алгоритмов. Они все просят таблицу только на этапе загрузки данных. Для него в питоне есть две перегрузки `LoadData`, в которых таблица создаётся. Здесь предполагается, что если алгоритм попросил таблицу, то он находится на этапе загрузки данных и был вызван один из этих двух методов. Передача таблицы через `kwargs` пока не предполагается.

2023-07-01 19:38 UTC, polyntsov commented on python_bindings/py_algorithm.cpp
> +                }
Как в таком случае работает задание готового pandas dataframe через `kTable` опцию?

2023-07-01 19:56 UTC, BUYT-1 commented on python_bindings/py_algorithm.cpp
> +                }
DataFrame передаётся в соответствующую перегрузку и там конструируется {`String`,`Arbitrary`}`DataframeReader`, с которого алгоритм читает данные. Если смущает `set_option`, то это отдельная логика, там всё по-честному ставится.

2023-07-01 23:24 UTC, polyntsov approved these changes

2023-07-01 23:24 UTC, merged