Add Python bindings for ACAlgorithm
Mstrutov/Desbordante pull request #227
Opened 2023-07-03 16:05 UTC by Sched71

2023-07-06 07:49 UTC, BUYT-1 requested changes

2023-07-06 07:49 UTC, BUYT-1 commented on src/algorithms/algebraic_constraints/ranges_collection.h
> +        for (size_t i = 0; i < ranges.size(); i += 2) {
С таким циклом надо бы писать `assert(ranges.size() % 2 == 0)`

2023-07-06 07:49 UTC, BUYT-1 commented on src/algorithms/algebraic_constraints/ranges_collection.h
> +            res.push_back({col_pair.num_type->ValueToString(ranges[i]),
`emplace_back` и без фигурных скобок

2023-07-06 07:49 UTC, BUYT-1 commented on src/algorithms/algebraic_constraints/ranges_collection.h
> +        std::vector<std::pair<std::string, std::string>> res;
Можно `res.reserve(ranges.size() / 2)`

2023-07-06 07:49 UTC, BUYT-1 commented on src/algorithms/algebraic_constraints/ranges_collection.h
> +                           col_pair.num_type->ValueToString(ranges[i + 1])});
На самом деле лучше бы иметь метод в питоне, который из этих строк делает питоновский `int`. Строки здесь смотрятся максимально странно.
Делается с помощью `py::int_(py::str(...->ValueToString(...)))`

2023-07-06 08:51 UTC, Sched71 commented on python_bindings/bindings.cpp
> +    py::class_<PyRangesCollection>(module, "ACRanges")
Прокладка уже есть и работает, так что не буду её переписывать...

2023-07-06 08:55 UTC, Sched71 commented on python_bindings/py_ac_algorithm.h
> +        GetAlgorithm<algos::ACAlgorithm>(algorithm_).CollectACExceptions();
Согласен. Сбор исключений без найденных промежутков не имеет смысла. Как-то сам не додумался

2023-07-06 09:16 UTC, Sched71 commented on src/algorithms/algebraic_constraints/ranges_collection.h
> +                           col_pair.num_type->ValueToString(ranges[i + 1])});
А это в каком месте писать следует?

2023-07-06 11:35 UTC, BUYT-1 commented on src/algorithms/algebraic_constraints/ranges_collection.h
> +                           col_pair.num_type->ValueToString(ranges[i + 1])});
Метод `algos::RangesCollection::GetRanges` перенеси в питоновскую часть. Сделай функцию, которую вызываешь в initializer list для прокладки, и в ней замени то, что сейчас ValueToString на вот это (и возвращаемый тип тоже, соответственно).

2023-07-06 16:37 UTC, Sched71 commented on python_bindings/py_to_any.cpp
> +        NormalConvPair<size_t>,
Этот оказался нужен

2023-07-06 16:39 UTC, Sched71 commented on python_bindings/py_ac_ranges_collection.h
> +          ranges_(ConvertStringRanges(r_coll.GetRanges())){};
Я так и не понял до конца, что ты предлагал, поэтому сделал так

2023-07-06 18:13 UTC, BUYT-1 commented on python_bindings/py_to_any.cpp
> +        NormalConvPair<size_t>,
Всё правильно, у тебя есть опция этого типа

2023-07-06 18:18 UTC, BUYT-1 commented on python_bindings/py_ac_ranges_collection.h
> +          ranges_(ConvertStringRanges(r_coll.GetRanges())){};
Я предлагал вместо метода для создания списка в библиотечной части сделать аналогичную функцию сразу в питоновской части с той лишь разницей, что она создаёт вектор пар с нужным типом сразу же, чтобы не преобразовывать лишний раз.

2023-07-06 18:19 UTC, BUYT-1 commented on src/algorithms/algebraic_constraints/ranges_collection.h
> +        assert(ranges.size() % 2 == 0);
`#include <cassert>`

2023-07-06 19:20 UTC, BUYT-1 requested changes

2023-07-06 19:20 UTC, BUYT-1 commented on python_bindings/py_ac_ranges_collection.h
> +    using ranges = std::vector<std::pair<py::float_, py::float_>>;
Типы с заглавной буквы

2023-07-06 19:20 UTC, BUYT-1 commented on python_bindings/py_ac_algorithm.h
> +        for (auto const& c : collections) {
nit: `auto` -> `algos::RangesCollection`

auto только когда тип очевиден

2023-07-06 19:20 UTC, BUYT-1 commented on python_bindings/py_ac_ranges_collection.h
> +std::vector<std::pair<py::float_, py::float_>> ConvertStringRanges(
Актуализируй имя

2023-07-06 19:20 UTC, BUYT-1 commented on python_bindings/py_ac_ranges_collection.h
> +        std::string r_border = r_coll.col_pair.num_type->ValueToString(r_coll.ranges[i + 1]);
nit: Кажется, правильнее будет boundary, а не border, но ещё лучше эти переменные назвать как-то типа `minimum_value_string` и `maximum_value_string`.

2023-07-06 19:20 UTC, BUYT-1 commented on src/algorithms/algebraic_constraints/ranges_collection.h
> +    std::pair<size_t, size_t> GetColumnIndices() const {
Если не видишь вариантов использования этого метода вне питоновской части, то стоит перенести его туда.

2023-07-06 19:39 UTC, BUYT-1 commented on python_bindings/py_ac_ranges_collection.h
> +        std::string r_border = r_coll.col_pair.num_type->ValueToString(r_coll.ranges[i + 1]);
UPD: Если это границы интервала, то нужное слово — "endpoint"

2023-07-07 11:10 UTC, polyntsov commented on python_bindings/py_ac_algorithm.h
> +        for (auto const& c : collections) {
Ну тут вроде очевиден, определение `collections` ведь двумя строками выше

2023-07-07 11:24 UTC, BUYT-1 commented on python_bindings/py_ac_algorithm.h
> +        for (auto const& c : collections) {
Хм, мне как-то думалось, что очевидно — это нечто вроде `auto obj = std::make_unique<Type>(...)` — ситуации, когда даже если невнимательно смотреть в код, то всё будет понятно и явное объявление типа только место занимает.
А это, скорее, "надо немного подумать". Мне вот пришлось файл этот открыть, чтобы понять, какой тут тип.

2023-07-08 14:12 UTC, Sched71 commented on python_bindings/py_ac_algorithm.h
> +        for (auto const& c : collections) {
Ну если на файл смотреть, то очевидно же. А открыть его != немного подумать :disappointed:

2023-07-08 14:18 UTC, Sched71 commented on src/algorithms/algebraic_constraints/ranges_collection.h
> +    std::pair<size_t, size_t> GetColumnIndices() const {
Уберу уж его тогда совсем...

2023-07-08 20:09 UTC, BUYT-1 approved these changes

2023-07-08 20:10 UTC, BUYT-1 commented
Ты же проверял, что в питоне всё хорошо?

2023-07-08 20:12 UTC, Sched71 commented
> Ты же проверял, что в питоне всё хорошо?

Запускал, результаты нормальные выдает

2023-07-08 20:13 UTC, Sched71 commented
> > Ты же проверял, что в питоне всё хорошо?
> 
> Запускал, результаты нормальные выдает
Сейчас последний разок посмотрю, последние пару изменений не запускал

2023-07-08 20:13 UTC, BUYT-1 commented
> > Ты же проверял, что в питоне всё хорошо?
> 
> Запускал, результаты нормальные выдает

Окей. Кнопку мержа пока нажимать не буду, т.к. мне эти права дали, чтобы у меня можно было ревью запросить.
@polyntsov

2023-07-08 20:20 UTC, Sched71 commented
> > > Ты же проверял, что в питоне всё хорошо?
> > 
> > 
> > Запускал, результаты нормальные выдает
> 
> Сейчас последний разок посмотрю, последние пару изменений не запускал

Окей, все нормально, всё еще работает

2023-07-09 13:17 UTC, BUYT-1 requested changes
Слушай, отмена. Слей коммиты 33969302 и 4fa10940 с 6bba79dc, странно смотрится.
`git rebase -i main`, потом помещаешь строчки, соответствующие этим двум коммитам под последний и заменяешь pick на fixup в этих двух строчках

2023-07-09 13:21 UTC, polyntsov commented on python_bindings/py_ac_algorithm.h
> +        for (auto const& c : collections) {
Стайлгайд конечно явно не определяет значение слова "очевидно", но думаю, что имеется в виду, что код будет понятен человеку не знакомому с кодовой базой (но знакомому с языком, конечно). Здесь чтобы понять какой тип будет у `c` про десборданте знать совсем ничего не надо, только посмотреть на три строки выше :)

2023-07-09 13:57 UTC, BUYT-1 requested changes

2023-07-09 13:57 UTC, BUYT-1 commented on src/algorithms/algebraic_constraints/ranges_collection.h
> +#include "model/types/type.h"
Не нужно

2023-07-09 14:14 UTC, BUYT-1 approved these changes

2023-07-11 16:28 UTC, polyntsov commented on python_bindings/py_ac_ranges_collection.h
> +        // TODO: chage type conversion method, when better one will be implemented
"chage" -> "change", "will be implemented" -> "is implemented", ну и запятая лишняя :)

2023-07-11 16:29 UTC, BUYT-1 commented on python_bindings/py_ac_ranges_collection.h
> +        // TODO: chage type conversion method, when better one will be implemented
```suggestion
        // TODO: change this once a proper conversion mechanism from `model::INumericType` is implemented
```
Или как-то так.

2023-07-11 17:05 UTC, polyntsov commented on python_bindings/py_ac_ranges_collection.h
> +namespace py = pybind11;
стайлгайд запрещает элиасы (в том числе для неймпейсов) в api (хедеры) помещать

2023-07-11 17:14 UTC, polyntsov approved these changes

2023-07-11 18:19 UTC, merged