Python testing
Mstrutov/Desbordante pull request #229
Opened 2023-07-11 17:53 UTC by BUYT-1

`get_option_type` changes according to feedback from another dev
tests for python bindings

2023-07-11 18:26 UTC, BUYT-1 commented
Здесь нужны какие-то серьёзные тесты, или как сейчас -- собирается и хорошо? И как сделать этот workflow required?

2023-07-16 17:34 UTC, polyntsov commented
> Здесь нужны какие-то серьёзные тесты, или как сейчас -- собирается и хорошо? И как сделать этот workflow required?

Ну вообще хотелось бы каких-то тестов с проверкой того, что все майнится верно. Но для начала наверное и такого хватит, а потом допишем сами тесты. Workflow required может только Максим сделать и видимо только после того, как этот pr вмержится

2023-07-23 22:36 UTC, polyntsov requested changes
Хорошая работа, но опять несколько логически несвязанных изменений в одном пулреквесте, нехорошо

2023-07-23 22:36 UTC, polyntsov commented on src/CMakeLists.txt
> +target_link_libraries(${BINARY}_run PRIVATE ${CMAKE_PROJECT_NAME}_lib easyloggingpp)
интересно, почему можно удалить `Threads::Threads`, которую мы используем

2023-07-23 22:36 UTC, polyntsov commented on .github/workflows/python.yml
> +name: Python
копипаста из других воркфлоу, общие части стоит вынести в отдельное место и переиспользовать через [include](https://docs.gitlab.com/ee/ci/yaml/#include)

2023-07-23 22:36 UTC, polyntsov commented on python_bindings/testing_script.py
> +              and issubclass(obj, desb.Algorithm) and not obj.__subclasses__()]
какая-то магия, не понимаю.

2023-07-23 22:36 UTC, polyntsov commented on python_bindings/testing_script.py
> +    print(algorithm_type.__name__, algorithm.get_fds())
а мы разве не определяем `__str__` у типа, зачем тут `__name__`?

2023-07-23 22:36 UTC, polyntsov commented on python_bindings/py_to_any.cpp
> +                      << '"';
nit: на мой взгляд `stringstream` оверкилл тут и проще написать приведение к `std::string` и конкатенацию, но не настаиваю

2023-07-23 22:36 UTC, polyntsov commented on python_bindings/py_to_any.cpp
> +        LOG(INFO) << "Cast failed on option " << option_name << ": " << e.what();
А почему тут уровень `INFO`? Как будто бы пользователь и так увидит сообщение исключения, зачем ему еще этот принтаут

2023-07-23 22:36 UTC, polyntsov commented on python_bindings/py_table.h
> +// Placeholder type for denoting a Python object that can be converted to `util::config::InputTable`
а как это работает?

2023-07-27 07:52 UTC, Mstrutov reviewed
I do not have anything to add to @polyntsov comments

2023-07-31 17:01 UTC, BUYT-1 commented on .github/workflows/python.yml
> +name: Python
Не понял, почему тут gitlab. github же по-другому работает.

2023-07-31 23:22 UTC, polyntsov commented on .github/workflows/python.yml
> +name: Python
не прав, почему-то гугл выдает это третьей страницей в выдаче, когда я ищу для гитхаба. Возможно это намек на то, что гитхаб так не умеет. Ну или я запрос плохо составил

2023-07-31 23:24 UTC, polyntsov commented on .github/workflows/python.yml
> +name: Python
Видимо нам нужно что-то такое https://stackoverflow.com/questions/64055230/nested-templates-calling-a-yaml-file-from-another-yaml-file-in-github-actions

2023-08-07 15:40 UTC, BUYT-1 commented on python_bindings/testing_script.py
> +              and issubclass(obj, desb.Algorithm) and not obj.__subclasses__()]
Это собирает все типы алгоритмов из библиотеки

2023-08-07 15:41 UTC, BUYT-1 commented on python_bindings/testing_script.py
> +    print(algorithm_type.__name__, algorithm.get_fds())
Не понял. У объекта типа мы ничего не определяем, `__name__` - это просто его имя.

2023-08-10 19:03 UTC, polyntsov commented on python_bindings/testing_script.py
А почему такое название? Просто `tests` как будто лучше будет, `script` избыточным выглядит

2023-08-12 12:23 UTC, polyntsov commented on src/python_bindings/test_bindings.py
> +        continue
Мне в целом не очень нравится эта логика, что мы берем все классы и ищем среди них наследников нашего конкретного, как будто эта логика должна быть в модуле `desbordante`, но пока думаю можно оставить так

2023-08-12 12:24 UTC, polyntsov commented on .github/workflows/python.yml
`bindings_tests.yml` или типа того, потом ведь еще тесты на cli добавятся, они тоже про python

2023-08-12 17:34 UTC, BUYT-1 commented on src/python_bindings/test_bindings.py
> +        continue
Не понимаю, зачем нам такая логика в модуле.

2023-08-12 18:50 UTC, polyntsov commented on src/python_bindings/test_bindings.py
> +        continue
Получить все классы алгоритмов? Выглядит полезно хотя бы для этих тестов. Просто внешний код, которому нужно взаимодействовать с классами конкретного типа, делает это перебирамя вообще все классы определенные в модуле и проверяет какие из них наследуются от кого нужно, выглядит на мой взгляд странно. Эту логику можно как будто даже оставить такой же, но спрятать внутрь модуля `desbordante`

2023-08-13 05:43 UTC, BUYT-1 commented on src/python_bindings/test_bindings.py
> +        continue
Для чего получать все классы алгоритмов может понадобиться обычному пользователю? Мы же предполагаем, что пользователь возьмёт какой-то алгоритм и им будет искать, что ему нужно.

2023-08-13 12:04 UTC, polyntsov commented on src/python_bindings/test_bindings.py
> +        continue
В качестве пользователя у python_bindigs библиотеки выступает не только человек, пишущий обычные скрипты, но и CLI с тестами, им вполне может понадобиться.

2023-08-13 12:05 UTC, polyntsov approved these changes

2023-08-13 12:05 UTC, merged