Rework workflows
Mstrutov/Desbordante pull request #240
Opened 2023-08-03 15:14 UTC by BUYT-1

Splits downloading files into a separate workflows.
Fixes "'pybind11/pybind11.h' file not found" warnings.
Fixes "Post clang-tidy review comments" failures.

2023-08-08 10:34 UTC, polyntsov requested changes

2023-08-08 10:34 UTC, polyntsov commented on .github/composite-actions/download-files/action.yml
> +      if: inputs.download-datasets != 'false' && steps.cache-datasets.outputs.cache-hit != 'true'
new line, в `.github/composite-actions/download-library/action.yml` тоже

2023-08-08 10:34 UTC, polyntsov commented on .github/composite-actions/download-files/action.yml
> +name: 'Download files'
Я бы переименовал в "Download libraries"

2023-08-08 10:34 UTC, polyntsov commented on .github/composite-actions/download-files/action.yml
> +name: 'Download files'
И соответствсенно директорию в download-libraries и name, где action используется

2023-08-08 10:34 UTC, polyntsov commented on .github/workflows/cmake.yml
Думаю, стоит переименовать в `core-tests` или что-то в таком духе

2023-08-08 12:49 UTC, polyntsov approved these changes
Nice. Let's wait for @Mstrutov approve and then merge

2023-08-09 12:04 UTC, Mstrutov commented
LGTM

2023-08-09 12:05 UTC, merged