GFD paper
Mstrutov/Desbordante pull request #254
Opened 2023-08-22 20:48 UTC by AntonChern

2023-08-24 20:21 UTC, chernishev requested changes
Everything is fine, but the name of the file should be "FastGFDs - Anton Chernikov - BA thesis.pdf".

2023-08-25 10:46 UTC, polyntsov commented
Dot at the end of the commit message is not needed

2023-08-25 21:29 UTC, chernishev approved these changes

2023-08-26 11:03 UTC, polyntsov commented
Please, squash commits into one, "Add file X", "Rename file X" are not really valuable to store in history

2023-09-22 16:30 UTC, merged