Anomaly detection scenario.
Mstrutov/Desbordante pull request #255
Opened 2023-08-24 17:49 UTC by nvbobrov

2023-08-24 20:05 UTC, polyntsov commented
Please, reword the commit messages to match the style described in [wiki](https://github.com/Mstrutov/Desbordante/wiki/Development#%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D0%BE%D0%B2)

2023-08-24 21:07 UTC, BUYT-1 requested changes
Please don't copy code without understanding what it does. If you are not confident in your Python skills, write it in whatever way you can, then fix according to reviews. It's fine to look at the other examples, but make sure you understand what is happening if you take the code. Code being copied without reason makes reviewing very difficult.

2023-09-29 15:54 UTC, Elluran approved these changes

2023-10-02 13:22 UTC, polyntsov approved these changes

2023-10-02 13:23 UTC, merged