FDep Algorithm
Mstrutov/Desbordante pull request #7
Opened 2021-07-09 16:12 UTC by ArthurChains

Base implementation of FDep algorithm.

2021-08-05 20:08 UTC, Mstrutov requested changes
Привет! Хороший код, было приятно его смотреть. Осталось сделать несколько косметических правок, пару незначительных улучшений и, главное, добавление ФЗ в `fdCollection_`.

2021-08-05 20:08 UTC, Mstrutov commented on src/algorithms/FDep/FDep.h
> +    FDTreeElement* negCoverTree_{};
Точно нельзя эти два поля сделать через `std::unique_ptr<>`?

2021-08-05 20:08 UTC, Mstrutov commented on src/algorithms/FDep/FDep.cpp
> +
delete newline

2021-08-05 20:08 UTC, Mstrutov commented on src/algorithms/FDep/FDep.cpp
> +
delete newline

2021-08-05 20:08 UTC, Mstrutov commented on src/algorithms/FDep/FDep.cpp
> +    std::chrono::milliseconds elapsed_milliseconds =
`auto elapsed_milliseconds`

2021-08-05 20:08 UTC, Mstrutov commented on src/algorithms/FDep/FDep.cpp
> +}
newline

2021-12-23 23:01 UTC, achains commented
Добавлено представление найденных зависимостей в виде fdCollection. Внесены правки по остальным замечаниям.

2021-12-24 15:56 UTC, Mstrutov requested changes
Хорошо! Осталась пара мелких замечаний и CI. Нужно прогнать алгоритм через тесты.

Чтобы включить его в CI, нужно вписать его класс в конце `TestAlgorithm.cpp`. Можешь у себя прогнать: `./Desbordante_test --gtest_filter='*:-*HeavyDatasets*'`. 

Если всё будет зелёным, заливаем, если нет, напиши мне, посмотрим, что можно сделать.

2021-12-24 15:56 UTC, Mstrutov commented on run_tests.sh
> +		./fdtester_run --algo='pyro' --data="${datasets[i]}".csv --sep="${separators[i]}" --hasHeader="${header_presence[i]}" --seed=$j | grep 'TIME' >> $experiment_name/$j/results_${datasets[i]}.txt
У нас поменялась цель сборки в CMake -- теперь это Desbordante_run, так что было правильно.

2021-12-24 15:56 UTC, Mstrutov commented on src/main.cpp
> +}
newline

2021-12-24 17:54 UTC, Mstrutov approved these changes

2021-12-24 17:55 UTC, merged