Implement infrastrucutre and agorithm for Assocation rule mining
Mstrutov/Desbordante pull request #91
Opened 2022-03-10 17:14 UTC by alexandrsmirn

Here is the implementation of the Apriori algorithm based on the enumeration tree approach. Also there is introduced a new infrastructure that represents a transactional database (like classes `TransactionalData` and `Itemset`) and the base class for associtation rule mining algorithms (class `ARAlgorithm`).

2022-03-12 17:44 UTC, polyntsov requested changes
Хороший код, в нескольких местах стоит поправить логику, поместить весь код в соответствующие пространства имен, и исправить форматирование (я не оставлял несколько одинаковых комментариев к одной и той же проблеме с форматированием, так что исправить стоит не только там, где оставлены комментарии).

2022-03-12 17:44 UTC, polyntsov commented on src/algorithms/association-rules/CandidateHashTree.cpp
> +    leaf_node.children.shrink_to_fit();
Не очень понятно, зачем эта строчка нужна. Мы же зарезервировали `branching_degree_` элементов и заполнили ровно столько.

2022-03-12 17:44 UTC, polyntsov commented on src/algorithms/association-rules/CandidateHashTree.cpp
> +    auto const curr_level_element_id = node_items.at(level_num - 1);
Наверное можно использовать `operator[]` вместо `at()`, если то, что индекс валидный, проверяется ассертом выше.

2022-03-12 17:44 UTC, polyntsov commented on src/algorithms/association-rules/CandidateHashTree.cpp
> +                                  std::vector<unsigned> const& transaction_items, int tID) {
`tID` стоит переименовать в `tid`, как в функции выше

2022-03-12 17:44 UTC, polyntsov commented on src/algorithms/ARAlgorithm.h
> +        return transactional_data_->GetItemUniverse(); }
Форматирование: `}` на следующую строку.

2022-03-12 17:44 UTC, polyntsov commented on src/algorithms/ARAlgorithm.cpp
> +        auto node = path.top(); //TODO попробовать как-то синхронизировать пусть с генерацией
Все `TODO` стоит оформлять, как описано [тут](https://google.github.io/styleguide/cppguide.html#TODO_Comments), чтобы они не остались навсегда. Ну и пробел нужен после `//`. К остальным не буду оставлять комментарий

2022-03-12 17:44 UTC, polyntsov commented on src/algorithms/ARAlgorithm.cpp
> +    auto const last_child_iter = std::next(children.end(), -1);
`std::prev` вместо `std::next(, -1)`

2022-03-12 17:44 UTC, polyntsov commented on src/algorithms/association-rules/Apriori.h
> +    void AppendToTree();
Стоит отделить объявления `static` функции от не-`static`.

2022-03-12 17:44 UTC, polyntsov commented on src/algorithms/association-rules/Apriori.cpp
> +    for (unsigned index_to_skip = 0; index_to_skip < itemset.size() - 1; ++index_to_skip) { //itemset.size() is at least 2
Я бы добавил `assert(itemset.size()  >= 2);`

2022-03-12 17:44 UTC, polyntsov commented on src/algorithms/association-rules/Apriori.cpp
> +        std::cout << curr_node->support << " ";
То же самое про вывод чего-либо в алгоритме через `std::cout`.

2022-03-12 18:54 UTC, polyntsov commented on src/algorithms/association-rules/Apriori.h
> +        : ARAlgorithm(config, {"AR mining"}) {}
Если прогресс бар еще не реализован, то `phase_names` стоит оставить пустым

2022-03-14 07:28 UTC, alexandrsmirn commented on src/algorithms/ARAlgorithm.cpp
> +
А я же правильно понимаю, что остальные алгоритмы пока не помещены в algos?

2022-03-14 07:58 UTC, alexandrsmirn commented on src/model/TransactionalData.cpp
> +        }
В целом да, но в этом случае придётся ещё раз выполнять поиск в контейнере. Вот думаю, стоит или нет в данном случае пожертвовать читабельностью ради производительности?

2022-03-14 09:57 UTC, alexandrsmirn commented on src/algorithms/association-rules/CandidateHashTree.h
> +        LeafRow(LeafRow&& other) = default;
А нужнен ли тут оператор присваивания? В узле есть константное поле -- указатель, которое, мне кажется, лучше оставить константным. Это константное поле не и не даёт сделать оператор присваивания.

2022-03-14 11:43 UTC, polyntsov commented on src/algorithms/ARAlgorithm.cpp
> +
Да, не помещены, это нужно исправить, но отдельным пул-реквестом. Новый код лучше сразу помещать в неймспейсы

2022-03-14 11:47 UTC, polyntsov commented on src/model/TransactionalData.cpp
> +        }
Не совсем понимаю, в какой момент придется еще раз выполнять поиск, `transaction` же используется только в строках 47-54, а все эти строки заменяются той, что я написал выше

2022-03-14 12:01 UTC, polyntsov commented on src/algorithms/association-rules/CandidateHashTree.h
> +        LeafRow(LeafRow&& other) = default;
Мне кажется, что здесь конструктор копирования семантически подходит лучше, чем перемещения. Наверное, тут вообще стоит сделать наоборот, удалить все перемещающие операции и оставить копирующие, потому что, если я все правильно понимаю, по логике работы с этим классом происходит именно копирование `LeafRow`, а не перемещение. И перемещающий конструктор в этом классе все равно просто копирует поля.
Или, если ты считаешь, что перемещение тут подходит больше, то оператор присваивания (копирования и деструктор тоже) все равно стоит явно описать удаленным ([the rule of five](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c21-if-you-define-or-delete-any-copy-move-or-destructor-function-define-or-delete-them-all)).

2022-03-14 13:09 UTC, alexandrsmirn commented on src/algorithms/ARAlgorithm.cpp
> +
Ага, понял.
Думаю, стоит добавить это в вики

2022-03-15 11:09 UTC, alexandrsmirn commented on tests/TestApriori.cpp
> +        }
Неа, так просто не сработает. Штука примерно такая: алгоритм возвращает list actual. expeсted я сдел set'ом, чтобы удобнее было искать одно в другом. ContainerEq работает только для контейнеров одного типа. Если expected тоже сделать list-ом, как и actual, то оно запускается, но сравнение листов в этом случае работает плохо: учитывается порядок элементов, и тест не проходит, хоть и list'ы равны как множества. А гаранировать, что в actual  и expected все будет в одном порядке, не так уж просто. Можно, конечно, из алгоритма возвращать set actual вместо листа, но тогда, кажется, производительность/память может пострадать.

2022-03-15 11:36 UTC, alexandrsmirn commented on tests/TestApriori.cpp
> +                                             << expected.size() << ", got " << actual.size();
Нет, если напиасать `ASSERT_EQ(actual.size(), expected.size())` внутри самой функции вместо этих строк, то код не компилруется.

2022-03-15 11:58 UTC, polyntsov commented on tests/TestApriori.cpp
> +                                             << expected.size() << ", got " << actual.size();
Не понимаю, почему оно может не компилироваться

2022-03-15 12:00 UTC, polyntsov commented on tests/TestApriori.cpp
> +        }
да, точно, нужны одинаковые контейнеры. В таком случае можно оставить сравнение вручную, но все же все еще не ясно, зачем результат сравнения возвращать из функции, а потом каждый вызов функции оборачивать в `ASSERT_TRUE()`, почему просто не использовать тут `FAIL()` и `SUCCES()`.

2022-03-15 12:10 UTC, alexandrsmirn commented on tests/TestApriori.cpp
> +                                             << expected.size() << ", got " << actual.size();
Вот такое сообщение:
`or: could not convert ‘testing::internal::AssertHelper(testing::TestPartResult::kFatalFailure, ((const char*)"Desbordante/tests/TestApriori.cpp"), 15, gtest_ar.testing::AssertionResult::failure_message()).testing::internal::AssertHelper::operator=(testing::Message())’ from ‘void’ to ‘testing::AssertionResult’`

Оно работало бы, если мой метод возвращал `void`, а не `testing::AssertionResult`, сейчас проверил.

2022-03-15 12:15 UTC, polyntsov commented on tests/TestApriori.cpp
> +                                             << expected.size() << ", got " << actual.size();
>Оно работало бы, если мой метод возвращал void, а не testing::AssertionResult, сейчас проверил.

Это я как раз и предлагаю сделать, чтобы не оборачивать каждый вызов этом функции в `ASSERT_TRUE()`.

2022-03-15 12:19 UTC, alexandrsmirn commented on tests/TestApriori.cpp
> +        }
Подсмотрел такой паттерн в файле TestFdMine, там есть очень похожая функция, которая сравнивает списки зависимостей, и результат возвращает именно таким образом.
А по поводу FAIL() и SUCCESS() -- в целом да, если тип возвращаемого значения функции сделать void, то впринципе можно переписать и на них, тогда и `ASSERT_EQ(actual.size(), expected.size())` будет работать. Но стоит ли переделывать, если в целом и так работает?

2022-03-15 12:23 UTC, polyntsov commented on tests/TestApriori.cpp
> +        }
@Mstrutov что думаешь?

2022-03-15 12:37 UTC, polyntsov commented on tests/TestApriori.cpp
> +        }
Вместо `ContainerEq` должны сработать `UnorderedElementsAreArray()` или `WhenSorted()`

2022-03-15 14:06 UTC, alexandrsmirn commented on src/model/TransactionalInputFormat.h
> +    virtual unsigned item_column_index() const noexcept = 0;
Долго думал над тем, как бы тут сделать лучше -- и пока что ни к чему не пришёл. На самом деле, третий метод, по-сути, не имеет смысла для `Singular`, так что по логике тогда и с ним нужно что-то сделать. Вообще, я думаю, что здесь нужно будет применить какой-то паттерн, чтобы сделать изящнее, а пока оставлю как есть.

2022-03-17 07:38 UTC, Mstrutov commented on tests/TestApriori.cpp
> +        }
Думаю, можно так поступить:

1. Перейти на `FAIL()`, `SUCCESS()`. Будет более читаемо без оборачивания в `ASSERT_TRUE()`. 

2.* Возможно, у gtest есть возможность подсунуть кастомный `==`, чтобы по `ASSERT_EQ` срабатывал он, а не дефолтный оператор. Но тут я, во-первых, не уверен, что будет сильно читаемее, а, во-вторых, что это можно легко сделать. Поэтому это просто доп. пункт -- если будет время и получится сделать, то здорово, если не получится, ничего страшного, оставляем так.

2022-03-17 07:40 UTC, Mstrutov commented on tests/inputData/transactionalData/rules-kaggle.csv
> +10,COCK
SUS

2022-03-17 12:39 UTC, alexandrsmirn commented on tests/TestApriori.cpp
> +        }
Да, окей, тогда так и сделаю, а про оператор запишу в TODO

2022-03-18 20:23 UTC, polyntsov approved these changes
LGTM!

2022-03-19 09:54 UTC, merged