Implement type system
Mstrutov/Desbordante pull request #92
Opened 2022-03-12 19:11 UTC by polyntsov

Implements classes for types and classes describing typed columns, relational typed data. Knowing the type of data in a column is necessary to collect statistics and identify possible typos in typo mining workflow.

2022-03-22 06:46 UTC, Mstrutov requested changes

2022-03-22 06:46 UTC, Mstrutov commented on src/model/ColumnTypedData.h
> +    TypedColumnData CreateFrom();
Я бы вообще здесь всё статическими методами сделал, потому что у состояния Factory почти нет смысла -- оно просто нужно, чтобы передаваться между методами.

Хотя вообще, можно себе представить ситуацию, когда мы создаём Фабрику, складывая туда unparsed, а потом генерируем из неё несколько раз разные ColumnData, поэтому стоит так оставить. К тому же, так не надо передавать набор col, unparsed, is_null_equal_null между внутренними методами.

Всё же, кажется, сейчас она будет в основном использоваться так: сконструировать - создать ColumnData - забыть. Как насчёт сделать `static TypedColumnData CreateFrom(col, unparsed, is_n_eq_n)`, в котором будет реализован этот сценарий?

2022-03-22 06:46 UTC, Mstrutov commented on src/model/types/MixedType.h
> +    std::byte* MakeValue(T literal, Type const* type) const {
Сейчас вызов сразу оборачивается в unique_ptr -- в целом, не вижу причин не оборачивать, поэтому почему бы сразу здесь не возвращать умный указатель?

2022-03-22 06:46 UTC, Mstrutov commented on src/model/types/MixedType.h
> +    TypeId RetrieveTypeId(std::byte const* value) const {
Этот и многие другие методы можно сделать `static` -- рассматривал этот вариант?

Вообще, clang-tidy из CLion'а подсвечивает в твоём коде несколько мест, где можно const убрать, auto использовать, expiicit проставить и т.п. 

1) Можешь плз посмотреть эти замечания в CLion?
2) Ещё вопрос: ты прогонял код через clang-format? Хотя подозреваю, он у тебя к vim'у подключен

2022-03-22 08:27 UTC, polyntsov commented on src/model/types/Type.h
> +        return type_id_ == +TypeId::kInt /* || type_id_ == +TypeId::kBigInt */ ||
BigInt должен быть классом с поддержкой длинной арифметики. Как псевдоним для String он объявлен временно, пока кто-нибудь не сделает длинную арифметику

2022-03-22 08:30 UTC, polyntsov commented on src/model/types/UndefinedType.h
> +        (void)l, (void)r;
В `[[maybe_unused]]` меня смущало слово `maybe`. `(void)` же явно показывает намерение: что `l` и `r` сознательно и всегда игнорируются. Но да, читать это сложнее, если не знать заранее. Сложно

2022-03-22 08:31 UTC, polyntsov commented on src/model/types/NumericType.h
> +class INumericType : public Type {
Да, потому что шаблонный класс использоваться невозможно без указанного явно параметра шаблона, а тогда вся суть интерфейса теряется.

2022-03-22 08:38 UTC, polyntsov commented on src/model/ColumnLayoutTypedRelationData.cpp
> +     * Maybe we need column-based parsing in addition to row-based in CSVParser */
Думал так сделать (ну и кажется это единственный рабочий вариант), но решил, что это сделает код более запутанным. Но видимо надо все же сделать

2022-03-22 08:39 UTC, polyntsov commented on tests/TestTypedColumnData.cpp
> +                          "iris.csv", ',', false)));
`kNull` и `kEmpty` не бывает в типе колонки, если в колонке только nullы или пустые строчки, то ее тип определяется как `kUndefined`.
У нас нет ни одного датасета, где колонки `kBigInt`. Добавить новый?

2022-03-22 08:49 UTC, polyntsov commented on src/model/ColumnTypedData.h
> +    TypedColumnData CreateFrom();
Сначала тут все методы были статическими, но как только я понял, что тогда между всеми методами придется передавать по три параметра (которые сейчас поля), я решил, что лучше сделать их нестатическими. Из  статического `CreateFrom` не получится вызывать нестатические методы, автоматически и их придется сделать статическими. Поэтому нужно сразу решить, будут ли они все статическими (и почти у каждого будет по 3 одинаковых параметра), либо все нестатическими.
И кажется, что сейчас  два последовательных вызова `CreateFrom` от одного объекта могут работать неправильно, потому что `CreateFrom` может внутри себя испортить `unparsed` (перемещая строки из него в 135ой строке ColumnTypedData.cpp)ю

2022-03-22 09:01 UTC, polyntsov commented on src/model/types/MixedType.h
> +    std::byte* MakeValue(T literal, Type const* type) const {
Я не использовал тут unique_ptr для того, чтобы интерфейс был как во всех остальных местах (везде raw указатели). Но наверное все же да, стоит обернуть

2022-03-22 09:13 UTC, polyntsov commented on src/model/types/MixedType.h
> +    TypeId RetrieveTypeId(std::byte const* value) const {
Рассматривал и решил оставить не `static`. Тут на самом деле ни у каких классов типов (кроме NullType) нет внутреннего состояния, но при этом есть виртуальные методы и в теории все методы, которые не используют виртуальные методы, можно пометить `static`. Я не помечал их `static`, чтобы они выглядели и использовались так же, как виртуальные, и потому что их не очень много, но вообще сложно. С одной стороны есть единообразие, с другой, чтобы использовать эти методы нужен всегда объект и приходится писать `static_cast`ы:
```cpp
if (type_id == +TypeId::kMixed) {
    static_cast<MixedType const&>(type).Something(values);
    // или так, но это по-моему еще страннее:
    // MixedType(is_null_equal_null).Something(values);
}
// vs
if (type_id == +TypeId::kMixed) {
    MixedType::Something(values);
}
```
Не знаю, что из этого лучше.

Прогонял через `clang-format`, но не весь код, а там, где сомневался в том, как правильно форматировать, что неправильно.  
А конструкторы, непомеченные `explicit`, это конечно ошибка

2022-03-22 09:16 UTC, polyntsov commented on src/model/types/MixedType.h
> +    TypeId RetrieveTypeId(std::byte const* value) const {
Вообще наверное все-таки стоит помечать `static`, это по идее только расширит возможности использования. `static` методы ведь все еще можно вызывать через `.` у объекта, так что можно будет и static_cast'ы писать, если очень уж захочется.

2022-03-22 10:05 UTC, polyntsov commented on src/model/types/MixedType.h
> +    std::byte* MakeValue(T literal, Type const* type) const {
Сейчас попробовал исправить это. По идее если использовать unique_ptr, то не только тут, а вообще во всех методах, которые аллокацию делают, а так сделать уже не получится. Поэтому и тут оставляю raw pointer.

2022-03-23 05:23 UTC, Mstrutov commented on src/model/types/UndefinedType.h
> +        (void)l, (void)r;
Ну, в https://en.cppreference.com/w/cpp/language/attributes/maybe_unused `[[maybe_unused]]`описывается как

> Suppresses warnings on unused entities. 

Так что, видимо, он предназначен в том числе для случаев, когда переменная явно не используется при любых настройках компиляции, и надо просто привыкать, что он так назван. К тому же, здесь при чтении кода понятно, что бросается исключение и никаких операций с аргументами не происходит. Какие-то макросы объявлять или функцию-заглушку изобретать я тут не вижу смысла.

Го `[[maybe_unused]]`

2022-03-23 05:29 UTC, Mstrutov commented on src/model/ColumnLayoutTypedRelationData.cpp
> +     * Maybe we need column-based parsing in addition to row-based in CSVParser */
Да, кажется это не по SOLID. Но тут думаю будет более-менее выглядеть, понятно, что происходит.

Возможно, правильно, но запарно было бы реализовать итератор у CSVParser'а, позволявший бы проитерироваться по ячейкам.

2022-03-23 05:30 UTC, Mstrutov commented on tests/TestTypedColumnData.cpp
> +                          "iris.csv", ',', false)));
Ок, добавь плз `kBigInt`, хотя бы синтетический, собранный руками.

2022-03-23 05:33 UTC, Mstrutov commented on src/model/ColumnTypedData.h
> +    TypedColumnData CreateFrom();
Я думаю, не надо целиком всё статическим делать.

Мб заприватить конструктор и нестатический `CreateFrom`, а наружу оставить только
```
static TypedColumnData CreateFrom(col, unparsed, is_n_eq_n) {
    auto factory = make_unique<TCDFactory>(col, unparsed, is_n_eq_n);
    return factory.CreateFrom();
}
```
?

2022-03-23 11:30 UTC, polyntsov commented on src/model/ColumnLayoutTypedRelationData.cpp
> +     * Maybe we need column-based parsing in addition to row-based in CSVParser */
По-моему отличная идея с итератором и может сразу стоит сделать так? (но видимо отдельным пулреквестом)

2022-03-24 05:03 UTC, Mstrutov commented on src/model/ColumnLayoutTypedRelationData.cpp
> +     * Maybe we need column-based parsing in addition to row-based in CSVParser */
Да, давай в этом ПР оставим так, не будем городить лямбды-колбэки. В отдельном запилишь итератор?

2022-03-24 05:32 UTC, Mstrutov commented on src/model/ColumnLayoutTypedRelationData.cpp
> +     * Maybe we need column-based parsing in addition to row-based in CSVParser */
Завёл таску, добавил туда пункт с итератором #96

2022-03-25 04:46 UTC, Mstrutov approved these changes

2022-03-25 04:46 UTC, Mstrutov commented on tests/TestTypes.cpp
> +    test(-21, -7);
Думаю, в тестах нужно ещё фиксировать, что происходит, если поделить на 0.

2022-03-25 04:46 UTC, merged

2022-03-25 07:23 UTC, polyntsov commented on tests/TestTypes.cpp
> +    test(-21, -7);
По стандарту ub, на практике, думаю, происходит sigfpe (на линуксе). Кажется, ни то, ни то нельзя отловить в тестах.