Implement and integrate FUN algo
Mstrutov/Desbordante pull request #98
Opened 2022-03-31 13:36 UTC by studokim

Closes #20
Partially implements #63 (places algorithms into namespace `algos`)

2022-04-01 08:12 UTC, polyntsov requested changes
Какой-то очень странный diff у `pull_datasets.sh`, проверь.

Я не смотрел логику, совсем не успеваю. @Mstrutov, посмотри, пожалуйста (:

2022-04-01 08:12 UTC, polyntsov commented on src/algorithms/FUN.cpp
> +    for (auto pair : fds_) {
Тут стоит использовать structured binding:
```cpp
for (auto const& [rhs, lverticals] : fds_) {
}
```
Сделает код более читаемым и позволит избежать лишнего копирования.

2022-04-01 08:12 UTC, polyntsov commented on src/algorithms/FUN.h
> +    FunQuadruple toQuadruple(Column const& attribute);
Складывается впечатление, что какие-то из этих методов на самом деле должны быть методами `FunQuadruple`.

2022-04-01 08:12 UTC, polyntsov commented on src/algorithms/FUN.cpp
> +    return s.GetColumnIndices().is_proper_subset_of(l.candidate.GetColumnIndices());
Возможно стоит сделать такой метод у `Vertical` (рядом с `Contains()`), выглядит полезно

2022-04-01 08:33 UTC, studokim commented on src/algorithms/FUN.h
> +    virtual ~FunQuadruple() = default;
> diff у pull_datasets.sh
это `chmod +x`
Остальные комментарии позже исправлю, спасибо

2022-04-02 08:51 UTC, Mstrutov requested changes
Хороший код, очень добротно перенесён алгоритм из статьи. Осталось только одно место оптимизировать и всякие константные ссылки расставить.

Я не все места, где надо pass-by-value на pass-by-reference поменять. Советую открыть код в CLion-е, или прогнать через clang-tidy, если вдруг знаешь, как это делать, --- там некоторые места подсветятся, которые тоже стоит подправить.

2022-04-02 08:51 UTC, Mstrutov commented on src/algorithms/FUN.cpp
> +    auto positionAtLK = std::find(lK.begin(), lK.end(), l);
Насколько я помню, в lattice-based алгоритмах, таких как TANE и FUN, проблемы с производительностью особенно заметны на широких датасетах. Там два бича:
1) Количество элементов в уровне --- порядка биномиального коэффициента, то есть зависит экспоненциально от ширины датасета. Всем операциям с линейной+ сложностью относительно размера уровня становится плохо.
2) Больше колонок, значит, надо чаще пересекать партиции, а это тяжело.

В общем, чтобы понять, где узкие места, надо именно представлять, что ширина датасета большая и смотреть, какие методы от этого больше всего страдают.

Например, 
computeClosure --- это примерно O(|lk| * |columns| * (T(find_lk) + |lk|))
computeQClosure --- O(|lk|^2)
purePrune --- O(|lk|^2 * T(erase_lk))
genCandidate --- O(|lk| * |columns| * T(intersect))
Я считал |lk| ~ |lkMinus1|. T(...) --- время операции. Можно пренебречь |columns|. displayFD можно не рассматривать --- он выглядит довольно эффективно, но, если ФЗ много, всё равно будут проблемы, эту сложность трудно убрать.

Видно, что среди методов без пересечений партиций самые тяжелые --- computeClosure и purePrune. list -- грамотный выбор, засчёт константности удаления purePrune становится O(|lk|^2), а в computeClosure нас всё равно ограничивает |lk| для поиска максимума. Возможно, получится ускорить в константу раз, если подобрать структуру для level, а которой и erase, и find за O(1) --- какую-нибудь хеш-таблицу.

Вообще, прирост вряд ли будет большим, а поанализировать-позамерять-покопаться в коде придётся, так что отложим на другой ПР, в котором будем оптимизировать FUN, если это понадобится.

2022-04-02 08:51 UTC, Mstrutov commented on src/algorithms/FUN.cpp
> +        for (FunQuadruple s : lKMinus1) {
Здесь и в других местах стоит передавать по ссылке: `... const& s`.

2022-04-02 08:51 UTC, Mstrutov commented on src/algorithms/FUN.cpp
> +    for (auto&& it = lK.begin(); it != lK.end();) {
Понимаю, что `&&` универсальнее, поэтому им удобнее пользоваться, но лучше явно использовать что-то константное, если ты будешь только читать из элементов (erase относится ко всей коллекции).

`const&` и `cbegin`

2022-04-02 08:51 UTC, Mstrutov commented on src/algorithms/FUN.cpp
> +        FunQuadruple l = *it;
тут бы тоже избежать копирования

2022-04-02 08:51 UTC, Mstrutov commented on src/algorithms/FUN.cpp
> +    for (auto&& A : schema_->GetColumns()) {
тоже лучше `const&`

2022-04-02 08:51 UTC, Mstrutov commented on src/algorithms/FUN.cpp
> +void FUN::displayFD(level lKMinus1) {
Тут какое-то жосское копирование может быть, давай `const&`.

2022-04-02 08:53 UTC, Mstrutov commented on src/algorithms/FUN.h
> +    virtual ~FunQuadruple() = default;
Вообще, я где-то видел, что стоит делать деструктор виртуальным, даже если нет ни потомков, ни других виртуальных методов, просто чтобы в будущем, когда это всё появится, не забыть про деструктор.

Так что я за виртуальный деструктор здесь.

2022-04-02 11:49 UTC, polyntsov commented on src/algorithms/FUN.cpp
> +    for (auto&& it = lK.begin(); it != lK.end();) {
Передавать итераторы по ссылке по-моему бессмысленно и можно сделать просто `auto`.

2022-04-02 12:13 UTC, polyntsov commented on src/algorithms/FUN.h
> +    virtual ~FunQuadruple() = default;
Не очень понятно, какие плюсы он дает. Кажется, только один: если кто-нибудь когда-нибудь добавит в этот класс виртуальные методы и отнаследуется от него, а потом удалит объект наследника через указатель на базовый класс, то этот деструктор, объявленный заранее, поможет избежать утечки (при этом не факт, что это будет желаемым поведением, возможно само удаление через объект на базовый класс -- баг, добавленный заранее виртуальный деструктор только усложнит его поиск). А при условии включенного ворнинга и санитайзера в дебаг моде, который найдет утечку, если она произойдет, совсем не понятно..
При этом минусы:
Появляются ограничения на этот тип, например, он перестает быть `TriviallyCopyable`.
Если компилятор не соптимизирует, то генерируется vtable, ко всем объектам класса добавляется указатель на нее (где один деструктор). Если компилятор не сможет оптимизировать виртуальный вызов деструктора на прямой (или инлайнинг, как если бы тут был non-virtual default деструктор), то получится очень много оверхеда, если кто-то захочет удалять объекты этого класса в цикле

2022-04-02 18:15 UTC, studokim commented on src/algorithms/FUN.h
> +    virtual ~FunQuadruple() = default;
В остальных алгоритмах нигде нет виртуального. Тогда уберу для единообразия

2022-04-03 13:41 UTC, studokim commented on src/algorithms/FUN.cpp
> +    return s.GetColumnIndices().is_proper_subset_of(l.candidate.GetColumnIndices());
Уточнил: даже в FUN не требуется именно proper subset. Заменил на уже имеющийся в Vertical `Contains()`, Vertical менять не стал

2022-04-04 18:18 UTC, polyntsov requested changes
Нужен неймспейс. И проверь нейминг (:

2022-04-04 18:18 UTC, polyntsov commented on src/algorithms/FUN.h
> +struct FunQuadruple {
Я на самом деле не очень хорошо понимаю, как этот класс устроен и используется. У этого класса есть какие-нибудь инварианты? Если да, то поля точно не должны быть публичными, а обращение к ним должно происходить через accessors/mutators, ну и слово `_` подчеркивание в конце + слово [struct заменить на class](https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes). 
Если все же инвариантов нет, а объекты используются как хранилище полей, то наверное можно оставить так.

2022-04-04 21:28 UTC, polyntsov approved these changes
LGTM!
Thanks for the namespaces <3

2022-04-11 04:40 UTC, Mstrutov approved these changes

2022-04-11 04:40 UTC, merged