Implement functionality to find specific lines containing typos
Mstrutov/Desbordante pull request #99
Opened 2022-03-31 14:05 UTC by polyntsov

Implements `TypoMiner` methods to find lines in cluster that differ from the most frequent value in a cluster by less than specified epsilon. Extends the clusters finding functionality with a ratio of non-frequent values per cluster parameter that specifies which clusters should be treated as containing typos.

2022-04-03 07:53 UTC, Mstrutov requested changes

2022-04-03 07:53 UTC, Mstrutov commented on tests/TestTypoMiner.cpp
> +    for (FD const& fd : typo_miner->GetApproxFDs()) {
Я бы так сделал:

1. Проверил, что actual_fds == expected_fds (сейчас проверяется только Precision, то есть что typo_miner находит только правильные фз).
2. Проверил, что actual_typo_clusters == expected_typo_clusters через FindClustersWithTypos
3. Проверил, что для каждого кластера actual_typos == expected_typos

Понимаю, что 1 --- это ответственность алгоритма приближённых ФЗ, а 2 --- простого поиска опечаток, без подсветки линий, и эти пункты должны были быть проверены в соответствующих тестах. Вообще, 2 прямо несколькими строчками выше проверяется, поэтому его точно не надо здесь повторять.

Но насчёт 1, лучше не мешать проверку фз, причём неполную, и опечаток в одном цикле. Либо полностью проверить все фз, потом перейти к проверке опечаток, либо вообще не сверять фз. 

Я склоняюсь к последнему варианту, потому что это всё же юнит тест, который проверяет, что typo_miner находит правильные строчки для данной фз, данного кластера, радиуса и отношения. Значит, в тесте должна быть инициализация (Execute) и цикл по expected фз и cluster с данными radius, ratio, в котором сверяются typo_lines.

Стоит ещё подумать, что будет с FindLinesWithTypos, если туда случайно загнать неверную фз или cluster: вдруг на сервере произойдёт ошибка при перекладывании данных и не факт, что придёт тот же cluster, который взяли из FindClustersWithTypos. Возможно, зафиксировать это поведение в отдельном тест кейсе.

2022-04-03 07:53 UTC, Mstrutov commented on src/algorithms/TypoMiner.cpp
> +    model::Type const& type = col_data.GetType();
Как-то многовато инициализации

Может, вот эти пониже перенести?
```
    std::vector<util::PLI::Cluster::value_type> typos;
    std::vector<std::byte const*> const& data = col_data.GetData();
    unsigned long num_of_close_values = 0;
```

2022-04-03 07:53 UTC, Mstrutov commented on src/algorithms/TypoMiner.cpp
> +        if (ratio_ == 1) {
Надо наверное в коде комментом описать, что делает `ratio_`. Это же минимальная доля значений-выбросов, с которой считаем кластер содержащим опечатки?

Наверное, здесь должно быть `==0`?

2022-04-03 07:53 UTC, Mstrutov commented on src/algorithms/TypoMiner.cpp
> +    if (most_freq_value == 0 || col_data.IsMixed() || !type.IsMetrizable()) {
Везде, где есть most_freq_value, замени 0 на `util::PositionListIndex::singleton_value_id_`, а то совсем неочевидно, что это значит. Такое сравнение можно вынести в `isSingleton`.

2022-04-03 07:53 UTC, Mstrutov commented on src/algorithms/TypoMiner.cpp
> +        int const value = (probing_table_value == 0) ? 1 : frequencies.at(probing_table_value);
unsigned

2022-04-03 07:53 UTC, Mstrutov commented on src/algorithms/TypoMiner.cpp
> +        unsigned const value = (probing_table_value == 0) ? 1 : frequencies.at(probing_table_value);
Я бы переназвал value -> frequency, most_frequent_value -> largest_frequency

2022-04-03 07:53 UTC, Mstrutov commented on src/algorithms/TypoMiner.h
> +        return static_cast<model::IMetrizableType const&>(type).Dist(l, r) < radius_;
clang-tidy очень просит юзать здесь dynamic_cast

хотя понятно, что случай type not IMetrizable отфильтровывается раньше

2022-04-03 11:05 UTC, polyntsov commented on src/algorithms/TypoMiner.h
> +    double radius_ = -1; /* Maximal distance between two values to consider one of them a typo */
Почему? Если расстояние между значениями меньше `radius_`, то они считаются близкими. То есть `radius_` это максимальное значение для расстояния

2022-04-03 11:11 UTC, polyntsov commented on src/algorithms/TypoMiner.cpp
> +        if (ratio_ == 1) {
Максимальная доля. Кажется все же `== 1`: если все значения уникальны, то считаю, что все значения подходят под опечатки. Если `ratio_` равно 1, то соответственно весь кластер и возвращаем, если не равно, то выбросов с такой долей нет.

2022-04-03 11:12 UTC, polyntsov commented on src/algorithms/TypoMiner.h
> +        return static_cast<model::IMetrizableType const&>(type).Dist(l, r) < radius_;
Мне кажется, что тут менять на `dynamic_cast` не стоит, тип-то точно известен

2022-04-03 11:20 UTC, polyntsov commented on tests/TestTypoMiner.cpp
> +    for (FD const& fd : typo_miner->GetApproxFDs()) {
Насчет последнего: я решил, что это проблема вызывающего кода. Тем более проверить, что фз или кластер неправильные довольно трудно. Особенно при условии, что этот метод может вызываться без предварительного вызова `Execute()`, то есть в во время выполнения этого метода не будет информации о намайненных `approx_fds_`

2022-04-03 13:38 UTC, Mstrutov commented on tests/TestTypoMiner.cpp
> +    for (FD const& fd : typo_miner->GetApproxFDs()) {
Ок, сделай тогда коммент к методу и пропиши там, что при неверных fd, cluster будет unexpected behavior.

2022-04-03 13:45 UTC, Mstrutov commented on src/algorithms/TypoMiner.h
> +    double radius_ = -1; /* Maximal distance between two values to consider one of them a typo */
`radius_` -- это максимально разрешённое расстояние для двух значений кластера. Если расстояние больше радиуса, считаем одно из них опечаткой --- правильно?

Просто именно английская формулировка меня сбила с толку --- как будто "радиус --- максимальное расстояние, при котором мы считаем одно из значений опечаткой".

Поэтому я думаю, что лучше как-нибудь так:
* Minimal distance between two values to consider one of them a typo
* Maximal distance between two values to consider them equal

2022-04-03 13:58 UTC, Mstrutov commented on src/algorithms/TypoMiner.cpp
> +        if (ratio_ == 1) {
Да, перечитал код про `ratio_`, всё ок. 
+ спасибо за коммент в коде про `ratio_` :)

2022-04-03 16:00 UTC, polyntsov commented on src/algorithms/TypoMiner.h
> +    double radius_ = -1; /* Maximal distance between two values to consider one of them a typo */
> Если расстояние больше радиуса, считаем одно из них опечаткой --- правильно?

Нет, наоборот, если расстояние **меньше** радиуса, то считаем одно из них опечаткой.

2022-04-03 16:14 UTC, Mstrutov commented on src/algorithms/TypoMiner.h
> +    double radius_ = -1; /* Maximal distance between two values to consider one of them a typo */
Аааа, всё, я понял семантику. Мы считаем за опечатки только близкие к самому частому значения. Тогда всё ок.

2022-04-04 04:45 UTC, Mstrutov approved these changes

2022-04-04 17:53 UTC, merged